### ISSUE TITLE
Multiple database user connections

### ISSUE THREAD

**Issue by michaelirey** [influitive/apartment#101]
This may be somewhat addressed in https://github.com/influitive/apartment/issues/69

We are looking for a multi-tenant separate database solution. However, the contracts we have with our clients state: The connection used to access a specific tenant's data and database will not be allowed to access another tenant's data.

From what I can tell from experimenting with apartment, the same privileged database user is used to connect to all databases.

Please correct me if I am wrong.

Is this a future feature looking to be included in apartment? If so I can help contribute.

**Comment by mikecmpbll** [comment]
> From what I can tell from experimenting with apartment, the same privileged database user is used to connect to all databases.

that's correct. with the full-config support added for multi-host capabilities fairly recently, you should be able to use full connection details including different users etc for each tenant. this code is still experimental.
