### ISSUE TITLE
undefined method `configure' for Apartment:Module

### ISSUE THREAD

**Issue by AhmedElSharkasy** [influitive/apartment#126]
I am having this weird error when i am trying to rake db:migrate, this error is related to the initialize filer, my configurations is so simple, could you advise?

Apartment.configure do |config|
  config.excluded_models = %w{Tenant}
  config.use_schemas = true
  config.tenant_names = lambda{ Tenant.pluck(:name) }
end

am using apartment version 0.24.3

@bradrobertson

**Comment by abhchand** [comment]
Looks like it's been a few years, but I came across this issue while developing a Rails Engine that depends on the `apartment` gem. 

I didn't want to auto-require the `apartment` gem. Instead, I wanted to manually require it in my initializer (the reasoning for this is outside the scope of this topic, but it involves my app supporting an opt-in multi-tenant mode which is when I'd want to gem required

As mentioned above, the gem needs to be required in the Gemfile. I originally had

```ruby
group :development, :test do
  gem "apartment", require: false
end
```

This worked great on `development` but caused a problem while running specs in `test`. It threw the `undefined method \`configure' for Apartment:Module` error that caused this thread to be opened. (I don't know exactly what causes it to throw this error, I didn't bother digging too deep into the stack trace)

Solution was simply requiring it for `test` but not for `development`

```ruby
group :development do
  gem "apartment", require: false
end

group :test do
  gem "apartment"
end
```

Not the cleanest solution, but also not the messiest :)
