### ISSUE TITLE
Apartment persists search_path when switching between schemas

### ISSUE THREAD

**Issue by aliekens** [influitive/apartment#133]
I'm using Apartment on a Postgres setup. I have noted that when I'm trying to access non-existing schemas, that the reported search_path is dependent on previous tenant switches, persisting some of these tenants (in the search_path?) among user sessions.

In the example below, I try to access a non-existing tenant, giving me the error that this schema is invalid and could not be found in the search_path of the non-existing tenant nor in public.

Next, I access an existing tenant, where Apartment correctly switches to this tenant.

Next, I try to access the non-existing tenant again, but now Apartment reports that it could not find the non-existing tenant in the *existing* tenant's schema. Apartment shouldn't be trying to access this other tenant when I'm trying to access a faulty one.

```
$ rails console
Loading development environment (Rails 4.0.4)
irb(main):001:0> Apartment::Database.switch("non_existing_tenant")
Apartment::SchemaNotFound: One of the following schema(s) is invalid: non_existing_tenant, "public"
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:95:in `rescue in connect_to_new'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:88:in `connect_to_new'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/abstract_adapter.rb:100:in `switch'
	from (irb):1
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):002:0> Apartment::Database.switch("existing_tenant")
=> "\"existing_tenant\""
irb(main):003:0> Apartment::Database.switch("non_existing_tenant")
Apartment::SchemaNotFound: One of the following schema(s) is invalid: non_existing_tenant, "existing_tenant"
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:95:in `rescue in connect_to_new'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:88:in `connect_to_new'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/abstract_adapter.rb:100:in `switch'
	from (irb):3
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/aliekens/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

The problem popped up when I noticed I could gain access to a tenant when testing for the nil tenant. I'm using the Subdomain elevator and my app should give an error when accessing the nil domain, not give me full access to a previously used tenant.

**Comment by rabbitt** [comment]
You should be able to revert the connection back to public after every request (please correct me if I'm wrong) by adding this to your elevator:
```
module Apartment
  module Elevetors
    class MyElevator < Generic
      def call(*args)
        super
      ensure 
        Tentant.reset
      end
    end
  end
end
```

**Comment by bradrobertson** [comment]
Ya one change I'm going to make to the Generic elevator actually is to use `switch` with a block, which basically does what you've suggested (uses `ensure` to make sure you go back to the previous tenant)

**Comment by rabbitt** [comment]
@bradrobertson, so you're thinking something like so? 
```ruby
# lib/apartment/elevators/generic.rb
      def call(env)
        . . . 
        begin
          previous = Tenant.current
          Tenant.switch! database if database
          @app.call(env)
        ensure
          Tenant.switch!(previous) rescue Tenant.reset 
        end
      end
```

or more along the lines of this:
```ruby
# lib/apartment/adapters/abstract_adapter.rb
      def switch!(tenant = nil)
        ...
      end

      def switch(tenant = nil, &block)
        raise ArgumentError, 'block expected, none given' unless block_given?

        previous = current_tenant
        begin
          switch!(tenant)
          block.call
        ensure 
          switch_tenant!(previous) rescue reset
        end
      end```

**Comment by bradrobertson** [comment]
the 2nd one... Since switch with a block does the `ensure` we don't need to duplicate it in the middleware.

But the adapter code itself `def switch` is already implemented, somewhat similar to what you have so it's really just the middleware that should change

**Comment by rabbitt** [comment]
Ah - I probably should have looked at the more recent code and I would have seen the newer #switch() that you speak of. But yeah, I grok ya.

**Comment by hiattp** [comment]
I'm not sure if this is related but I'm seeing a seemingly related issue in my RSpec test suite where roughly 20% of the time (and only on our CI server) a test will fail with:

    One of the following schema(s) is invalid: "company_1" "company_1", "shared_extensions"

I have Apartment::Tenant.reset in both before and after hooks (shouldn't be necessary?) and I've tried manually setting the search path (`Apartment.connection.schema_search_path = "public,shared_extensions"`) in efforts to weed out this failure but so far no luck. I'm at a bit of a loss for what to try next. We are creating/using/tearing down schemas during the test cases (both within integration tests, which is where we usually see this failure, and before/after blocks. But it seems like sometimes this process breaks down somewhere and leaves a schema in place. This is my (seemingly over-aggressive) after block:

    config.after(:each) do
      Apartment::Tenant.reset
      Apartment.connection.schema_search_path = "public,shared_extensions"
      Company.all.each { |c| Apartment::Tenant.drop("company_#{c.id}") }
      Capybara.reset_sessions!
      DatabaseCleaner.clean
    end

And on a potentially related note sometimes the failure is that a table doesn't exist, as if the switch into a tenant was not successful. Again, these only happen a minority of the time, and even sporadically within the same seed.

**Comment by hiattp** [comment]
Ok I think you can ignore my comment, I think those were leftover ajax requests that were executing after the after hook started. I'm guessing both issues were caused by that effect, my suite seems to be way more consistent after accounting for it.
