### ISSUE TITLE
switch tenants subdomains

### ISSUE THREAD

**Issue by brunoporto** [influitive/apartment#134]
parameters: 
Database: postgresql 
schema: yes 
excluded_subdomains = ['www', 'public'] 

Domain 1: 
www.site.com 

Domain 2: 
mytenant.site.com 

if i open a tab with domain1 it will use the current_tenant as "public". But if i open the another tab with domain2, both tabs given the tenant as "mytenant".

temporary fix:
# application_controller.rb

before_action :verify_tenant
def verify_tenant
    Apartment::Database.reset if Apartment::Elevators::Subdomain.excluded_subdomains.include?(request.subdomain)
end

Would make an adjustment within the gem itself if possible.

Thanks.

**Comment by RtypeStudios** [comment]
Last night i'm having exactly the same issue but your 

    # config/initializers/apartment.rb 
    Rails.application.config.middleware.insert_before 'ActiveRecord::ConnectionAdapters::ConnectionManagement', 'Apartment::Elevators::Subdomain'

Change doesn't seem to be working for me nor does:

    before_action :verify_tenant
    def verify_tenant
    Apartment::Database.reset if Apartment::Elevators::Subdomain.excluded_subdomains.include?  (request.subdomain)
    end

Both still seem to cause issues, are you both using unicorn or some other server? I know unicorn does some funky things with its threading and wondered if that is what is causing the issue.
