### ISSUE TITLE
Creating tenants in seeds.rb

### ISSUE THREAD

**Issue by ToMoCoop** [influitive/apartment#138]
When i've updated the gem, I think this commit is causing me problems:
https://github.com/influitive/apartment/commit/39813f9cd7c6914e1600421c1ac57c0fa99b6152#diff-0379e8683973008c80572d78a24a3969

Basically, I am creating the tenants in the seeds.rb file, which then in turn runs the seeds file again for each tennant (as my pluck method drags them from the database). I then rather obviously get errors relating to records that already exist.

Is there a way to seed excluded models as well as create and seed tenants in one go with something like db:seed? I feel like i'm missing something...

**Comment by brunowego** [comment]
Thanks @lucaspiller 👍
