### ISSUE TITLE
How can I run a migration for a single database?

### ISSUE THREAD

**Issue by HuckyDucky** [influitive/apartment#149]
I see in the docs that it says "rake db:migrate" runs "Apartment::Database.migrate(#{tenant}) for each tenant. But in the Rails console, when I run:

Apartment::Database.migrate(mydb)

I get the following error:

NoMethodError: undefined method `migrate' for Apartment::Database:Module

I looked at the source, and I see a "migrate" method in the Migrator module, but I'm not sure how to invoke it. Calling:

Apartment::Migrator.migrate(mydb)

NameError: uninitialized constant Apartment::Migrator

**Comment by betacanis** [comment]
thanks Brad.. u made my day with 
```javascript
DB=my_tenant rake db:migrate
```

**Comment by andandio** [comment]
> that file before you use it. It's required by the rake task so when you run `rake db:migrate` it runs the apartment migrator.

This doesn't seem to work anymore, nor does `TENANT=my_tenant`. Is there another way to accomplish a migration for a single tenant?
