### ISSUE TITLE
views not 'copied' into the schema's

### ISSUE THREAD

**Issue by koenhandekyn** [influitive/apartment#159]
i couldn't use the tool because 'view' definitions didn't get copied into the 'tenant' schemas. i know it's probably not a very common thing to use pg views with rails but it's actually very powerful in my use case.

any ideas about a fix ? for getting the views 'copied' into the tenant schemas?

**Comment by minhdanh** [comment]
Any updates on this? I'm having the same problem.

**Comment by bradrobertson** [comment]
This really isn't anything to do with Apartment, other than the fact that we use the `schema.rb` for creating tenants. You'd have the exact same problem setting up a new environment by loading `schema.rb`. Check out [schema_plus_views](https://github.com/SchemaPlus/schema_plus_views) which may help you get the view definition into the schema file.

Also another interesting project: [scenic](https://github.com/thoughtbot/scenic) though I have no idea if it's compatible with Apartment.

**Comment by minhdanh** [comment]
Thank you for your suggestion, Brad. I guess you can close this issue now. :dancer:

**Comment by minhdanh** [comment]
By the way, Brad, how about using `structure.sql` instead of `schema.rb`? Does apartment work well with SQL schema format?   (config.active_record.schema_format = :sql)

**Comment by bradrobertson** [comment]
I remember people having issues with it previously, but I don't recall off the top of my head why that is. Sorry I don't have a better answer. Let me know if it works for you and we can update the docs!
