### ISSUE TITLE
Can i use SubDomains and Domains in the same app?

### ISSUE THREAD

**Issue by raulperezalejo** [influitive/apartment#193]
This is more a question than and issue. 

gem 'rails', '4.1.6'
...
gem 'apartment', :github => 'influitive/apartment'

In the description of the gem is spoken about the use or Domains and SubDomains or eaven Custom Elevators, but no reference if i could use a combination of these. 
i have made some test and no app or gem error, but not the result expected, maybe is just a matter of routes.rb configuration that i could achive with routes Constraints. 
any advise, experience or help will be welcome.

regards

**Comment by bradrobertson** [comment]
Switching tenants is kind of left up to you if you have anything beyond a simple domain or subdomain matching switch. 

I've added more docs to the [elevator section](https://github.com/influitive/apartment#switching-tenants-per-request) under custom elevator. You can implement your own strategy

**Comment by alik78** [comment]
Scroll down to **Custom Elevator Class** in this article. It covers this question here pretty well. Don't forget to require your custom Elevator class in **apartment.rb**
https://medium.freecodecamp.org/building-a-multi-tenant-app-is-easy-if-you-have-an-apartment-3465f6eda85b
