### ISSUE TITLE
Dashes in schema names with PostgresqlSchemaAdapter

### ISSUE THREAD

**Issue by jonsgreen** [influitive/apartment#198]
I just discovered that the pg_dump fails for new schemas with dashes when calling Apartment::Tenant.create with use_sql because the schema name is not being wrapped in double quotes. I will be submitting a simple fix with spec as a pull request shortly.

**Comment by jonsgreen** [comment]
Thank you for merging the pull request. Just curious if you have a sense of when this might be released into a future gem version?

**Comment by bradrobertson** [comment]
I'll do a patch release for this. We'll have a 1.0 out shortly with the new interface.
