### ISSUE TITLE
Question about Apartment

### ISSUE THREAD

**Issue by ndenkowycz** [influitive/apartment#200]
I am trying to get the current tenant value in a migration's up method, is it even possible?
Thanks in advance.

**Comment by ndenkowycz** [comment]
Just figured it out. I can just do #{ActiveRecord::Base.connection.current_schema.to_s}

**Comment by bradrobertson** [comment]
`Apartment::Tenant.current` would be preferred

**Comment by ndenkowycz** [comment]
Thank you very much
