### ISSUE TITLE
Generic Elevator - tenant won't switch

### ISSUE THREAD

**Issue by ivanstojkovicapps** [influitive/apartment#201]
i am trying to use apartment with GenericElevator. I have a line "for test purposes" that should switch the schema. The schema exists in database. SQL generated for MyActiveRecord.first is showing select for "no schema", and it lands in public schema.

class MyElevator < Apartment::Elevators::Generic

    def parse_tenant_name(request)

    token = request.env["TOKEN"];
    Apartment::Tenant.switch("public")
    user = User.find_by(authentication_token: token)
    if !user.nil?
      tenant_name = user[:database_name]
    else
      raise ActiveRecord::RecordNotFound
    end

    # for test purposes
    Apartment::Tenant.switch("existing_schema")
    MyActiveRecord.first

    return tenant_name
  end
end

In apartment.rb i have the following

config.excluded_models = %w{User}
config.use_schemas = true
Rails.application.config.middleware.use 'MyElevator'

The elevator gets called, but switch doesn't work. Do you have some clues for me?

**Comment by ivanstojkovicapps** [comment]
Issue is resolved, SQL logging is not showing the schema name if its not a public schema.

regards

**Comment by bradrobertson** [comment]
Just some advice, your elevator shouldn't have to do any switches. You've got `User` as an excluded model, so when you do a select it will automatically fetch it from the public schema. The purpose of the elevator is to provide the tenant name to switch to, but the inherited Generic elevator will actually do that switching. You just provide the tenant name.

**Comment by ivanstojkovicapps** [comment]
i figured that out after my post. Thanks for help!
