### ISSUE TITLE
ActiveRecord::Migrator.proper_table_name is deprecated and removed in Rails 4.2

### ISSUE THREAD

**Issue by ldonnet** [influitive/apartment#202]
Hi,

I use apartment for a long time and I upgrade to rails 4.1. I have a deprecation warning for Rails 4.2 and I prefer alert you about this : 
DEPRECATION WARNING: ActiveRecord::Migrator.proper_table_name is deprecated and will be removed in Rails 4.2. Use the proper_table_name instance method on ActiveRecord::Migration instead. (called from measure at /home/luc/.rbenv/versions/2.1.3/lib/ruby/2.1.0/benchmark.rb:279)
An other solution has to be found for Rails 4.2.

Best Regards 
Luc Donnet

**Comment by bradrobertson** [comment]
Thanks Luc, care to submit a pull request?

**Comment by ldonnet** [comment]
I will try. I hope I could have some time soon.

**Comment by albertyw** [comment]
Looking through the code and running Apartment on rails 4.2, I don't see any usage of `proper_table_name` or a `benchmark.rb` file.  Are you sure that deprecation warning is from Apartment?

**Comment by ldonnet** [comment]
You are right. I debug my project and it seems that apartment is not the guilty. I close this issue and will reopen it if I find the method call in apartment.
