### ISSUE TITLE
Getting sorcery logged in user in apartment custom elevator (rack middleware)

### ISSUE THREAD

**Issue by klnrajareddy** [influitive/apartment#205]
Hi,

I am using sorcery for authentication and implementing multi-tenancy using apartment. I need current logged in user from sorcery to figure out the tenant, for which I am putting up a custom elevator (rack middleware).

Can someone please let me know how do I access sorcery current user in the custom elevator? 

I also raised a question with sorcery: https://github.com/NoamB/sorcery/issues/665.

Regards,
Raja

**Comment by bradrobertson** [comment]
This isn't an Apartment question.
