### ISSUE TITLE
models are not aware of their tenant owner

### ISSUE THREAD

**Issue by bluej100** [influitive/apartment#211]
It would be helpful if ActiveRecord models stored the Apartment::Tenant.current at the time they were fetched. ActiveRecord assumes that models are uniquely identified by id, which is dangerously shaky with multiple schemas. An example of the problems:

```
Apartment::Tenant.use("first")
u = User.find(1)
Apartment::Tenant.use("second")
u2 = User.find(1)
u == u2 # true
u.name == u2.name # false
u.reload
u.name == u2.name # true
```

**Comment by bradrobertson** [comment]
This would involve monkey patching of ActiveRecord which I'm loath to do. It might be a bit of an issue comparing across tenants, but I think as long as you're aware of the situation, things should be fine. We've never run into an issue in the 4 years of using Apartment.

**Comment by bluej100** [comment]
I can understand that position. Thanks for the response.
