### ISSUE TITLE
Apartment does not work behind HAProxy

### ISSUE THREAD

**Issue by zakirpk** [influitive/apartment#212]
Apartment does not work behind HAProxy (Highly Available Proxy). I am facing a lot of  Apartment::DatabaseNotFound  errors. HAProxy is mostly used for scaling the application vertically. I will be very thankful to you if you make this gem workable behind HA Proxy. 

Below are some error messages.

------------------------------------  Error Messages --------------------------------------

Apartment::DatabaseNotFound (Cannot find tenant node1):
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:65:in `rescue in connect_to_new'
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:59:in `connect_to_new'
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/abstract_adapter.rb:100:in `switch'
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/elevators/generic.rb:20:in `call'

============================================================================

Apartment::DatabaseNotFound (Cannot find tenant node2):
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:65:in `rescue in connect_to_new'
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:59:in `connect_to_new'
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/abstract_adapter.rb:100:in `switch'
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/elevators/generic.rb:20:in `call'

**Comment by bradrobertson** [comment]
We use HaProxy on all of our apps, it certainly does work. There's numerous ways you can switch to the correct tenant. Most commonly, this comes from the subdomain, which at the end of the day is just parsed out of the http host that comes in. HaProxy certainly does NOT strip this out of the headers so it really must just be something to do with your middleware.

It looks like you're using the generic middleware there. If you are, you're implementing your own solution, which means there's something wrong with your code.

Check out [the section on switching tenants](/github.com/influitive/apartment#switching-tenants-per-request) to see your options. The subdomain elevator is most common.

**Comment by zakirpk** [comment]
First of all I would like to thank you for your wonderful apartment gem. I used the apartment gem with subdomain elevator, without HAProxy my app is working perfectly. I hosted my application on OpenShift. My application configuration is given below:

************************************  initializers/apartment.rb  content ****************************
require 'apartment/elevators/subdomain'
Apartment.configure do |config|
  config.excluded_models = ["StaticPage", "Tenant"]
end
Apartment::Elevators::Subdomain.excluded_subdomains = ['www', 'public']
Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain'

*******************************  haproxy contents    *********************************

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    #option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 128

listen stats 127.2.161.101:8080
    mode http
    stats enable
    stats uri /

listen express 127.2.161.100:8080

    cookie GEAR insert indirect nocache
    option httpchk GET /
    http-check expect rstatus 2..|3..|401

    balance leastconn
    server local-gear 127.2.161.111:8080 check fall 2 rise 3 inter 2000 cookie local-758437gfgfgdfggdf

*********************************   Log file contents ****************************************

I, [2015-01-31T15:13:29.928497 #305602]  INFO -- : [ex-std-node11.prod] Started GET "/" for 127.2.161.111at 2015-01-31 15:13:29 -0500
E, [2015-01-31T15:13:29.993063 #305602] ERROR -- : [ex-std-node11.prod] Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-std-node11' at line 1: use ex-std-node11
F, [2015-01-31T15:13:29.996375 #305602] FATAL -- : [ex-std-node11.prod] 
Apartment::DatabaseNotFound (Cannot find tenant ex-std-node11):
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:65:in `rescue in connect_to_new'
  vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:59:in `connect_to_new'
