### ISSUE TITLE
How do you automatically delete PSQL Schema when Tenant is Deleted?

### ISSUE THREAD

**Issue by guitarjoe02** [influitive/apartment#216]
I'm not finding any info in the Readme or on the issues regarding how to delete the corresponding Postgres schema when a Tenant is deleted.

I've tried a few things and I would expect something like ```Apartment::Tenant.destroy('tenant_name')``` is/could be setup to add to the controller's ```destroy``` action.

Currently, when a ```tenant``` is deleted/destroyed, the Postgres Schema is not deleted.

Can someone please assist?

**Comment by bradrobertson** [comment]
Obviously not documented very well, but [Apartment::Tenant#drop](https://github.com/influitive/apartment/blob/development/lib/apartment/adapters/postgresql_adapter.rb#L46) will do it.

Note there's nothing 'automatic' about this, you have to call it yourself. There's no direct connection between the model you use to represent a tenant, and the underlying postgresql schema other than the name.

**Comment by guitarjoe02** [comment]
Thanks for the quick response!
Trying to understand the implementation... Would this need to be added as a route?

**Comment by bradrobertson** [comment]
Depends what you're trying to achieve really. More typically this would be done through an `after_destroy` hook on your tenant model, or something to that affect (like a service class etc)

An example rails model might look something like:

```ruby
class Tenant < ActiveRecord::Base
  after_create :create_tenant
  after_destroy :remove_tenant

  def create_tenant
    Apartment::Tenant.create(name)
  end

  def remove_tenant
    Apartment::Tenant.drop(name)
  end
end
```

Also note I'm not advocating for this pattern (I personally don't like the ActiveRecord callback approach) it should serve as an example of what you can do. More typically I'd recommend a `TenantRepository` type class that is responsible for creating/removing tenants not directly coupled to your model.

At this point it's not really an Apartment question though and really just how you model your Rails (or equivalent Rack) app

**Comment by guitarjoe02** [comment]
That gets me what I need. Thanks!
