### ISSUE TITLE
Drop public schema tables

### ISSUE THREAD

**Issue by ronanrodrigo** [influitive/apartment#219]
After i created a new schema, all of my tables will be destroyed. I am doing this:
```ruby
@organization = FactoryGirl.build(:organization)
@organization.create_schema if @organization.save
```
```ruby
class Organization < ActiveRecord::Base
  def create_schema
    Apartment::Tenant.create("organization_#{self.id}")
  end
end
```

After the ```@organization.create_schema``` all public tables was droped. My apartment config block:
```ruby
Apartment.configure do |config|
  config.excluded_models = %w{ Organization Category User }
  config.use_schemas = true
  config.persistent_schemas = %w{ public }
end
```

Note: My database before these blocks was clean.

**Comment by bradrobertson** [comment]
you can't have public as a persistent schema (at the moment). I'd like to fix this, but for the moment I *believe* that's your issue.

**Comment by ronanrodrigo** [comment]
@bradrobertson i changed this configuration but the issue persist... Yesterday it was working nicely, but today when i restart my DB to start from beginning this happened :(

**Comment by ronanrodrigo** [comment]
Forget what i am mentioned, yesterday works because i insertions with other way

**Comment by ronanrodrigo** [comment]
Downgrade my gem version and now its works fine! Apartment 0.25.2 (was 0.26.1) @fabiomello
