### ISSUE TITLE
Coverage report (rspec, simplecov-rcov) and excluded_models

### ISSUE THREAD

**Issue by fabiomello** [influitive/apartment#220]
My excluded_models doesnt appear at coverage/ report generated by simplecov-rcov.
Have I to do any around?

**Comment by bradrobertson** [comment]
Not sure what you're asking. You want rcov to report the test coverage for setting `excluded_models` in your app?

Or you're running rcov on the Apartment repo??

**Comment by fabiomello** [comment]
First option, i want rcov to report the test coverage setting excluded_models in my app.
Example: I Have one model (Organization), and when i run the tests it doesnt be visible at coverage/rcov reports

**Comment by bradrobertson** [comment]
I've never used rcov but I don't really think this is an Apartment question.

**Comment by fabiomello** [comment]
If i remove from apartment initializer, my reports go good, and simplecov generate model report...

**Comment by bradrobertson** [comment]
Ok I think I get what you're saying. I've never run into this. Again I Don't use rcov/simplecov.

Apartment basically does a constantize on your excluded models. Maybe that's affecting things?

**Comment by fabiomello** [comment]
Maybe is this. I wil check and answer, thanks for the help!

**Comment by bradrobertson** [comment]
Any update? I'll close otherwise.

**Comment by helloinc** [comment]
I have same problem. 
I am still not sure why rcov/simplecov skips these models as a result of setting 'excluded_models', but I found that rcov/simplecov use core library class named Coverage of Ruby2.
http://ruby-doc.org/stdlib-2.1.0/libdoc/coverage/rdoc/Coverage.html
Does Apartment interfere core libraries? I think that Apartment just changes table_name.

RSpec3, Ruby2.2.3, Rails4.2.2, and PostgreSQL.

**Comment by helloinc** [comment]
Hmm, I understand why.
The coverage checks files after Coverage.start but, Apartment require excluded_models before start RSpec.

**Comment by Pralish** [comment]
@fabiomello Did you manage to make this work? I am facing the same issue.
