### ISSUE TITLE
ould not find apartment-0.26.1 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by mkosuri** [influitive/apartment#221]
Hi friends, 
I found the below error when i am running cron job in development mode 

/home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find apartment-0.26.1 in any of the sources (Bundler::GemNotFound)
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `map!'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/definition.rb:132:in `specs'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/definition.rb:177:in `specs_for'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/definition.rb:166:in `requested_specs'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/environment.rb:18:in `requested_specs'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:13:in `setup'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler.rb:122:in `setup'
	from /home/admins/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.7.12/lib/bundler/setup.rb:17:in `<top (required)>'
	from /home/admins/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/admins/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'

could please suggest me,
Thanks
Madhu

**Comment by bradrobertson** [comment]
Was your internet not working at the time? It's [certainly there](https://rubygems.org/gems/apartment/versions/0.26.1)

**Comment by mkosuri** [comment]
Yes working , its not working in my local machine only. its working fine in all others systems and server also . Thanks to respond

**Comment by bradrobertson** [comment]
Don't know what to tell you but it's not really an Apartment issue itself I don't think. Them gem most definitely exists on rubygems.org

**Comment by mkosuri** [comment]
Ok

**Comment by bradrobertson** [comment]
Going to close this, I don't think anyone else is finding this
