### ISSUE TITLE
Allow use of custom prepends for database names

### ISSUE THREAD

**Issue by Undo1** [influitive/apartment#225]
I'd like to be able to prepend a custom string to all my database names. Is there a config option to do this? If not, can we add one?

**Comment by bradrobertson** [comment]
Right now there's `prepend_environment` and `append_environment` options. Maybe we should just have some sort of tenant modifier option that is a block that gets yielded the tenant name and you can return a string that ultimately gets used? That way people could do their own prepend/append in whatever way they want.

Thoughts? If you're interested in submitting a PR I'd be happy to review it.

**Comment by fuzzygroup** [comment]
+1 for this.  I'd strongly recommend it from the perspective of being able to manage the tenant databases that are created.

**Comment by mikecmpbll** [comment]
@fuzzygroup can you advise me your use-case, with examples?

**Comment by Undo1** [comment]
When I was looking at this two years ago, my use case was two applications sharing the same database server. Namespacing is necessary in that case.

**Comment by fuzzygroup** [comment]
I'm looking at using RDS on AWS for a SAAS app with multiple users where the data is stored at the level of one database per user.  One way of namespacing is of course at the database level itself and that's an option but, particularly for development, knowing which project your data belongs to makes managing things a lot easier.

**Comment by mikecmpbll** [comment]
ah okay. i'm in favour of brad's tenant modifier idea. PRs welcome :).

**Comment by mikecmpbll** [comment]
addressed with `tenant_decorator` in my rails 5.1 only branch. am still testing things but will merge bits into main repo as and when.

https://github.com/influitive/apartment/issues/438#issuecomment-311894556
