### ISSUE TITLE
How can I run migrations for non-tenants?

### ISSUE THREAD

**Issue by HuckyDucky** [influitive/apartment#228]
I have my tenants set up correctly for PostgreSQL in a Rails 4.2 application, and migrations are going off without a hitch. I've been using this for about a year and a half now, and it's a big improvement over my hand-coded db switcher that I put in the ApplicationController. And in every single report class I ever created ;-)

I also see how to run migrations for a single database by supplying "DB=<schema_name>" to the regular migration task.

My problem is that we use EngineYard, and via Chef our migrations are run automatically. I don't think there is a way to provide environment variables to the migration stack there. I was wondering if there is some sort of code magic that I can put into the migrations themselves. Anything, really:

    class AddAddressToUsers < ActiveRecord::Migration
      def up
        if <the users table exists>
          add_column :users, :address, :string
        end
      end
    end

**Comment by bradrobertson** [comment]
It's a good question. We've actually always just put code in the migration itself, something like
```ruby
if Apartment::Tenant.current == 'public'
```
It's not the *greatest* solution but it's worked for us.

**Comment by HuckyDucky** [comment]
Oh, that's perfect. So I should make sure to put "public" as one of my tenants then, right? And conversely, I would need to put:

    unless Apartment::Tenant.current=='public'

around all the migrations that were destined for the regular tenants, right?

**Comment by bradrobertson** [comment]
As it stands, public is automatically migrated with all the tenants, so you don't need to worry about it. Since all tables live in all schemas (including public) there's no need to really filter it out for any reason. The migrations will run against it but the tenanted tables in that schema will just be ignored.

So no you shouldn't really need to change anything, just do the check for public in your non-tenanted migrations

**Comment by HuckyDucky** [comment]
I see, maybe included from the default schema_search_path, thanks a lot Brad.
