### ISSUE TITLE
Trying to understand how to go with custom schema.rb file.

### ISSUE THREAD

**Issue by HuckyDucky** [influitive/apartment#229]
I'm working on a multi-tenant Rails 4.2 application against PostgreSQL. There is a group of models that are used for application administration, and then each tenant will have its own Product-related tables.

I've been going through the code and examples I have found on the internet. After quite a bit of experimentation, I have the following:

* My centralized tables (users, companies, etc.) in the 'public' schema. I have excluded these models in my Apartment initializer.
* I have a seeds.rb file that seeds the public tables, and creates one tenant to develop against.
* In the initializer I have overridden the database schema file name:

    ```
    module Apartment
      class << self
        def database_schema_file
            @database_schema_file=Rails.root.join('db', 'catalog_schema.rb')
        end
      end
    end
    ```
* I have created two models for a tenant: ProductBase and Product.
* I have wrapped each migration in a conditional.

   If it belongs to public:
```if Apartment::Tenant.current == 'public'```

  and if it belongs in a tenant:
```unless Apartment::Tenant.current == 'public'```

* My custom "catalog_schema.rb" file is empty. How do I dump the tenant models to that file? I tried:

```rake db:schema:dump```

but that only rewrote my schema.rb. And it only wrote my excluded models, but that makes sense because it's just dumping the structure that it gets from the public schema.

* I **want** to dump my tenant schema to my custom **catalog_schema.rb** file, but I just don't know how. I have looked, but found nothing. I have figured out this command:

```rake db:schema:dump SCHEMA=db/catalog_schema.rb```

but it is still just dumping the public schema. I need for it to dump my tenant schema.

I'm about 3 days into this. I will put together a nice wiki page for this whole process if someone can offer me some clues on how to get my tenant schema dumped to my custom schema file. It won't help any of you, but at least we'll be paying it forward!

**Comment by bradrobertson** [comment]
Sorry for the late response, I have no idea how you'd do this. That's specific to ActiveRecord really, not apartment.

**Comment by HuckyDucky** [comment]
No problem Brad. Is the accepted practice then to keep the tenant schema up by hand?

**Comment by bradrobertson** [comment]
We actually just have the one `schema.rb` file which represents all tables, whether excluded or not. It'd be awesome to have separate schema.rb files...  for tenanted/excluded models, but I've never really explored that option.

**Comment by HuckyDucky** [comment]
OK, I'm going to look into that. I'll contribute back anything of value that I find.

**Comment by mwalsher** [comment]
@HuckyDucky did you find a solution for maintaining separate public/tenant schemas?
