### ISSUE TITLE
Different schema for public and tenant database?

### ISSUE THREAD

**Issue by irfanfadilah** [influitive/apartment#230]
I know by default Apartment will create same tables on both public and tenant database. And most of tables on public database are no use, empty tables. I also know that tenant database are depending on schema.rb

But I wonder if we can have different schema for public and tenant database? For example I have 4 tables: merchant, products, comments and users.

If I want the main database (public) only have merchants table, and tenants only have products, comments and users tables, is it possible?

Thanks before.

**Comment by bradrobertson** [comment]
This directly mirrors [this issue](https://github.com/influitive/apartment/issues/229) I think it's a good idea, but I don't know exactly how to manage that with ActiveRecord

**Comment by Billable** [comment]
I want to do the same thing as @irfanfadilah said. Have you find any solution?

**Comment by irfanfadilah** [comment]
@Billable, I haven't found any solution, so I still use same schema for public and tenant..
