### ISSUE TITLE
Using alternative seed file

### ISSUE THREAD

**Issue by typeoneerror** [influitive/apartment#231]
I've got apartment installed in a rails engine and I'd like to use a seed file in my engine instead of the one at Rails.root/db. What's the best way to do this since it's [hard-coded in the seed method](https://github.com/influitive/apartment/blob/870988bb8ec542a33a95d0061b1b90f3bb3985d7/lib/apartment/adapters/abstract_adapter.rb#L141)?

Should I monkey patch this method or is there a better way?

Here's what I'm thinking:

    Apartment::Tenant.create(subdomain) do
      seed_data if Apartment.seed_after_create
    end

    def seed_data
      silence_stream(STDOUT){ DokiCore::Engine.load_seed }
    end

**Comment by bradrobertson** [comment]
You're welcome to submit a pull-request to make that configurable. It'd be pretty simple. I've just never had anyone ask for it, but it makes sense. See the other config options such as [default_schema](https://github.com/influitive/apartment/blob/870988bb8ec542a33a95d0061b1b90f3bb3985d7/lib/apartment.rb#L15) where we allow the option to be written but [give a fallback reader method](https://github.com/influitive/apartment/blob/870988bb8ec542a33a95d0061b1b90f3bb3985d7/lib/apartment.rb#L45) if it isn't.

**Comment by typeoneerror** [comment]
@bradrobertson yeah, I'll do that. thanks for the point in the right direction.

**Comment by typeoneerror** [comment]
PR [here](https://github.com/influitive/apartment/pull/234/files)
