### ISSUE TITLE
rake db:rollback rolls back TWICE for some reason

### ISSUE THREAD

**Issue by eliduke** [influitive/apartment#233]
I've been experiencing this problem now for a couple months and just dealing with it, but I've decided to **finally** take some action. The problem is that I don't know near enough about how apartment works, so I figure I'd just throw this in the mix.

The title really says it all. I create a migration and then `rake db:migrate` runs just fine. If I run `rake db:rollback` it rolls back that migration, prints `Rolling back #{db_name} tenant` to the screen, and then rolls back the next migration. I can't for the life of me understand why it would do that.

```
project_name [develop]$ rake db:rollback
== 20150507215555 AddIsLeaderboardSponsorToSponsors: reverting ================
-- remove_column(:sponsors, :is_leaderboard_sponsor, :boolean)
   -> 0.5300s
== 20150507215555 AddIsLeaderboardSponsorToSponsors: reverted (0.5302s) =======

Rolling back db_name tenant

== 20150507144309 RemoveUnnecessaryFieldsFromUser: reverting ==================
-- add_column(:users, :remember_created_at, :datetime)
   -> 2.8080s
-- add_column(:users, :current_sign_in_ip, :string)
   -> 1.1334s
-- add_column(:users, :current_sign_in_at, :datetime)
   -> 0.8994s
-- add_column(:users, :sign_in_count, :integer)
   -> 0.9577s
== 20150507144309 RemoveUnnecessaryFieldsFromUser: reverted (5.7990s) =========
```

From there I can run `rake db:migrate` again and it then migrates both migrations again just fine. So, as you can see it's not a show stopper, but it's been bugging me... no pun intended. ;)

**Comment by bradrobertson** [comment]
Hmm... we don't see this on our app. The only issues we've seen is that if 1 tenant is migrated and another isn't (for whatever reason) you'll see different migrations applied during migration/rollback.

So if for some reason your public schema wasn't migrated properly and you did a rollback, you'd see 2 different migrations being rolled back. 1 for the current migration that public has, and 1 for the tenant.

Can you verify that when you run `rake db:migrate` that all postgres schemas have all the latest migrations run on them? (including the `public` schema).

**Comment by eliduke** [comment]
We are using MySQL, does that matter? Also, we only have one tenant.

**Comment by eliduke** [comment]
Any thoughts?

**Comment by bradrobertson** [comment]
sorry, kind of stumped on this one.

**Comment by eliduke** [comment]
Hmmm... What about just this part of the output?

`Rolling back {db_name} tenant`

Where does that happen in the flow of things? I'm looking around in my initializer and I'm not seeing anything...

**Comment by eliduke** [comment]
Here's my thoughts...

I was once having problems with the chewy gem and some of it's rake tasks because I had created my own rake tasks on top of the already existing chewy rake tasks. So, when I ran the task it was running the built-in chewy rake task and then it would run my own custom rake task. I did a search through the Apartment code base and found this:

```
# https://github.com/influitive/apartment/blob/4023342570817cb66fb23bf61b6e2a47f3e52d5a/lib/tasks/apartment.rake#L47

desc "Rolls the migration back to the previous version (specify steps w/ STEP=n) across all tenants."
task :rollback do
  warn_if_tenants_empty

  step = ENV['STEP'] ? ENV['STEP'].to_i : 1

  tenants.each do |tenant|
    begin
      puts("Rolling back #{tenant} tenant")
      Apartment::Migrator.rollback tenant, step
    rescue Apartment::TenantNotFound => e
      puts e.message
    end
  end
end
```

That `puts` in there is what is drawing my attention because when I run `rake db:rollback` locally, the rollback happens as expected, rolling back the most recent migration. But then it says `Rolling back {db_name} tenant" and then rolls back another step. That is inline with your custom rake task. It `puts` that message and then rolls back. So, somehow your custom apartment rake tasks are getting wrapped up with `rake db:migrate` and being run on top of the built-in default rails rollback.

If I try to run the existing apartment rake tasks I get the notification that they have been deprecated and that tenants will automatically be migrated with `db:migrate`. That seems to favor my theory about what is happening here.

**Comment by bradrobertson** [comment]
ya we basically override `rake db:migrate` to run tenant migrations also. You can disable this feature.

I'm not sure about the duplicate migrations though as we don't personally see this. Again we don't use Mysql though so maybe it's something to do with that?

**Comment by eliduke** [comment]
Hmmm. Ok. How do I disable the override of rake db:migrate? I just want to keep testing things.

**Comment by bradrobertson** [comment]
see [Managing Migrations](https://github.com/influitive/apartment#managing-migrations)

Note the config option `db_migrate_tenants` and you can see in the [railtie](https://github.com/influitive/apartment/blob/development/lib/apartment/railtie.rb#L39) what this does. It basically requires [this enhancements file](https://github.com/influitive/apartment/blob/development/lib/apartment/tasks/enhancements.rb)

**Comment by eliduke** [comment]
I turned off `db_migrate_tetants` and that did fix the problem temporarily, but it didn't really fix the problem because eventually I will need `rake db:migrate` to migrate all the tenants correctly. I still need to figure out what's happening here because I'm having new problems, this time with seeding. I run all the seeds and immediately after all the seeds have successfully run, the console outputs `Seeding #{db} tenant`, the seeds try to run again and then there are duplicate entry errors.

There's still something pretty fishy going on here.

I was looking at the list of available rake tasks, and I noticed some Apartment specific rake tasks, but when I try to run `rake apartment:rollback` I get this warning:

```
[WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

1. You may not have created any, in which case you can ignore this message
2. You've run `apartment:migrate` directly without loading the Rails environment
* `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.
```

The funny thing is that it says my "list of tenants to migrate appears to be empty," but that is definitely NOT true because when I run `Apartment.tenant_names` it returns a single element array with the name of my db: `["db_name"]`. I understand that those rake tasks have been deprecated, but regardless it should still know that there is at least one tenant in my list.

But I keep coming back to this idea that when I run any db specific rake tasks, it seems to be running them straight away and THEN trying to run them against the tenants. Is that normal behavior? Shouldn't it ONLY be running them against the tenants. What is it doing the first time around? When you run rake db tasks on your end, does the output BEGIN with a message from apartment saying "Rolling back #{db_name} tenant" or does it happen in the middle?

**Comment by bradrobertson** [comment]
It's normal to run migrations in public *then* all the tenants yes. That's the intended behaviour. You need to do both as the `schema.rb` is generated from the public tenant itself and is needs to represent all the tables for new tenants to be created.

I'd love to split out migrations so public only gets public model migrations and tenanted ones just get tenanted migrations, but it's extremely complicated to do this and not really worth the dev effort IMO.

The warning you're seeing is because `Apartment.tenant_names` is returning an empty array. You can see that code [here](https://github.com/influitive/apartment/blob/development/lib/tasks/apartment.rake#L114). If it's empty, my guess is it's because you're running the rake task directly, which does NOT load the rails environment which has your initializer that ultimately populates that array. This is why we've deprecated these migrations. Basically, instead, we just 'enhance' `db:migrate` to run itself and *then* run against all tenants.

**Comment by eliduke** [comment]
After more experience in this realm of postgres and schemas and tenants, I realize now that the problem was that we were using MySQL. Once we switched over to postgres and got our schemas all sorted, everything is working just fine.

I think we had multi-tenancy sort of half-baked at that point, poised for a move over to postgres, and that middle-ground scenario was causing problems.

**Comment by bradrobertson** [comment]
Hmm... ok. Doesn't make me super confident on the mysql implementation side of things, but I'm glad you sorted your issue. Will keep my ears open for anyone else with these issues on Mysql.

**Comment by eliduke** [comment]
It's very possible that we just didn't have it completely configured yet because we were actually doing any multi-tenancy stuff, we just had some of the pieces in place.
