### ISSUE TITLE
Migrating data from the public schema.

### ISSUE THREAD

**Issue by vjustov** [influitive/apartment#236]
Hello,

This is not an issue with apartment.

We were using the 'public' schema before switching into the multi-tenancy model. Now all the data for one tenant resides in 'public'. 

What is the best way to "move" that data to its corresponding schema?
I was trying to rename the public schema into a 'tenant' schema but the migration errors out.

Thanks in advance.

**Comment by bradrobertson** [comment]
You can just create a new tenant and, for each table run a
```sql
INSERT INTO tenant.table_name SELECT * from public.table_name
```
for each table.

And you're right, this is not an apartment issue.

**Comment by vjustov** [comment]
Thank you @bradrobertson for your guidance. That certainly pointed me in the right direction.
If anyone ever needs something like this. This is the whole migration i used for creating and migrating all the data from the public into the tenant schema:

```ruby
class CreateSchemaForTenants < ActiveRecord::Migration
  def change
    add_column :tenants, :schema_name, :string

      Tenant.all.map { |tenant|
        tenant.schema_name = tenant.name.parameterize.gsub('-', '_')
        tenant.save
        Apartment::Tenant.create(tenant.schema_name)
      }
      
      # Because not all tables need to be migrated into the tenant schema.
      # We get all the tables in public, and black list the ones we want to 
      # leave in the public schema.
      all_tables = ActiveRecord::Base.connection.tables
      blacklisted_tables = ['tenants', 'users', 'roles', 'schema_migrations', 'clients']
      whitelisted_tables = all_tables - blacklisted_tables

      #insert all data into the tenant schema
      whitelisted_tables.each do |table_name|
        execute("INSERT INTO tenant.#{table_name} SELECT * from public.#{table_name}")
        execute("DELETE FROM public.#{table_name}")
      end

      # The clients table was erroring out because of a casting from varchar to integer problem.
      # so we are using this more explicit query for that.
      query = "INSERT INTO tenant.clients(all, fields, from, this," \
        "table) SELECT all, fields, from, this, table FROM tenant.clients;"

      execute(query)

      execute("DELETE FROM public.clients")
  end
end
```

**Comment by jhirn** [comment]
Hey guys!

We're doing a similar process of introducing multi-tennancy into an existing application. Is there any reason why you've chosen here to create a new schema and then run a copy of data from public to the new rather than just running `alter table set schema ...`? Doing alter schema drags along sequences, indices and objects owned by that table as well cleans up the public schema. 

Just curious if there are any pitfalls to my approach as opposed to copying via `INSERT INTO ... SELECT ...`
