### ISSUE TITLE
Do we have some best practices on joining data from different tenants?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [influitive/apartment#245]
I'm using postgresql schema setup. I have a couple of features where it would be handy to load out and mix data from different tenants (schemas). Any suggestions on the best way to do this? The solutions is NOT to put it in excluded models, since they for 99% of my functionality need them to be separated. For a bit more backgrund info the way I use apartment is for separating a web service by country because the products in each country are very different. However in the feature I want to build I would like to show them along side.

**Comment by zia954** [comment]
NielsKSchjoedt did you get your answer or did you accomplish this? i have the same problem

**Comment by mikecmpbll** [comment]
this is far from straight forward, unfortunately.

you could fire off separate queries to each schema (in parallel too if you wanted) and then collate the results. alternatively you could create a VIEW which unions the tables from the different schemas and query that.

I need to do something similar to this soon and these are the only techniques that I can think of so I'd be interested if anyone has any experience with this too!

**Comment by bradrobertson** [comment]
Oh sorry, don't know how I missed this. Ya the way we approach the situation is to think about the use case as a "service". It doesn't necessarily need to be an external service, it's just the term we use. We then call that out as needing aggregate queries and either manually aggregate (eg in an excluded model) or create a view as @mikecmpbll suggests.

Unfortunately there's no simple way to query across tenants other than unions, so a view (or materialized view) is probably your best bet.

**Comment by bradrobertson** [comment]
To give more context, things like Reporting for example are considered (by us) to be wholly separate. And of course we need reporting across tenants, but we don't consider this to be the job of Apartment. In that particular case we've literally written a new reporting service and we aggregate all records using [MultipleMan](https://github.com/influitive/multiple_man) into a denormalized service/db

**Comment by zia954** [comment]
so i guess excluding that model is the best option then?

**Comment by bradrobertson** [comment]
If you're using a model as an aggregate of multiple tenants in the same app, then ya you'll want it to be excluded.

**Comment by zia954** [comment]
no its not an aggregate of multiple tenants. I want to show the records of a table to admin from every tenant at one place. and this table's data is tenant's specific

**Comment by bradrobertson** [comment]
I'm not sure I understand. You said you want to show records from *every* tenant in one place, but that the tables' data is *tenant specific*. Isn't that contradictory? Either the data is an aggregate of all tenants, or it's relevant to a single tenant. Not both.
