### ISSUE TITLE
Foreign key constraint violation

### ISSUE THREAD

**Issue by hugomarisco** [influitive/apartment#248]
Hello there,

I'm trying to accomplish the following scenario:
### Models
- `User`
  - `id`
  - `email`
- `Game`
  - `id`
  - `name`
- `GameItem`
  - `id`
  - `user_id`
  - `game_id`

Tenants are provided by `Game` model using **name** column

I've subdomains for each `Game`.

Both `User` and `Game` are excluded from apartment models.

When I try to add a `GameItem` rails complains about user_id foreign key.
Perfactly understandable, since `User` information is in the "public" tenant, and we are working under a `Game` tenant.

My question is, how to deal with this kind of situation?

Best regards and thank you for any help

**Comment by bradrobertson** [comment]
There's currently no support for foreign keys across tenants. The 'solution' (unfortunately) is to just remove those foreign key constraints. Everything else will work as expected.

**Comment by firedev** [comment]
Sigh it causes so much pain. What can I do now? Just drop the keys manually? No migration are passing successfully. It's both: 
```
Table 'days' has no foreign key on column 'shop_id'
Mysql2::Error: Cannot drop index 'index_days_on_shop_id': needed in a foreign key constraint: ALTER TABLE `days` DROP `shop_id`
```
