### ISSUE TITLE
MySQL Schema Based

### ISSUE THREAD

**Issue by firedev** [influitive/apartment#249]
Hi, 

In [the poll](http://www.poll-maker.com/poll391552x4Bfb41a9-15) there is a question about MySQL Schema-based adapter.

However the documentation mentions schemas only in relation to Postgres. How to use MySQL schema?

**Comment by bradrobertson** [comment]
Ya I wasn't really sure how to term that one. It's really connection based vs non connection based. Mysql uses "databases" whereas postgresql uses "schemas" in the non-connection based adapters. I'll try to clarify that.

**Comment by bradrobertson** [comment]
ok I've updated the poll. Let me know if that's more clear
