### ISSUE TITLE
Apartment thinks a tenant has been migrated, but it hasn't.

### ISSUE THREAD

**Issue by HuckyDucky** [influitive/apartment#255]
Where does apartment keep track of the migration status of each tenant? I have a tenant that needs a migration run on it, but apartment refuses to do it. It's as if it thinks it has already been migrated.

**Comment by bradrobertson** [comment]
this is just straight up rails. Everything is stored in the `schema_migrations` table on each tenant

**Comment by HuckyDucky** [comment]
Thanks Brad. I found that that tenant was missing that. All systems normal.
