### ISSUE TITLE
Apartment::Tenant.create not deleting public schema multi tenant tables

### ISSUE THREAD

**Issue by CastroNuno** [influitive/apartment#256]
Hello,

as the tittle says, when I run Apartment::Tenant.create 'tenant_name' both, my public schema and the tenant schema, stay with all the tables. 

Shouldn't it drop the unnecessary tables on both schemas ?

rails (4.2.3) 
apartment (1.0.2)
pg (0.18.2)

apartment.rb

```ruby
Apartment.configure do |config|

  config.excluded_models = %w{ Admin Account }
  config.tenant_names = lambda { Account.pluck :name }
  config.use_schemas = true

end

Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain'
```

**Comment by bradrobertson** [comment]
This has been asking [numerous](https://github.com/influitive/apartment/issues/229) [times](https://github.com/influitive/apartment/issues/230). No, Apartment does NOT remove tables from public/tenants based on tenanting and excluded models. It doesn't do this as its very complicated and rails `schema.rb` is generated from one listing of tables, which reside in the public schema (by default) so we'd have to get around that somehow, which we don't.

The tenanted tables in public will be empty, as well the excluded tables in the tenants. It should not cause problems.

**Comment by mwalsher** [comment]
@bradrobertson did you find a solution for maintaining separate public/tenant schemas?
