### ISSUE TITLE
Uninitialized constant Apartment::Tenant on brand new Rails 4.2.4 app.

### ISSUE THREAD

**Issue by HuckyDucky** [influitive/apartment#260]
Just installed Rails 4.2.4 and created a brand new raw application. The ***only*** thing I've done is downgrade the ```mysql2``` gem to a previous verison.

I've been using this gem for a long time, never had this issue before.

The default version that installed is ```apartment-0.24.3```. Why not ~> 1.0.0? Is it because of the ```mysql2``` downgrade? Well, the latest mysql2 breaks Rails 4.2.4.

I also ran the generator and configured it for my pre-existing tenants.

At the console:

    Apartment::Tenant.switch("c19009")

Error:

    NameError: uninitialized constant Apartment::Tenant

Dead in the water. What can I do to *force* Rails to load this gem? It looks like I am in dependency hell. In other words, Rails 4.2.4 won't work with the latest mysql2, but Apartment will *only* work with the latest mysql2. 

Another thing I don't understand is if I do this in my Gemfile:

    gem 'apartment', '1.0.2'

and run:

   bundle install

I get:

    Could not find gem 'apartment (= 1.0.2) ruby' in the gems available on this machine.

Well, I don't want to install gems "available on this machine". I want to install them from the source. So I try to put the explicit tag line in my Gemfile:

    gem 'apartment', :git => 'https://github.com/brianmario/mysql2.git', :tag => '1.0.2'

And I get:

    myapp>  bundle update apartment
    Fetching https://github.com/influitive/apartment.git
    fatal: ambiguous argument '1.0.2': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
    Git error: command `git rev-parse 1.0.2` in directory
    /Users/me/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/cache/bundler/git/apartment-ab9b4e55afb06e135ef5b1134d2e75242eba0414 has failed.
    If this error persists you could try removing the cache directory
    '/Users/me/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/cache/bundler/git/apartment-ab9b4e55afb06e135ef5b1134d2e75242eba0414'

What a nightmare. Hopefully there is some way out of this. I can't understand why this isn't simple.

**Comment by HuckyDucky** [comment]
OK, so it's:

    Apartment::Database

in this version. I would still like to figure out why the new version isn't installing though.

**Comment by bradrobertson** [comment]
Wow lots of things going on here. First off, `Apartment` doesn't have any strict requirements (or any requirements for that matter) on `mysql2`. I *think* what you're seeing here is just bundler dependency management confusion.

ActiveRecord *also* doesn't have strict `mysql2` requirements since you can use different dbs under the hood. 

In the end none of these issues are `Apartment` issues because, as I said, we don't require mysql2 in any way.

I've found Bundler dependency management can often be a pain but from what I can see, there's no reason you shouldn't be able to use `Apartment ~> 1.0`

**Comment by HuckyDucky** [comment]
Thanks for your reply. I think you're right Brad. I'll dig further and open again if I see the issue.
