### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by apneadiving** [influitive/apartment#269]
In most places, errors are rescued and then a custom error is raised.

There the failure reason is sort of assumed based on the context but it could be wrong or not clear enough:

Example:

      rescue *rescuable_exceptions
        raise TenantNotFound, "The tenant #{tenant} cannot be found"
      end

There could be plenty of reasons there.

Could we pass the real error message instead of the custom one? eg:

      rescue *rescuable_exceptions => e
        raise TenantNotFound, e.message
      end

**Comment by bradrobertson** [comment]
Ya but I'd like to keep the context of *which* tenant couldn't be found if we can incorporate that into the message.

**Comment by apneadiving** [comment]
Ok, something like:

    "Error while creating tenant #{ tenant_name }: #{ e.message }"

**Comment by bradrobertson** [comment]
That depends if the error really **was** from creating or from switching to an unknown tenant. Those are two separate concepts. `TenantNotFound` is really that someone switched into an unknown tenant. Nothing to do with creation.

**Comment by apneadiving** [comment]
Yes sure :)

Was jut meaning something like `"Error while #{relevant action } on tenant #{ tenant_name }: #{ e.message }"`

**Comment by bradrobertson** [comment]
yup makes total sense!
