### ISSUE TITLE
Looks like a bug in pg adapter

### ISSUE THREAD

**Issue by apneadiving** [influitive/apartment#270]
I'd like to understand why we have almost same code in abstract and pg adapters, only difference is a call to `environmentify` which looks legit in abstract but is not present in pg's.
So I think I could remove the code in pg's and only rely on the abstract controller. Would be cool to have confirmation. Thanks

![The 2 files](https://www.evernote.com/shard/s244/sh/aa91d534-3428-4de6-a0f0-b29dd28abd3d/94c074107d459812/res/8c1a0b36-9a68-450b-a539-06fa3639895b/skitch.png?resizeSmall&width=832)

**Comment by bradrobertson** [comment]
Ya I *think* you're right. Looks like they're not doing anything different other than `environmentify`.

Note that the *concept* of environmentify should (has) changed to be more of a "translate this tenant name into some other tenant name" and environmentify was the original implementation of this (translate "tenant1" to "tenant1-development".

I'd *love* to abstract that out to just be a proc that someone can configure that receives the tenant name and returns the translated name that works for ALL adapters (not just connection based). I just don't have any time to actually do this unfortunately. There's [an open issue](https://github.com/influitive/apartment/issues/254) to this affect but I don't think anything has come from it

**Comment by apneadiving** [comment]
ok, so do you mind if I just remove the confusing override in pg's adapter?

**Comment by bradrobertson** [comment]
sure
