### ISSUE TITLE
Can't create an excluded model besides the main one

### ISSUE THREAD

**Issue by typeoneerror** [influitive/apartment#274]
I'd like to have a tenants table and settings table excluded:

    config.excluded_models = %w(DokiCore::Tenant DokiCore::Settings)

but when I migrate this, I cannot get it to work:

    ~/Dev/Doki/backend (payments) $ bundle exec rake db:migrate
    rake aborted!
    ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "doki_core_settings" does not exist
    LINE 5:                WHERE a.attrelid = '"doki_core_settings"'::re...
                                              ^
    :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                    FROM pg_attribute a LEFT JOIN pg_attrdef d
                      ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                   WHERE a.attrelid = '"doki_core_settings"'::regclass
                     AND a.attnum > 0 AND NOT a.attisdropped
                   ORDER BY a.attnum

If I remove Settings from the excluded models, it works fine but I'd like to have this model excluded. Am I misunderstanding how excluded models works or is there some way to get around this issue?

**Comment by bradrobertson** [comment]
That's odd you can definitely have multiple excluded models, we do that in our app so no, you're not misunderstanding anything. You probably have to create the table in a migration *before* it's marked as excluded though.

**Comment by typeoneerror** [comment]
@bradrobertson okay, so db:migrate, then add to excluded, then db:migrate again? sounds like it might be problematic in production, but I'll give that a shot.

**Comment by bradrobertson** [comment]
Ya I guess we've never run into this before. If you add the models first on production, then make them excluded you should be fine.

**Comment by typeoneerror** [comment]
Appears to be an issue with Rails inflections. I renamed my model to "configuration.rb/Configuration" with table name of "configurations" (instead of "settings.rb/Settings" with table name "settings") and now it works. I wasn't able to get "settings" to work with any combination of uncountable/irregular/singular/plural inflections.

**Comment by typeoneerror** [comment]
Actually, nope, after a team member did a fresh checkout and created database from scratch, we ran into the error again. I think this is an issue and should be reopened. Currently you'll have to comment our excluded models, migrate, and then uncomment the excluded_models line to create the database. I'm thinking this means every time you add a new model, you'll have to shut down production, push code to comment out excluded models, migrate, then push new code to uncomment again, then restart production? Is this what you experience?

**Comment by typeoneerror** [comment]
Okay, I *think* I've resolved this finally. Going to add this note here in case anyone experiences a similar issue. I was accessing the column_names in my model to create validations like so:

    COLORS = column_names.grep(/_color\z/).freeze
    validates(*COLORS, { color: true, allow_nil: true, allow_blank: true }) if COLORS.any?

I think this was causing the issue in the excluded model. Long story short, keep your excluded models simple.

**Comment by rafarubert** [comment]
Hi Guys,

I solve this bug usin the bellow code:


`
  after_create :create_schema

def create_schema
  Apartment.excluded_models.each do |model|
    ActiveRecord::Base.connection.exec_query("DROP TABLE #{self.subdomain}.#{model.tableize} CASCADE;");
end`
