### ISSUE TITLE
How do I set tenants can be browsed via   http://www.abc.com/:tenants/ ?

### ISSUE THREAD

**Issue by VansonLeung** [influitive/apartment#275]
How do I set tenants can be browsed via   http://www.abc.com/tenant/   instead of  http://tenant.abc.com/ ?  Does Apartment support this?

**Comment by srt32** [comment]
I believe your options are to 1) use the  `HostHash` elevator (https://github.com/influitive/apartment/blob/development/lib/apartment/elevators/host_hash.rb) or 2) implement a `Custom` elevator.

Reference: https://github.com/influitive/apartment#switching-tenants

**Comment by bradrobertson** [comment]
As @srt32 mentioned, you can switch in whatever way you want using a [custom elevator](https://github.com/influitive/apartment#switching-tenants)

**Comment by liveact** [comment]
@VansonLeung i'm looking at the same, how did you solve this?
