### ISSUE TITLE
Trying to switch on tld

### ISSUE THREAD

**Issue by enyachoke** [influitive/apartment#276]
The gem is trying to switch based on the tld and am using the subdomain elevetor
http://savannahacademia.co.ke/

 Apartment::TenantNotFound (One of the following schema(s) is invalid: "savannahacademia" "public"):
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/apartment-1.0.2/lib/apartment/adapters/postgresql_adapter.rb:92:in `rescue in connect_to_new'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/apartment-1.0.2/lib/apartment/adapters/postgresql_adapter.rb:85:in `connect_to_new'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/apartment-1.0.2/lib/apartment/adapters/abstract_adapter.rb:84:in `switch!'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/apartment-1.0.2/lib/apartment/elevators/generic.rb:21:in `call'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/pdfkit-0.6.2/lib/pdfkit/middleware.rb:17:in `call'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call'
18:08:07 web.1  |   vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call'

**Comment by mikecmpbll** [comment]
The default `tld_length` is 1, you should set this in your Apartment config initializer (config/initializers/apartment.rb):

```ruby
#
# Apartment Configuration
#
Apartment.configure do |config|
  # ...
  config.tld_length = 2
  # ...
end
```

**Comment by enyachoke** [comment]
Thanks closing I had to set
```ruby
#......
  class Application < Rails::Application
#......
config.action_dispatch.tld_length = 2
#......
end
#........
```
too.

**Comment by choznerol** [comment]
For people arrived this thread years later:

Apartment's own`tld_length` configuration option seemed to be deprecated since  https://github.com/influitive/apartment/pull/309 and will have no effect.

If both `http://savannahacademia.co.ke/` and `http://tenant-name.savannahacademia.co.ke/` are valid in your app, configure the default elevator like below to avoid `Apartment::TenantNotFound (One of the following schema(s) is invalid: "savannahacademia" "public")` in `http://savannahacademia.co.ke/`:

```ruby
# config/initializers/apartment.rb
...
elevator = Apartment::Elevators::Subdomain
elevator.excluded_subdomains = ['savannahacademia']
Rails.application.config.middleware.insert_before Warden::Manager, elevator
```
