### ISSUE TITLE
Best practice to sign up the same user for multiple tenants with a global User model

### ISSUE THREAD

**Issue by danema** [influitive/apartment#277]
By default a user gets created twice when they sign up for both tenant1 and tenant2.

My question is if there's a best practice to have the user model globally and when user1 wants to sign up for both tenants, user1 can access both tenants without having to register twice?

**Comment by bradrobertson** [comment]
What you're talking about is pretty specific to your domain so I can't comment a ton on that. Generally though, you'd have a tenanted model representing a person's membership to that tenant (eg `Member`) and a non-tenanted model representing their authentication within the system (eg `User`) and the `Member` model would have a foreign_key to the `User` model.

If you want a single signup to create memberships in all your tenants, this is something you'd need to manually do.
