### ISSUE TITLE
Best practices for backup and restore Tenant database on Heroku

### ISSUE THREAD

**Issue by bricesanchez** [influitive/apartment#279]
Hello all,

First, thanks for your awesome work on Apartment, that's a very useful gem !

I'm creating an app based on https://github.com/DefactoSoftware/Hours and i would like to know how you handle Database backup and restore for each Tenant on Heroku?

Basically, i'm using PostgreSQL heroku add-on + pg:backups, Autobus add-on for backup DB at long term.

Is it a correct config if i use Apartment gem ?

How could i restore the database for only one Tenant if there is a problem ?

Thanks for your answers!

**Comment by bradrobertson** [comment]
There's nothing specific about Apartment for this setup other than restoring a single tenant. Basically, there's no built in mechanism in Apartment for restoring a single tenant, but postgres itself (if you're using postgres) allows you to restore specific schemas using [pg_restore](http://www.postgresql.org/docs/current/static/app-pgrestore.html). Something like:
```bash
pg_restore --schema=the-tenant-name
```
With whatever other options apply

**Comment by bricesanchez** [comment]
@bradrobertson You makes my day! Thanks!
