### ISSUE TITLE
New DB name

### ISSUE THREAD

**Issue by Svashta** [influitive/apartment#281]
Hi,

Reading the docs i got an impression that whenever I create a new tenant a current environment string will be prepended to the DB name ("#{environment}_tenant_name"). However, my DB is always just a tenant name...

I am using MySQL and tenant names are gathered like this:

```
config.tenant_names = lambda { Organisation.pluck :tenant }
```

I create a new tenant:

```
Apartment::Tenant.create('some_tenant_string')
```

Am I missing something, maybe I don't understand how everything is connected?
Thx

**Comment by Svashta** [comment]
Ah, I see where the problem is.
This line was commented...

    config.prepend_environment = !Rails.env.production?

After uncommenting it my tenant DBs are now having environment prefixed - in development/test of course.

But may I say, that the docs are ultra confusing about this. Because, like it is written, one has impression that "by default" environment is prefixes - also in production. Only if this line is uncommented it will not be prefixed in production. At least this is how i understood it.

Sorry for confusion. But it is confusing :)

**Comment by bradrobertson** [comment]
We always accept pull requests to make the docs less confusing!
