### ISSUE TITLE
Drop All Tenants DBs

### ISSUE THREAD

**Issue by ajmyers01** [influitive/apartment#282]
Is there a good way to drop all of the existing Tenant databases? 

Something like rake:db:drop so I don't get the error: 
```
Apartment::TenantExists: The tenant TestTenant already exists.
```

**Comment by bradrobertson** [comment]
There's no command to drop ALL tenants in one, but you can use
```ruby
Apartment::Tenant.drop('tenant_name')
```
to [drop an individual tenant](https://github.com/influitive/apartment#dropping-tenants)

So you can iterate over all your tenants and run that for each one if you want.
