### ISSUE TITLE
Skip tenant seed on rake db:seed

### ISSUE THREAD

**Issue by jvanbaarsen** [influitive/apartment#283]
Is it possible to not seed the tenants when running `rake db:seed`? I might be overlooking this.

**Comment by bradrobertson** [comment]
In a roundabout manner you can if you look [here](https://github.com/influitive/apartment/blob/development/lib/tasks/apartment.rake#L109) you can optionally specify the tenants to run your task against. So you could run `DB="" rake db:seed`. Kind of a hack but *should* work?

**Comment by jvanbaarsen** [comment]
Hm ok, Thanks! Will give it a try later on. Would be great to have a config option to always skip seeding of the tenants :)
