### ISSUE TITLE
Switching tenants in rspec 

### ISSUE THREAD

**Issue by devmarwen** [influitive/apartment#284]
I am using the `apartment/elevators/subdomain` to switch between **tenants**.
When testing using **rspec** I set the `host` in a `before` hook:
```ruby
  before :each do
    @request.host = "tenant.domain.tn"
  end
```
hoping that the tenant will change, but not.
Is this normal behavior or am I missing something ?

Currently I'm using this instead:
```ruby
  config.before(:each) do
    Apartment::Database.switch 'tenant'
  end

  config.after(:each) do
    Apartment::Database.reset
  end
```

**Comment by bradrobertson** [comment]
If you're running controller specs, those don't go through Rails middleware. Think of a controller spec as a unit test for your controllers. It doesn't really know about the full stack and rspec is just injecting some dummy behaviour for you.

**Comment by devmarwen** [comment]
I suspected this and you confirmed it, thank you !
