### ISSUE TITLE
Switching Servers

### ISSUE THREAD

**Issue by davenpatel** [influitive/apartment#286]
I'm trying to switch between servers locally, just to test out the functionality and it doesn't seem to work as expect even when following the examples

```
config.tenant_names = {
      'Development' => {
          adapter: 'postgresql',
          host: 'localhost',
          port: 5432,
          database: 'postgres',
          username: 'test',
          password: ''
      }
  }
```

I end up getting the following message when trying to run migrations, after ensuring that the database is present is postgres.

```
rake db:migrate

Migrating ["Development", {"adapter"=>"postgresql", "port"=>5432, "database"=>"Development", "host"=>"localhost"}] tenant

The tenant ["Development", {"adapter"=>"postgresql", "port"=>5432, "database"=>"Development", "host"=>"localhost"}] cannot be found.
```

**Comment by masterkain** [comment]
perhaps related https://github.com/influitive/apartment/commit/abdffbf8cd9fba87243f16c86390da13e318ee1f#commitcomment-15398453

**Comment by MarkMT** [comment]
No doubt you've moved on, but a few thoughts in case anyone else reads this:

1. AFAIK you don't need to specify the database connection details in the tenant definition if all of your tenants are using the same server. Just the name of the tenant will suffice.
1. Assuming 'Development' really is what you want to call the tenant, I'm pretty sure you need to create the tenant explicitly with `Apartment::Tenant.create 'Development'` (though my own experience has been in the context of the spree_shared gem, which does this for you).
3. If you are using localhost in development with the subdomain elevator you will need to tweak the tld_length configuration to enable it to correctly pick your subdomain out of the hostname. In config/initializers/apartment.rb...
```ruby
Apartment.configure do |config|
  ...
  config.tld_length = 0 if Rails.env == 'development'
end
```
The default value is 1, which works for .com, .org etc, but if there's no suffix it will treat your subdomain as part of the parent domain.

**Comment by mikecmpbll** [comment]
multi-host support is now in apartment experimentally and will be developed actively going forward
