### ISSUE TITLE
Fix testing wiki page

### ISSUE THREAD

**Issue by wynksaiddestroy** [influitive/apartment#290]
The use of `Apartment::Database.drop`, `Apartment::Database.switch` and `Apartment::Database.reset` is deprecated.
Use `Apartment::Tenant.drop`, `Apartment::Tenant.switch!` and `Apartment::Tenant.reset` instead.
Take a look at wynksaiddestroy/apartment-wiki@529bad2 for the changes and easy merging.

**Comment by bradrobertson** [comment]
Merged thx!
