### ISSUE TITLE
Any tips on moving a single schema to a staging or test environment?

### ISSUE THREAD

**Issue by jhubert** [influitive/apartment#293]
I know this isn't specifically an apartment issue but I figure I can't be the only heavy apartment user who has run into this. I took a look through the postgresql documentation and it doesn't seem like migrating a single schema is that easy.

Does anyone have any tips or suggestions on how to move a single tenant to another database? For example, if I want to move one tenant and the public schema to a test database for debugging content issues or demoing features with live data.

So far, the easiest way seems to be to move it all over and then delete all the schemas except the one I want, but that's a little crazy as our system gets bigger and bigger.

**Comment by jrabramson** [comment]
You could try something like
pg_dump <db> -n 'public' -n '<tenant>' -f <file>

**Comment by jhubert** [comment]
Bah, I'm sorry. This ended up being a stupid question.

I had originally been trying to figure out how to copy the data from one schema to another schema (ie: clone one schema into a new schema) which seems to be hard. Then when I was running into this I conflated the problems.

Thank you. That works great.
