### ISSUE TITLE
Active Admin

### ISSUE THREAD

**Issue by jasper502** [influitive/apartment#294]
I am trying to switch tenants in Active Admin.  Summary of my troubles here:

http://stackoverflow.com/questions/35378248/switching-apartment-tenants-in-active-admin

If I add the tenant switch call in the AA model file it switches the tenant and I can see the data etc. but if I load the page a second time AA kicks me to the login page - except that I am not really logged out.

This is a bit over my head and I am hoping someone else has made this work or can point me in the right direction to help figure out why this is happening.

**Comment by jasper502** [comment]
Some progress - tried to add the output of the switch! call to a logger debug and that 'solved' the issue. If I set the switch call to a variable it also goes away:

logger.debug "Apartment Switch: #{Apartment::Tenant.switch!('abc').inspect}"    
new_tenant = Apartment::Tenant.switch!('abc')

**Comment by bradrobertson** [comment]
Is this issue closed then?

**Comment by jasper502** [comment]
I will close it and post / re-open if I find that it's not a pure Devise issue.
