### ISSUE TITLE
Creating records in migrations

### ISSUE THREAD

**Issue by Svashta** [influitive/apartment#298]
Sorry if this is trivial and not the right place to ask the question, but how do I add some initial records in migrations? It seems like the record creation is just skipped or something. I've tried few ways, but can't figure it out.

Is a running migration Tenant aware?
I would like to add a really simple record, like:
`NetworkType.create(name: "test")`

Should i first load the correct tenant? How?

Thx!

**Comment by mikecmpbll** [comment]
in standard usage migrations run sequentially on all your tenants https://github.com/influitive/apartment#managing-migrations (code: https://github.com/influitive/apartment/blob/3f8af6ae5e4188bea5c819f1b9ba31ad3c15eea2/lib/tasks/apartment.rake#L17-L28)

this will mean that `NetworkType.create(name: "test")` will be called once for each tenant, thus creating that record in all tenants. If you're not seeing the record, it could be that it's failing some rails validation, try using `create!` which'll force an exception and maybe make things clearer.

**Comment by Svashta** [comment]
Hi. Thanks for an answer.

I know about validations, and the only validation I have is uniqueness.
So, if record is not created is either not called at all, or tries to be created in Public DB.

I have problem with creating this record inside migration that is called when new Tenant is created (haven't tried it yet as a normal rake db:migrate process).

I am thinking that maybe migrations on Apartment::Tenant.create are loaded from the DB?
I've added record creation only recently in a  migration that was already executed for existent Tenants, but would like this record to be created on all future ones.

**Comment by mikecmpbll** [comment]
ah, migrations aren't run when tenants are created. when a new tenant is created the schema is loaded (equivalent of rake db:schema:load) on the new tenant, and seed data is loaded.

sounds like what you're doing is trying to load seed data, so you should use that for this.

**Comment by Svashta** [comment]
OK, it is clear now. Thanks for clarification!

**Comment by Svashta** [comment]
May I ask how is seed data loaded?
I am currently using seedbank and will have to refactor heavily if just seed:db is called.

Also I don't think my seed is called when tenant is created, at least I don't see any errors, which i think I should due to the nature seeds are currently organized.

**Comment by mikecmpbll** [comment]
seed data is loaded by just loading the file at the path defined by Apartment.seed_data_file. by default this is set to "#{Rails.root}/db/seeds.rb", the standard rails seed file location. i don't know anything about seedbank, but if it's anything like the regular seeds file you can probably point Apartment.seed_data_file at it?

**Comment by Svashta** [comment]
Fantastic! :) Works like a char.
I was of course missing seed_after_create, but after figuring that out and setting my custom file, everything is just perfect. Thanks for pointing me in right direction.

Maybe it would be beneficial if seed_after_create and seed_data_file would be mentioned in the readme.

Thx Mike.

**Comment by mroach** [comment]
I found that when using both Seedbank and Apartment, you need to have your `gem 'seedbank'` line in your Gemfile come *before* apartment. This is because both gems override/wrap the `db:seed` task and if you load seedbank after, it'll wipe out the overrides from apartment and you'll end up seeding your 'public' space and not the tenants when you run `bundle exec rake db:seed`

**Comment by mikecmpbll** [comment]
we now have a `create` callback via `ActiveSupport::Callbacks` which you could hook in to for your custom seeding needs, I would imagine. https://github.com/influitive/apartment/blob/development/lib/apartment/adapters/abstract_adapter.rb#L23

**Comment by mikecmpbll** [comment]
in addition, i wonder whether we should be invoking the db:seed rake task rather than loading the seed file directly.

**Comment by nlsrchtr** [comment]
I was also facing the issue with integrating seedbank and apartment. It would be great if apartment would just call the rake task directly.
