### ISSUE TITLE
Missing schema.rb causes hard exit of process in Production Rails Env

### ISSUE THREAD

**Issue by edave** [influitive/apartment#301]
If I try running `Apartment::Tenant.create` when there is no `schema.rb` present, the current process the code is being run in exits (as in is killed/quits) and prints a generic error message to the terminal that the schema does not exist.. See this example:

```
dave@dave-MBP ~/repositories/my_repo (master) $ RAILS_ENV=production rails console
Loading production environment (Rails 4.2.5.1)
2.2.4 :001 > Apartment::Tenant.create('apartment')
/Users/dave/repositories/my_repo/db/schema.rb doesn't exist yet
dave@dave-MBP ~/repositories/my_repo (master) $ 
```

While I understand that there's a good reason to have `schema.rb` exist, it makes it quite difficult to track down the cause of this problem with the current behavior. Instead, it'd be great if some sort of Exception were thrown to aid in debugging, as well wrapping in try/catch behavior if necessary (say for production environments).

**Comment by bradrobertson** [comment]
You're welcome to submit a PR with a proper exception being thrown if you like!
