### ISSUE TITLE
manage subdomain as part of domain

### ISSUE THREAD

**Issue by Xosmond** [influitive/apartment#302]
Hi guys, i have a question (problem), i want make work this gem to treat with subdomains of a subdomain, so my principal subdomain would be apps.domain.com, and the gem would manage every subdomain of that subdomain like:

```
abad.apps.domain.com
asa.apps.domain.com
```

Is that posible?
Thanks.

**Comment by bradrobertson** [comment]
Totally. you can configure whatever [tld length](https://github.com/influitive/apartment#switching-tenants-per-request) you want. Just read about tlds on the Readme.
