### ISSUE TITLE
Rescue from Apartment::TenantNotFound

### ISSUE THREAD

**Issue by almaron** [influitive/apartment#306]
Hello. I ran into a problem. I'm trying to rescue from the Apartment::TenantNotFound error , but the error is obviously located in some middleware I can't get access to. I just want to display a nice error page, nothing sophisticated. 

What's the best way to do that?

**Comment by bradrobertson** [comment]
This [this issue](https://github.com/influitive/apartment/issues/235) and [some](http://stackoverflow.com/questions/27188411/apartment-ruby-gem-want-to-catch-an-exception) other [sources](http://stackoverflow.com/questions/11667710/how-to-rescue-custom-exceptions-coming-from-a-middleware-in-rails-3-2)
