### ISSUE TITLE
Rails 5: ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base

### ISSUE THREAD

**Issue by vladra** [influitive/apartment#310]
Encountered error with apartment gem using rails5.beta4.

Every 3-5 connection is receiving error (sometimes every connection in a row):

    Rack app error: #<ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base>

Anyone encountered this before? Any tips to solve this?

DB connection pool is more then enough and set to 40. 1 user only. Puma server, running 2 workers with 8 threads each.

Full stack trace:

    Rack app error: #<ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base>
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.0.beta4/lib/active_record/connection_adapters/abstract/connection_pool.rb:878:in `retrieve_connection'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.0.beta4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.0.beta4/lib/active_record/connection_handling.rb:87:in `connection'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.0.beta4/lib/active_record/query_cache.rb:47:in `block in install_executor_hooks'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:396:in `instance_exec'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:396:in `block in make_lambda'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:546:in `catch'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:546:in `block in default_terminator'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:170:in `block in halting'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:454:in `block in call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:454:in `each'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:454:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:750:in `_run_complete_callbacks'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/callbacks.rb:90:in `run_callbacks'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/execution_wrapper.rb:107:in `complete!'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/execution_wrapper.rb:64:in `ensure in block in run!'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/execution_wrapper.rb:64:in `block in run!'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/execution_wrapper.rb:58:in `tap'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0.beta4/lib/active_support/execution_wrapper.rb:58:in `run!'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.beta4/lib/action_dispatch/middleware/executor.rb:10:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0.beta4/lib/action_dispatch/middleware/static.rb:136:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/rack-2.0.0.alpha/lib/rack/sendfile.rb:111:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/sentry-raven-0.15.6/lib/raven/integrations/rack.rb:53:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/skylight-0.10.3/lib/skylight/middleware.rb:61:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/railties-5.0.0.beta4/lib/rails/engine.rb:522:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/configuration.rb:227:in `call'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:561:in `handle_request'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:406:in `process_client'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/server.rb:271:in `block in run'
    /home/developer/crm/shared/bundle/ruby/2.3.0/gems/puma-3.2.0/lib/puma/thread_pool.rb:111:in `block in spawn_thread'

**Comment by vladra** [comment]
Solved this issue, by switching Puma to preload application. Tried to understand, but have no idea why it is happening. Without apartment gem, Puma works fine in any mode.

Sidekiq still throws same error occasionally.

**Comment by vladra** [comment]
It seems it is related to connection adapter being not thread safe

#311

**Comment by Xosmond** [comment]
I have experimented this too. When using sqlite3 database. @vladra  how did you solve it?

**Comment by vladra** [comment]
@Xosmond 
this exact fork worked for us:
```ruby
gem 'apartment', github: 'vladra/apartment', branch: 'connection_based_threading_fix'
```

but now we switched to Sequel
