### ISSUE TITLE
Apartment with threaded server (Puma)

### ISSUE THREAD

**Issue by vladra** [influitive/apartment#311]
Hi guys,

Anyone have success using Apartment gem with Puma?

I'm encountering problem, which is caused by multiple threads. If I have more then 1 thread available, and bunch of ajax requests are fired at the same time, 1 or 2 of requests hitting default DB, instead of Tenant DB.

It seems that some part of Apartment is not thread safe?

Has anyone encountered same issue? Any tips where should I look at? I'm using Postgres with separate databases (not schemas) setup.

For now I reduced Puma threads to 1 per worker, and this solved my issue temporary.

**Comment by albertyw** [comment]
This may be related to #180

**Comment by mikecmpbll** [comment]
are you using a 'connection' adapter? or a schema adapter? the connection adapters aren't threadsafe.

**Comment by vladra** [comment]
yep, I'm using connection adapter (1 tenant = 1 DB). So that is the reason. Can you please advice where I should look at to solve this issue?

**Comment by mikecmpbll** [comment]
i did some work on it some time ago now at #266 , but it still needs some work as there's an issue with an exorbitant number of db connections getting used.

**Comment by vladra** [comment]
Thanks, will take a look into your PR

We have few tenants with pretty big DB each. Each tenant is a country. Atm, it's 3 DB about 3-5 Gb each. Since amount of tenants will grow, we thought it is best for us to go with separate databases approach. Lets say 15 databases about 5 Gb each, to up to 100 Gb in total.

If we would use lots of tenants with small amount of data each, I would go with schema adapter.

**Comment by mikecmpbll** [comment]
ah okay, fair enough, i don't know much about pg. i'm doing some work on the PR today.

**Comment by kaspernj** [comment]
I am having this issue as well. Can I ask why this issue was closed?
