### ISSUE TITLE
Adding Index issue during migration

### ISSUE THREAD

**Issue by yzhouWework** [influitive/apartment#315]
Hi Guys,

I am trying to add an index on a table which is existing all tenants. However, the index is only add to the public tenant, and return an error for next tenant(Index name 'index_name' on table 'table_name' already exists). Is there a walk around for this kind of index addition? Your help will be appreciated.

Thanks

**Comment by bradrobertson** [comment]
We use indexes all the time, this is fully supported by Apartment for tenants. We'd need more information to help. Is this an excluded model? Are you schema migrations tables up to date?

**Comment by yzhouWework** [comment]
Hi Brad,

Thank you for the quickly response, and this test table is not in exclude model..

Here is the scenario. 
We have two custom tenants(tenant1, tenant2)
 I created a migration in rails app to add table to all tenant and add index afterward for all them.  

class TestMigration < ActiveRecord::Migration
  def change
   
    create_table :test_multi_tables do |t|
      t.string :name
      t.uuid :uuid
    end

   add_index :test_multi_tables, :uuid, name: 'test_multi_table_uuid_index'
  end

end

After ran the migration, the index was created in 'public' schema, but could not add the index into 'tenant1' schema since there is same index name in 'public' schema.  

Hopefully, this will give you a more info on this issue.

Thanks

**Comment by bradrobertson** [comment]
There's no issues having index names that are the same across schemas. So having an index on public, and having the same name of one on a postgres schema is totally fine. Again, we do this all the time. What version of Rails are you using?

**Comment by yzhouWework** [comment]
Rails 4.1.7
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

**Comment by bradrobertson** [comment]
Not sure TBH. Perhaps try going to Rails 4.2? That's what we use without any problems.

**Comment by yzhouWework** [comment]
Thanks Brad!

**Comment by johnclittle** [comment]
FWIW. For some reason, we are having the same issue on Rails 4.2.6. We found that using something like the following [add_index("#{::Apartment::Tenant.current}.roles", :name, name: 'index_roles_on_name')](url)
seems to make it work.  [We found this](https://github.com/influitive/apartment/issues/262/) which led us to this solution. Hope this helps.

**Comment by bradrobertson** [comment]
This is weird. We definitely don't do this in our app and indexes work fine ??

**Comment by yzhouWework** [comment]
@johnclittle, thank you for the help. I definitely will keep it in mind. What I did to fix it was removing the public from persistent_schemas.

**Comment by johnclittle** [comment]
@yzhouWework, your suggestion of removing public from persistent_schemas fixed everything for me. I went back and read the readme again and I now have a better understanding. Thank you.

**Comment by bradrobertson** [comment]
Oh, ya you CANNOT have public in `persistent_schemas`.

**Comment by yzhouWework** [comment]
@johnclittle Glad to help. You are welcome!

**Comment by johnclittle** [comment]
Brad, this gem is great. I figured it was something in my configuration just didn't know what. Thank you for your support.
