### ISSUE TITLE
Multiple tenants creation

### ISSUE THREAD

**Issue by waghanza** [influitive/apartment#318]
Hi all,

I've a `rails` app  with **100** tenants (at least for now).
I want to create them in a loop (of **100** items)
~~~ruby
Company.all.each do |c|
  Apartment::Tenant.create(c.tenant)
end
~~~
it appears that I use **hstore** extension (created in a **persitant_schema**).
However, I can create my tenants.
First tenant created successfully 
~~~ruby
   (1.4ms)  CREATE SCHEMA "xxxxxxxxxxxxxxxxxx"
  SQL (0.4ms)  CREATE EXTENSION IF NOT EXISTS "plpgsql"
  SQL (24.6ms)  CREATE EXTENSION IF NOT EXISTS "hstore"
  ....
  (2.3ms)  COMMIT
~~~
but second creation fails
~~~ruby
   (2.3ms)  CREATE SCHEMA "yyyyyyyyyyyyyyyyyyyyyy"
  SQL (0.2ms)  CREATE EXTENSION IF NOT EXISTS "plpgsql"
  SQL (0.2ms)  CREATE EXTENSION IF NOT EXISTS "hstore"
  ....
~~~
untill I have
**ActiveRecord::StatementInvalid: PG::UndefinedObject: ERREUR:  le type « hstore » n'existe pas**

Does somebody has this error ?

**Comment by bradrobertson** [comment]
That's odd. We also use `hstore`. What version of ActiveRecord are you using?

**Comment by waghanza** [comment]
I'm using `rails` **5**, but switch to `jsonb` type in **postgresql**
