### ISSUE TITLE
Alter exiting Hstore extension on Heroku

### ISSUE THREAD

**Issue by yzhouWework** [influitive/apartment#320]
Hi,

I read the comment from [here](https://github.com/influitive/apartment/pull/158/commits/112cbcbe5b5b617abffaf06907da995538898c70).  However, we have exiting Hstore extension on public schema, and we do not want to drop it and recreate on shared_extensions, since there are many data on it. I would like to know if there is way we can use public as our shared extension schema without alter it.

Thanks

**Comment by bradrobertson** [comment]
All we're doing is putting the `extensions` schema in the search path *for all requests* ( we call them `persistent_schemas`). This allows postgres to query from whatever schema `hstore` is on.

Unfortunately however, having `public` in the search path all the time has *I think* yielded errors when people tried it. I haven't confirmed this myself, but you can put `public` in `persistent_schemas` as an attempt. My guess however is that it won't work.

**Comment by yzhouWework** [comment]
Thank you for the feed back. I am testing it now.

**Comment by yzhouWework** [comment]
Yes, you are right. There will be an error for migration.
