### ISSUE TITLE
Possible connection leak

### ISSUE THREAD

**Issue by jsperezg** [influitive/apartment#321]
Good afternoon.

I've found a possible connection leak when working with Apartment. These are the steps to reproduce it:
- I've set the pool size to 1. After switching to the tenant I see that MySQL has two connections: 1 for the tennant and another to the database where the excluded models are.
- When I access to a belongs_to mapping which model is one of the excluded models I see that rails creates a new connection for it instead of using the existent one. 

This results in one connection per each access to excluded model so under heavy load my server stops attending requests because it reaches the max_connections limit.

I've tried to enclose the access to these relationships inside a switch block but it stills keep creating a new connection per model accessed.

PD: It's my first issue reported. Don't hesitate to ask me if you need additional information.

**Comment by jsperezg** [comment]
I respond to myself. 

This is happening only when config.use_schemas = false in MySQL

**Comment by jsperezg** [comment]
After a day of making tests I can add more information about this issue: Running the app with config.use_schemas = true makes the number of connections stay stable. The drawback is that the connections used to access the excluded model is the same than the used for the models in the tenant. Seems that it's creating connections that are not used (all connections created by the pool that is supposed to access to excluded models).

**Comment by senny** [comment]
I was just investigating some connection pool issues we were seeing on Heroku. We use a threaded webserver (puma) with 5 worker threads and a db pool size of 5 and we would regularly see "could not obtain a database connection within 5.000 seconds" errors. Looking closer at the connections held by our web dynos revealed that there was an unused connection per process, leaving only 4 connections in the pool for 5 competing threads.

I suspect that the issue is that apartment uses a database connection during the Rails boot process. The checks out a connection from the pool for the main thread that is never returned.

@bradrobertson any thoughts on this?

**Comment by mikecmpbll** [comment]
hi @senny 

what DB are you using and what switching style? (`use_schemas` config option)

the switching and connection handling code is quite different depending on these factors, so this info should help to isolate the issue.

**Comment by mikecmpbll** [comment]
btw, with respect to the OP: when you use the connection-based switching strategy (`use_schemas = false`) apartment calls `establish_connection` for each excluded model. `establish_connection` creates a new connection pool, so that's why you're experiencing what you describe.

**Comment by senny** [comment]
@mikecmpbll we are using schemas with PostgreSQL.

**Comment by mikecmpbll** [comment]
weird. afaict, on load it just initialises the adapter with the current connection config (`ActiveRecord::Base.connection_config` by default) and processes excluded models, which for pg schemas just means modifying the model's `table_name`. i don't see anything there which touches the database.

**Comment by jsperezg** [comment]
@mikecmpbll I realized that the unique way to maintain the number of connections defined in the connection pool stable was setting use_chemas = true. 

This issue could be simply solved  by describing this behaviour in the gem docs.

**Comment by jsperezg** [comment]
@senny I've observed also this behaviour. It's creating unnecessary connections. It should use the same connection for accessing both models in the tenant and models outside it.

**Comment by senny** [comment]
@mikecmpbll It's also the `tenant_names` configuration:

```
Apartment.configure do |config|
  config.tenant_names = -> { Account.pluck(:shortname) }
end
```

**Comment by mikecmpbll** [comment]
@senny i don't see where that proc gets called during initialisation, but could be wrong.

not sure what to do about this, i don't presume it's that unusual for gems to touch the database during initialisation?

**Comment by senny** [comment]
@mikecmpbll it should be. That's why this gem contains workarounds like #169 but that's just some symptom. Again, as I outlined with a threaded web server you'll be holding a unused connection on the main thread until the process exits. We had very strange connection issues because we used a pool of 5 with 5 threads but didn't notice 1 of the 5 connections was constantly held by the main thread.

**Comment by senny** [comment]
If using the db connection can't be avoided the [`with_connection` helper](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#method-i-with_connection) might be a solution to check them back in.

**Comment by mikecmpbll** [comment]
@senny i've created a branch to test a fix, would you be able to try it out? https://github.com/mikecmpbll/apartment/tree/dont-retain-connection-during-init

i wasn't sure how best to write the test, as the railtie is loaded when the test suite is initialised and i couldn't figure out how to call the `to_prepare` code from the test suite (derp). i wrote a test though which just duplicates the same code as the to_prepare, and it fails with the old code and passes with the new so i think that confirms things.

**Comment by senny** [comment]
@mikecmpbll thanks, I'll see if we can give this a dry-run in our staging environment. I'll share my findings once we gave it a try.

**Comment by senny** [comment]
@mikecmpbll just deployed the fix in our staging environment. Everything is looking good. I am no longer seeing leaked connections. Thanks for your work 💛

**Comment by mikecmpbll** [comment]
@senny excellent, i'll tidy up the test and make PR this evening. thanks for helping with the bug report.

**Comment by jsperezg** [comment]
Good job guys!
