### ISSUE TITLE
multi tenant double entry accounting

### ISSUE THREAD

**Issue by armanlearn** [influitive/apartment#324]
Hi .
I use postgresql database and I want to use schema option for multi tenant.
I have 500 tenant .Every tenant has 20 table , and some table have 10 million record. 
is apartment gem good for my work ? I know it depends of server and same issues , but you think as a background knowledge and your Experience . do I face any problem in feature if I use apartment and Postgresql  ?

**Comment by bradrobertson** [comment]
We're currently moving away from using Apartment, particularly on tables that have a lots of records. We're tending towards specific dbs for those tables. Say you have an "events" tables, or something that logs lots of things happening. I don't think Apartment (and questionably postgres) is necessarily the best tool to use.

**Comment by armanemadi** [comment]
tanks @bradrobertson for your fast answer , and what is solution for multi tenant for this kind of site , In my search Apartment is best gem for this job . you think postgres schema make db slow ? please give me some golden Advice because I am very raw . and many tanks that you was so honest about Apartment.

**Comment by bradrobertson** [comment]
Honestly your technology choices are really case-by-case and use-case specific. People often opt for something distributed that can scale out horizontally if they're logging large volumes of events. It all depends on what you're doing, how you want to query the data, what kind of consistency/availability you need so it's pretty hard to say.

I'd suggest you keep Apartment usage to config based storage (not logging of a high volume of events) and use something more distributed like DynamoDB, Riak, RethinkDB or Cassandra for logging events and use a secondary index on some sort of `Tenant` uuid.

That's about as specific a tip I can give without knowing what you're doing (or charging you lots of $$ for consulting ;) )
