### ISSUE TITLE
Public schema is not migrated

### ISSUE THREAD

**Issue by tangopium** [influitive/apartment#327]
I noticed that the public schema (which is my default schema) is not migrated when calling `db:migrate` (or `apartment:migrate`). Is this an expected behavior? And what if I need to modify an 'excluded_models'? Thanks in advance :)

**Comment by bradrobertson** [comment]
Excluded models shouldn't affect the public schema. It will *definitely not* be migrated when running `apartment:migrate`. It *should* be migrated when running `db:migrate`. Anything different about your setup? We've never heard of this before.

**Comment by tangopium** [comment]
You are completely right! Sorry! `db:migrate` did it. Seems as I had a confusion!

**Comment by bradrobertson** [comment]
Glad you got it sorted!
