### ISSUE TITLE
ActiveRecord association caching

### ISSUE THREAD

**Issue by jhjwind** [influitive/apartment#329]
My application needs to aggregate the query results from multiple schemas. So I wrote a function that takes a block, runs it in all tenants and aggregate the results. 

```
  # This method executes the block within all tenants and concatenate the results from the block
  # expect the block to return an array.
  def self.execute_in_all_tenants
    ['apac', 'global'].map do |tenant_name|
      Apartment::Tenant.switch!(tenant_name)
      yield
    end.flatten
  end
```

```
execute_in_all_tenants do
   account.payment_methods
end
```

However, it seems that Rails caches the results. In the example above, the results from two tenants are always the same, unless I change it to `account.payment_methods.reload`

I tried using `ActiveRecord::Base.connection.uncached` but it doesn't work. After some digging, I found that Rails also has [association caching](https://github.com/rails/rails/issues/2878)(in addition to query caching). Association caching can only be invalidate by calling `reload`. 

Have you run into this problem? Any idea how to solve this?

**Comment by jhjwind** [comment]
I thought using `switch` with a block solves the problem, but it didn't.
```
    results = []
    ['apac', 'global'].map do |tenant_name|
      Apartment::Tenant.switch(tenant_name) do
        result =  yield
        results << result
      end
    end
```

**Comment by mikecmpbll** [comment]
the reason is most likely not caching, but lazy loading. if `payment_methods` is just a rails association then calling `account.payment_methods` doesn't actually do anything other than build the relation, it does not query the database.

what you'll want to do is `account.payment_methods.to_a` inside the block.

**Comment by jhjwind** [comment]
@mikecmpbll thanks for you reply!

As a matter of fact, I do call `account.payment_methods.to_a`. The only way I can get this to work is to call `account.clear_association_cache` before calling `account.payment_methods.to_a`. However I have other more complicated scenario, where a lot of things go into the block and I can't call `clear_association_cache` on every ActiveRecord instance.

**Comment by mikecmpbll** [comment]
gotcha. there's no easy way for apartment to clear this cache as far as I can tell, it's decentralised across all the association instances (we'd have to iterate over all Aparment.connection_class.descendants and their associations?).

using reload in your code seems the correct approach.

**Comment by jhjwind** [comment]
`Aparment.connection_class.descendants` returns the classes, not the instances. `clear_association_cache` only exists on the instances. 

Using `reload` isn't quite scalable for me because the logics in the execution block can get really complicated. 

Do you know other way to aggregate results from multiple tenants?

**Comment by mikecmpbll** [comment]
ah yep. i can't see anyway to clear it completely, and that would be potentially undesirable in some circumstances too. you will have to keep an array of the instances so you can easily reload them after switching database, or something like that.

```ruby
# e.g.
def self.execute_in_all_tenants *instances_to_reload
  results = []
  ['apac', 'global'].map do |tenant_name|
    Apartment::Tenant.switch(tenant_name) do
      instances_to_reload.each{ |i| i.reload }
      result =  yield
      results << result
    end
  end
end

execute_in_all_tenants account do
   account.payment_methods
end
```

i wrote [querrel](https://github.com/meritec/querrel) for this sort of thing and i've not experienced this problem, but it's probably because all queries that i make are from the constant, not an already defined instance.

**Comment by patodevilla** [comment]
I found what seams like a possible solution for this. I am not using apartment

```ruby
  # @override
  def association(name)
    # expire cache if Current.client_id changed
    if instance_variable_defined?('@_client_scope') && @_client_scope != Current.client_id
      clear_association_cache
    end
    @_client_scope = Current.client_id
    super
  end
```

Where `Current < ActiveSupport::CurrentAttributes`

https://github.com/rails/rails/blob/593893c901f87b4ed205751f72df41519b4d2da3/activerecord/lib/active_record/associations.rb#L297
