### ISSUE TITLE
Rails 5 issues

### ISSUE THREAD

**Issue by rash-pro** [influitive/apartment#331]
Is there a reason why the activerecord version must be < 5.0 on the gemspec?

I can't upgrate to rails 5 due to that restriction

Thanks in advance!

**Comment by GCorbel** [comment]
I have the same issue. Rails 5 is out today!!!

**Comment by helloinc** [comment]
+1

**Comment by GCorbel** [comment]
I just created a pull request.

**Comment by grex84** [comment]
any news on this?

**Comment by mikecmpbll** [comment]
@grex84 #333 tests currently failing.

**Comment by idlogi** [comment]
Any update on this?  I'm using rails 5.0.0,
Initially I got an error -> NameError: uninitialized constant Apartment::Tenant (apartment (0.24.3))
then i update apartment to 1.1.0. but i got an error below :

Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    apartment (~> 1.1) was resolved to 1.1.0, which depends on
      activerecord (< 5.0, >= 3.1.2)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      activerecord (= 5.0.0)

Could help me on this Thanks!

**Comment by djvs** [comment]
Note, I was having zero problems using Apartment with 5.0.0.rc3, IDK what incompatibilities exist but I didn't experience any.

**Comment by grex84** [comment]
Same here

**Comment by bradrobertson** [comment]
1.2 now release with rails 5 support.
