### ISSUE TITLE
Constraints on database tenant

### ISSUE THREAD

**Issue by waghanza** [influitive/apartment#334]
Hello,

I'm using `apartment` **gem** to isolate databases (same structure).

Is there any way to add constraint (unicity, foreign_keys ...) on tenants ?

I mean : is there a way to enforce unicity on all record in the database no matter in what tenant we are.

**Comment by bradrobertson** [comment]
If you want cross tenant constraints it'd have to be an excluded model. There's not way to enforce uniqueness across different tables of different schemas AFAIK.

That's just a postgres thing, nothing to do with apartment. You can look up to see if you can generate a unique index across multiple tables, but my guess is No.

**Comment by waghanza** [comment]
what do you mean by **an excluded model** ?

**Comment by bradrobertson** [comment]
https://github.com/influitive/apartment#excluding-models

These are basically *non* tenanted models, that all live in the public schema, so you can have unique constraints on them like you would any other non-tenanted table.

**Comment by waghanza** [comment]
ok, so is this available when model are in an other database ?

**Comment by waghanza** [comment]
ok thanks
