### ISSUE TITLE
uninitialized constant Apartment::Tenant

### ISSUE THREAD

**Issue by djvs** [influitive/apartment#337]
Just upgraded from Rails 5.0.0.rc3 to Rails 5.0.0 (first major release) via bundle update, with a bunch of various updates (ActiveSupport, ActiveRecord/ActiveModel, etc.).  All of a sudden Apartment totally breaks. 

Autocompleting Apartment::Ten (tab) gives me this:

    2.3.1 :005 > Apartment::Tenant
    Apartment::TenantExists    Apartment::TenantNotFound

**Comment by mastertechrv** [comment]
Same issue I updated to Rails 5.0.0, and i am working with Apartment Gem and i am getting the same issue 
`uninitialized constant Apartment::Tenant`

**Comment by djvs** [comment]
Apparently it was renamed to Apartment::Database

**Comment by bradrobertson** [comment]
Mmm... no where are you seeing that. `Apartment::Database` is OLD. `Tenant` is new.

**Comment by djvs** [comment]
Apartment was thrown back to 0.2.4 by the bundle update due to unspecified versions of activerecord etc.  Manually setting it at '~> 1.1.0' throws me to this:

https://github.com/influitive/apartment/issues/331

**Comment by mastertechrv** [comment]
@djvs i have that same issue

**Comment by bradrobertson** [comment]
This is fixed with `v1.2.0` just released. Sorry there's obviously a *very* old gem still up there that didn't have a max limit on activerecord versions.
