### ISSUE TITLE
uninitialized constant Apartment::Tenant

### ISSUE THREAD

**Issue by mastertechrv** [influitive/apartment#338]
`Apartment::Tenant.create(business_subdomain)`

Rails 5
ruby 2.3.0p0
Just Updated to Rails 5, working with Apartment gem for a new app, and i run across this error
![screen shot 2016-07-26 at 11 04 27 pm](https://cloud.githubusercontent.com/assets/6068761/17162597/5f63ec08-5385-11e6-9f21-0670dc29535c.png)

**Comment by bradrobertson** [comment]
This has been reported before. We're not using Apartment with Rails 5 at all so I haven't looked into it, but high level this doesn't make any sense. `lib/apartment.rb` [directly requires tenant.rb](https://github.com/influitive/apartment/blob/development/lib/apartment.rb#L5) so Rails must be doing something magical here to make this fail.

**Comment by mastertechrv** [comment]
Ive reproduced the error with rails 4.2 and its the exact same error, i change the Tenant to Database and the error goes away

**Comment by bradrobertson** [comment]
What version of the gem are you using?

**Comment by mastertechrv** [comment]
0.24.3

**Comment by bradrobertson** [comment]
You should probably just grab the current version instead of using an old one. Apartment is currently on [1.1](https://rubygems.org/gems/apartment)
