### ISSUE TITLE
Apartment::Tenant.reset(s) when using Devise/Warden middleware

### ISSUE THREAD

**Issue by typeoneerror** [influitive/apartment#340]
We've got a Generic apartment subclass that calls `super` and `reset`s the schema if the Apartment is not found: 

```rb
def call(env)
  begin
    super
  rescue Apartment::TenantNotFound => error
    Apartment::Tenant.reset
    Rails.logger.warn(error)
    return [404, { 'Content-Type' => 'text/html' }, []]
  end
end
```

If I do the following:

* visit existingtenant.domain.com
* visit nonexistingtenant.domain.com

From now on I see in logs:

One of the following schema(s) is invalid: "nonexistanttenant" "existingtenant" 

So `reset` does not appear to be working from request to request. Is that correct? How can we completely ensure that schema path is reverted to "public" if a tenant isn't found?

**Comment by bradrobertson** [comment]
Now sure what you mean by "from now on", but the error message you get [from here](https://github.com/influitive/apartment/blob/development/lib/apartment/adapters/postgresql_adapter.rb#L72) will mention all possible schemas that could be invalid. This includes the currently attempted schema being switched to and the previous schema the connection was on. It definitely resets properly

**Comment by typeoneerror** [comment]
By "from now on" I mean if I refresh the page, or open new windows, I still see the previously switched schema the connection was on "existingtenant". Should it not be displaying "nonexistanttenant" "public" after the reset? Perhaps I'm not understanding how that works.

**Comment by typeoneerror** [comment]
Maybe this will help? Here's an example of what I'm doing. I'm opening new tabs and making requests to the application (using subdomain elevator here). Assuming that "one" and "two" are valid tenants and "nope" and "alsonope" will throw `TenantNotFound` and should `reset`.

```
> request to one.domain.com
> request to nope.domain.com

One of the following schema(s) is invalid: "nope" "one"  <- reset
One of the following schema(s) is invalid: "nope" "one"  <- refresh, next request still has "one" 
One of the following schema(s) is invalid: "nope" "one"  <- refresh
One of the following schema(s) is invalid: "nope" "one"  <- refresh

> request to two.domain.com <- schema set to "two"
> request to alsonope.domain.com

One of the following schema(s) is invalid: "alsonope" "two" 

> request to one.domain.com <- schema set to "one"
> request to nope.domain.com

One of the following schema(s) is invalid: "nope" "public" <- now it's reset, but why now?
```

**Comment by typeoneerror** [comment]
Interesting, so I am using Devise, and with the latest change do using Apartment in a block, it fails any time I make a POST to a Devise controller. So I took a look at the Rack stack:

```
$ rake middleware
...
use Warden::Manager
use Apartment::Reloader
use TenantDetectorMiddleware
run Doki::Application.routes
```

I thought I might try this:

```
Rails.application.config.middleware.insert_before "Warden::Manager", TenantDetectorMiddleware
```

```
$ rake middleware
...
```
use Warden::Manager
use Apartment::Reloader
run Doki::Application.routes
```

And now the Devise stuff works! So seems that the Apartment middleware needs to come before Warden that it's still running in the context of that middleware? Does that make sense?

**Comment by typeoneerror** [comment]
Closing as https://github.com/influitive/apartment/issues/349 is a duplicate. Will update docs.
