### ISSUE TITLE
UUID support and Rails 5

### ISSUE THREAD

**Issue by katgironpe** [influitive/apartment#342]
Been testing this gem with Rails 5. I am not getting good results when I use UUID instead of ID. I have seen similar issues, but the answers don't solve the problem.

```
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function uuid_generate_v4() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: CREATE TABLE "companies" ("id" uuid DEFAULT uuid_generate_v4() PRIMARY KEY, "user_id" integer, "name" character varying, "location" character varying, "body" text, "subdomain" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```

The example application is here https://github.com/katgironpe/multitenant

**Comment by richpeck** [comment]
Add line in your `db/migrate/create_companies` migration::

```
class CreateCompanies < ActiveRecord::Migration[5.0]
  def change
     enable_extension 'uuid-ossp' # => http://theworkaround.com/2015/06/12/using-uuids-in-rails.html#postgresql
    create_table :companies, id: :uuid do |t|
      t.references :user
      t.string :name
      t.string :location
      t.text :body
      t.string :subdomain

      t.timestamps
    end

    add_index :companies, :subdomain
  end
end
```

If you anticipate using something other than PGSQL, you'll want to use something like the following:

```
def change
   @adapter_type = connection.adapter_name.downcase.to_sym
    case @adapter_type
      when :mysql
        execute("DROP TRIGGER IF EXISTS before_insert_associations;") #http://stackoverflow.com/a/5945220/1143732
        execute("CREATE TRIGGER before_insert_associations BEFORE INSERT ON associations FOR EACH ROW SET new.uuid = uuid();")
      when :sqlite
        # Nothing to do
      when :postgresql
        enable_extension 'uuid-ossp' # => http://theworkaround.com/2015/06/12/using-uuids-in-rails.html#postgresql
      else
        raise NotImplementedError, "Unknown adapter type '#{@adapter_type}'"
    end
...

end
```

**Comment by bradrobertson** [comment]
Ya functions that come from extensions always need to be "visible" to your postgres connection. These extensions are normally installed to the `public` schema, but Apartment actually *switches* schemas when you make requests. The general workaround is to create an `extensions` schema and make that a persisted schema (so it's always in the `schema_search_path` no matter what tenant schema you're currently on)
See [here](https://github.com/influitive/apartment#installing-extensions-into-persistent-schemas) for more details.

**Comment by katgironpe** [comment]
@richpeck Thank you. That worked. But I don't know why the tenant was not created when I do `rake tenants:create`. Still testing this out.  https://github.com/katgironpe/multitenant/blob/master/lib/tasks/tenants.rake
