### ISSUE TITLE
Heroku rake assets:clean trying to connect to database

### ISSUE THREAD

**Issue by frank-west-iii** [influitive/apartment#346]
Very similar to this issue here, during heroku push the `rake assets:clean` command attempts to connect to the database.

https://github.com/influitive/apartment/issues/106

I would imagine the same fix presented here, but for `clean` would fix this.

https://github.com/influitive/apartment/pull/169

Happy to create a pull request if you agree.

**Comment by bradrobertson** [comment]
makes sense I think. happy to merge a PR
