### ISSUE TITLE
Inquiry : Multi Tenancy at Domain Level

### ISSUE THREAD

**Issue by hamdisy** [influitive/apartment#347]
Hi everyone,
Currently i have no problem in using influitive/apartment in subdomain level. It's works perfectly though there're some bugs on Rails 5 but looks like already been resolved.

I plan to switch subdomain approach (1 tenant 1 subdomain) to domain approach.
1. Let's say domain name is www.domain.com
2. User registration (using devise) will be in 'public' scheme. There is account_name information there.
3. After user login successfully, system will switch to certain scheme ex.account_name  that taken from point 1, but domain is expected to be www.domain.com also (no certain subdomain for each tenant)

It looks like not so many/limited example provided for Multi Tenancy at Domain Level.

Appreciate your kind support.

Thanks !

**Comment by mikecmpbll** [comment]
there is a section in the readme called ["Switching Tenants per Request"](https://github.com/influitive/apartment#switching-tenants-per-request) which describes switching on domain.
