### ISSUE TITLE
Records not beings saved to the current Tenant

### ISSUE THREAD

**Issue by glennfu** [influitive/apartment#354]
I'm using Rails 4.1.15, apartment-sidekiq 1.1.0, sidekiq 4.0.2, apartment 1.2.0. My issue is that some jobs write records to the intended Postgres schema, and some do not.
Here's a small snippet of my code from a Sidekiq job:

```
account = Account.find 12345
Apartment::Tenant.switch!(account.schema)
@case = Case.find 123 # this was saved in a previous job into the correct Tenant schema

# This prints out the expected Tenant schema name
puts "import_new_names, tenant is: #{Apartment::Tenant.current}"

user = User.new
user.email = "foo@bar.com"
user.first_name = "foo"
user.save!

user.cases << @case
```

Later in the console I see that while `@case` lives in the mentioned Tenant schema, both the `User` and `CasesUser` join table model both got written to the public schema, even though in the line just above my puts statement confirmed I was looking at the right schema.

How do I get these to write to the correct schema? My only thought would be maybe there's some indexes acting up? I have these two indexes in my `schema.rb`:
```
  add_index "cases_users", ["case_id"], name: "index_cases_users_on_case_id", using: :btree
  add_index "cases_users", ["user_id"], name: "index_cases_users_on_user_id", using: :btree
```

Another guess might be some issue with using the "apartment-sidekiq" gem. In some cases it can auto-detect the Tenant, but in this case it's not possible so I'm passing the `Account` model id along with the `Case` id to start this sidekiq job.

**Comment by mikecmpbll** [comment]
what switching strategy do you use? (do you have use_schemas = true ?)

**Comment by glennfu** [comment]
I have not changed it from the default, which is listed as true, so it's `true`

**Comment by mikecmpbll** [comment]
is User an excluded model?

i can't see what could be causing this. the apartment-sidekiq gem's pretty basic, there's not a lot that can go wrong there .. hm.

**Comment by glennfu** [comment]
Nope, it's not excluded:
```
config.excluded_models = %w{ Account }
config.tenant_names = lambda { Account.pluck :schema }
config.tld_length = 2
```

That's all that's in my config block.

**Comment by glennfu** [comment]
I tried removing "apartment-sidekiq" but there was no change there. Now I'm trying to re-do the database:
```
rake db:drop db:create db:migrate
```
Then I get the warning about new tenants. Then I seed to add the first Account
```
rake db:seed
Seeding n4_test tenant
One of the following schema(s) is invalid: "n4_test" "public"

rake db:migrate
Migrating n4_test tenant
One of the following schema(s) is invalid: "n4_test" "public"

rake apartment:create
Migrating n4_test tenant
One of the following schema(s) is invalid: "n4_test" "public"
Creating n4_test tenant

rake db:migrate
Migrating n4_test tenant
```

Then I redid all my stuff... output looks just like I describe above. However THIS time, while the User is available in both "public" and "n4_test" schemas, the CasesUser join model is in the "n4_test" schema and not the "public" one. The Case is only in the "n4_test" schema.

Is `Apartment::Tenant.switch!` asynchronous perhaps? Is there a chance that it's not actually ready in time for me to be inserting records later?

**Comment by mikecmpbll** [comment]
the user gets saved to both schemas? if that's happening then it may take someone with better pg understanding than me to unpick that, as i don't know how that can happen.

nothing async about `switch!`, it just modifies the schema_search_path on the connection.

**Comment by glennfu** [comment]
I just went into a console, where I'd been in the "n4_test" schema for a few minutes. I did `u = User.create; Apartment::Tenant.switch! "public"; u = User.find u.id` and it indeed loads the record fully in both schemas. If I create it in "public" or create it in "n4_test" it doesn't matter, it's accessible everywhere. So it's like Apartment is excluding the User model entirely even though Account is the only model I have listed to be excluded.

Is there any other way I can debug this?

**Comment by mikecmpbll** [comment]
is there any inheritance shared between User and Account? like STI or something?

check `User.table_name` in your console, apartment handles excluded models for pg by fully addressing the public schema in queries on those models (by prepending it to the table name).

**Comment by glennfu** [comment]
No I don't think there's any real connection there. There's not even associations between them set up in Rails. `User.table_name` shows "users" no matter which Tenant is active.

Here's the full schema.rb: https://gist.github.com/glennfu/995dce85c027b64067d5c88b6e5905dc

**Comment by mikecmpbll** [comment]
check `User.connection.schema_search_path` compared to a model which is working as expected? hit me up on #rubyonrails if you want, easier to discuss there; same username.

**Comment by glennfu** [comment]
Thanks to a nice chat with @mikecmpbll in #rubyonrails, we tracked down the issue to a `establish_connection` call happening in the affected model. In this instance, I was able to simply remove the call and do without it.
