### ISSUE TITLE
load_missing_constant': Unable to autoload constant apartment

### ISSUE THREAD

**Issue by essaebrahem** [influitive/apartment#355]
c:\simple_cms>rails s
DL is deprecated, please use Fiddle
=> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/active_support/d
ependencies.rb:495:in `load_missing_constant': Unable to autoload constant Admin
_user, expected c:/simple_cms/app/models/admin_user.rb to define it (LoadError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/dependencies.rb:184:in `const_missing'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/inflector/methods.rb:261:in `const_get'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/inflector/methods.rb:261:in `block in constantize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/inflector/methods.rb:259:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/inflector/methods.rb:259:in `inject'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/inflector/methods.rb:259:in `constantize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/core_ext/string/inflections.rb:66:in `constantize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/apartment-1.2.0/lib/apartme
nt/adapters/mysql2_adapter.rb:58:in `process_excluded_model'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/apartment-1.2.0/lib/apartme
nt/adapters/abstract_adapter.rb:136:in `block in process_excluded_models'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/apartment-1.2.0/lib/apartme
nt/adapters/abstract_adapter.rb:135:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/apartment-1.2.0/lib/apartme
nt/adapters/abstract_adapter.rb:135:in `process_excluded_models'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/apartment-1.2.0/lib/apartme
nt/tenant.rb:19:in `init'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/apartment-1.2.0/lib/apartme
nt/railtie.rb:31:in `block in <class:Railtie>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:446:in `instance_exec'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:446:in `block in make_lambda'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:192:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:192:in `block in simple'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:504:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:504:in `block in call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:504:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:504:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:92:in `__run_callbacks__'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:778:in `_run_prepare_callbacks'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activesupport-4.2.4/lib/act
ive_support/callbacks.rb:81:in `run_callbacks'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.4/lib/action
_dispatch/middleware/reloader.rb:83:in `prepare!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.4/lib/action
_dispatch/middleware/reloader.rb:55:in `prepare!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/ap
plication/finisher.rb:50:in `block in <module:Finisher>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/in
itializable.rb:30:in `instance_exec'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/in
itializable.rb:30:in `run'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/in
itializable.rb:55:in `block in run_initializers'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'

        from C:/Ruby200-x64/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in
each_strongly_connected_component'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connec
ted_component_from'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strong
ly_connected_component'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tsort.rb:180:in `each'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connec
ted_component'
        from C:/Ruby200-x64/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/in
itializable.rb:54:in `run_initializers'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/ap
plication.rb:352:in `initialize!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/ra
iltie.rb:194:in `public_send'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/ra
iltie.rb:194:in `method_missing'
        from c:/simple_cms/config/environment.rb:5:in `<top (required)>'
        from c:/simple_cms/config.ru:3:in `require'
        from c:/simple_cms/config.ru:3:in `block in <main>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder
.rb:55:in `instance_eval'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder
.rb:55:in `initialize'
        from c:/simple_cms/config.ru:in `new'
        from c:/simple_cms/config.ru:in `<main>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder
.rb:49:in `eval'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder
.rb:49:in `new_from_string'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder
.rb:40:in `parse_file'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/server.
rb:299:in `build_app_and_options_from_config'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/server.
rb:208:in `app'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands/server.rb:61:in `app'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/server.
rb:336:in `wrapped_app'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands/server.rb:139:in `log_to_stdout'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands/server.rb:78:in `start'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands/commands_tasks.rb:80:in `block in server'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands/commands_tasks.rb:75:in `tap'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands/commands_tasks.rb:75:in `server'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands/commands_tasks.rb:39:in `run_command!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.4/lib/rails/co
mmands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by essaebrahem** [comment]
this is my apartment 
# You can have Apartment route to the appropriate Tenant by adding some Rack middleware.
# Apartment can support many different "Elevators" that can take care of this routing to your data.
# Require whichever Elevator you're using below or none if you have a custom one.
#
# require 'apartment/elevators/generic'
# require 'apartment/elevators/domain'
require 'apartment/elevators/subdomain'
# require 'apartment/elevators/first_subdomain'

#
# Apartment Configuration
#
Apartment.configure do |config|

  # Add any models that you do not want to be multi-tenanted, but remain in the global (public) namespace.
  # A typical example would be a Customer or Tenant model that stores each Tenant's information.
  #
   config.excluded_models = %w{ Admin_user }

  # In order to migrate all of your Tenants you need to provide a list of Tenant names to Apartment.
  # You can make this dynamic by providing a Proc object to be called on migrations.
  # This object should yield either:
  # - an array of strings representing each Tenant name.
  # - a hash which keys are tenant names, and values custom db config (must contain all key/values required in database.yml)
  #
  # config.tenant_names = lambda{ Customer.pluck(:tenant_name) }
  # config.tenant_names = ['tenant1', 'tenant2']
  # config.tenant_names = {
  #   'tenant1' => {
  #     adapter: 'postgresql',
  #     host: 'some_server',
  #     port: 5555,
  #     database: 'postgres' # this is not the name of the tenant's db
  #                          # but the name of the database to connect to before creating the tenant's db
  #                          # mandatory in postgresql
  #   },
  #   'tenant2' => {
  #     adapter:  'postgresql',
  #     database: 'postgres' # this is not the name of the tenant's db
  #                          # but the name of the database to connect to before creating the tenant's db
  #                          # mandatory in postgresql
  #   }
  # }
  # config.tenant_names = lambda do
  #   Tenant.all.each_with_object({}) do |tenant, hash|
  #     hash[tenant.name] = tenant.db_configuration
  #   end
  # end
  #
  config.tenant_names = lambda { Admin_user.pluck :subdomain }

  #
  # ==> PostgreSQL only options

  # Specifies whether to use PostgreSQL schemas or create a new database per Tenant.
  # The default behaviour is true.
  #
  # config.use_schemas = true

  # Apartment can be forced to use raw SQL dumps instead of schema.rb for creating new schemas.
  # Use this when you are using some extra features in PostgreSQL that can't be respresented in
  # schema.rb, like materialized views etc. (only applies with use_schemas set to true).
  # (Note: this option doesn't use db/structure.sql, it creates SQL dump by executing pg_dump)
  #
  # config.use_sql = false

  # There are cases where you might want some schemas to always be in your search_path
  # e.g when using a PostgreSQL extension like hstore.
  # Any schemas added here will be available along with your selected Tenant.
  #
  # config.persistent_schemas = %w{ hstore }

  # <== PostgreSQL only options
  #

  # By default, and only when not using PostgreSQL schemas, Apartment will prepend the environment
  # to the tenant name to ensure there is no conflict between your environments.
  # This is mainly for the benefit of your development and test environments.
  # Uncomment the line below if you want to disable this behaviour in production.
  #
  # config.prepend_environment = !Rails.env.production?
end

# Setup a custom Tenant switching middleware. The Proc should return the name of the Tenant that
# you want to switch to.
# Rails.application.config.middleware.use 'Apartment::Elevators::Generic', lambda { |request|
#   request.host.split('.').first
# }

# Rails.application.config.middleware.use 'Apartment::Elevators::Domain'
Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain'
# Rails.application.config.middleware.use 'Apartment::Elevators::FirstSubdomain'

**Comment by mikecmpbll** [comment]
in your apartment config you have:

```ruby
config.excluded_models = %w{ Admin_user }
```

Apartment looks for a model called Admin_user, it's failing to find this, so correct the model name :).

**Comment by essaebrahem** [comment]
The model name exist in models folder with name admin_user

**Comment by mikecmpbll** [comment]
that sounds like the file name? the class name is likely AdminUser?

**Comment by essaebrahem** [comment]
yes the file name is admin_user but the class name is AdminUser 
what is the issue here

**Comment by mikecmpbll** [comment]
the issue is that you're not supplying the correct class name to `config.excluded_models`.

`Admin_user` is not the same as `AdminUser`.

**Comment by essaebrahem** [comment]
thanks a lot for you help that worked for me

**Comment by essaebrahem** [comment]
That nice thank you for your help that really class name is wrong

**Comment by essaebrahem** [comment]
Where can I find the new created connection string. That created for service the new sub domain or the new tenant?

**Comment by essaebrahem** [comment]
That nice thank you for your help that really class name is wrong
