### ISSUE TITLE
Using mysql with with_multi_server_setup option

### ISSUE THREAD

**Issue by fernandomm** [influitive/apartment#356]
I'm using version 1.2.0 of this gem and trying to use a multi server setup.

My tenant_names config looks like this:

```
  config.tenant_names = {
    'my_database_development' => {
      adapter: 'mysql2',
      host: '127.0.0.1',
      port: 3306,
    },
    'my_database' => {
      adapter: 'mysql2',
      host: '192.168.1.2',
      port: 32771,
    }
  }
```

When i run db:migrate, for example, i get this error:

```
Error while connecting to tenant my_database: Mysql2::Error: Unknown database 'my_database': use `my_database`
```

Looks like it's not trying to connect to another server since my_database doesn't exists in the local server, but exists in 192.168.1.2.

Is mysql supported for multi server setup or am I doing something wrong?

**Comment by mikecmpbll** [comment]
most likley to do with the config option introduced recently to fix some Rails 5 issues, but not documented:

```ruby
config.with_multi_server_setup = true
```

https://github.com/influitive/apartment/pull/328

try with that and let us know how you get on.

**Comment by fernandomm** [comment]
I forgot to mention but I have config.with_multi_server_setup = true in my apartment config. It doesn't work even with this option.

**Comment by mikecmpbll** [comment]
ah, i should've read the error message properly. it's trying to use `use` which means that you're using the 'schema' style mysql adapter, the multi server stuff will only work with the connection based adapter, so you'll have to set:

```ruby
config.use_schemas = false
```

sorry the docs suck hard on this bit at the moment, it's still pretty experimental. i'll make a PR for the docs soon and some of the implementation will be tidied up soon also.

**Comment by fernandomm** [comment]
Thank you!

I thought that use_schemas was a postgres only option but with it, it's working fine.
