### ISSUE TITLE
 to define Apartment (LoadError)

### ISSUE THREAD

**Issue by essaebrahem** [influitive/apartment#357]
ruby script/server
=> Booting WEBrick
=> Rails 2.3.5 application starting on http://0.0.0.0:3000
/usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:119:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:426:in `load_missing_constant': Expected /home/ruby/Desktop/fedena/vendor/plugins/apartment/lib/apartment.rb`load_missing_constant': Expected /home/ruby/Desktop/fedena/vendor/plugins/apartment/lib/apartment.rb to define Apartment (LoadError)
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in `const_missing'
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:92:in`const_missing'
        from /home/ruby/Desktop/fedena/config/initializers/apartment.rb:13
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load_without_new_constant_marking'
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load'
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:622:in `load_application_initializers'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:621:in`each'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:621:in `load_application_initializers'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:176:in`process'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `send'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in`run'
        from /home/ruby/Desktop/fedena/config/environment.rb:6
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
        from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
        from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in`gem_original_require'
        from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
        from script/server:3

**Comment by caironoleto** [comment]
I don't know if apartment supports Rails 2.3.5. Did you try to update your application to a newer Rails version?
