### ISSUE TITLE
Where do I look if Apartment is trying to run a migration on the database.yml schema?

### ISSUE THREAD

**Issue by HuckyDucky** [influitive/apartment#358]
Every other aspect seems to be working fine, but migrations are not working at all. Rather than honor my `config.tenant_names` setting, it's being ignored. It's trying to run a migration on the database that is set in my `database.yml` file.

I've used this gem successfully for a long time, not sure why I'm having an issue now.

**Comment by mikecmpbll** [comment]
could be spring. i can't remember precisely what the cause is but i remember issues with spring, so instead of `bin/rake db:migrate` i always have to use `bundle exec rake db:migrate`.
