### ISSUE TITLE
apartment multi tenancy with ruby 1.8.7

### ISSUE THREAD

**Issue by essaebrahem** [influitive/apartment#359]
iam using app with ruby 1.8.7 and rails 3.1.0 
when i run rake db:migrate i get this error message
rake aborted!
no such file to load -- apartment/elevators/subdomain

(See full trace by running task with --trace)
root@ruby-virtual-machine:~/fedena-v2.3-bundle-linux# rake db:migrate --trace
Invalid gemspec in [/usr/lib/ruby/gems/1.8/specifications/activemodel-3.2.0.gemspec]: Illformed requirement ["#YAML::Syck::DefaultKey:0x7f47561e4818 3.2.0"](in /root/fedena-v2.3-bundle-linux)
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
no such file to load -- apartment/elevators/subdomain
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/root/fedena-v2.3-bundle-linux/config/initializers/apartment.rb:7
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.

**Comment by caironoleto** [comment]
Apartment does not support ruby 1.8.7
