### ISSUE TITLE
Performance Impact of Apartment::Database.current

### ISSUE THREAD

**Issue by vanboom** [influitive/apartment#360]
I have a multi-tenant application with a lot of caching.  In order to ensure that cache hits do not occur across tenants, I have been including Apartment::Database.current when computing cache keys.  Database Postgres.

Excessive use of Apartment::Database.current is causing a performance hit as it calls ActiveRecord::Base.connection.current_database.

As of yet, I do not have a suggested solution, but wanted to capture this issue for your consideration. 
Thank you!

**Comment by mikecmpbll** [comment]
i'm not sure i understand at this point where the performance hit is?

**Comment by vanboom** [comment]
Unlike other ActiveRecord SQL calls which are cached, **ActiveRecord::Base.connection.current_database** is not cached, and hits the database server each time it is called. 

In my application, I am caching a LOT of fragments that require uniqueness per-tenant.  This is causing hundreds of calls to Apartment::Database.current which adds up to 700ms and slow page refreshes as the cache keys are computed.

**Comment by mikecmpbll** [comment]
i see. are you using some form of url elevator? if it's fragment caching then you should always have access to the request object and be able to parse out the tenant name from there, as an alternative to `current_database`.

**Comment by vanboom** [comment]
Yes, thanks, I will take a deeper look at it.  We are also calling Apartment::Database.current in the model layer, but I believe the real performance hit is the many cache(...) calls.
