### ISSUE TITLE
Apartment::Tenant.create(schema_id) is extremely slow

### ISSUE THREAD

**Issue by Stratus3D** [influitive/apartment#362]
I've have some unit tests that create multiple accounts (tenants in our app), and then perform some tests. The tests that were creating account records were extremely slow (1 minute each). I used Ruby's Benchmark module to benchmark all the code that was being run, and it was clear that creating the accounts was the slowest operation by far. I drilled down into account creation code and benchmarked our `Apartment::Tenant.create(schema_id)` call. It was taking nearly 5 seconds on average, and since were creating 12 of them these calls nearly made up all of the 1 minute runtime. I haven't had a chance to dig through and benchmark everything this call does, but I can't imagine it should take this long under any circumstances. Is there something oblivious I am missing here?

My environment is:

- Linux <host omitted> 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
- PostgreSQL 9.3.14 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit
- Apartment (1.2.0)
- Rails (4.2.5)
- RSpec (3.5.0)

**Comment by mikecmpbll** [comment]
5 seconds for creating a tenant doesn't seem that odd to me, the time is consumed in creating the schema. feel free to just run `rake db:setup` and see if it takes 5 seconds.

**Comment by Stratus3D** [comment]
@mikecmpbll Thanks for your response. You're right, setting up the schema does take time. 5 seconds isn't unreasonable for a large app.

On the positive side, upgrading to Postgres 9.5 made things significantly faster. The tests that took a minute to run on Postgres 9.3 now run in under 5 seconds! I don't really know why it's running so much faster, and I don't have a lot of time to do more digging. I'm just going stick to 9.5 from now on.
