### ISSUE TITLE
Recently added schemas don't appear in new connections made in new threads

### ISSUE THREAD

**Issue by glennfu** [influitive/apartment#365]
I think this might be somewhat related to #186 as my code shares a similar structure to what's described there.

```
schema = "app"
Apartment::Tenant.create(schema)
Apartment::Tenant.switch!(schema)
puts Apartment::Tenant.current
=> "app"

t = Thread.new do
  ApplicationRecord.connection_pool.with_connection do |conn|
    puts Apartment::Tenant.current
    => "public"
    Apartment::Tenant.switch!(schema)
    => Right here I get "One of the following schema(s) is invalid: "app" "public"
  end
end
t.join
```

If I replace that lower `.switch!` call with `Apartment::Tenant.create(schema)` I get an error saying that schema already exists. I would expect that since it existed and connected before, that opening a new Thread after this the schema would still be accessible. Any idea what I can do to work around this?

**Comment by glennfu** [comment]
A bit more debugging:

```
ActiveRecord::Base.connection.select_all("SELECT * from pg_namespace").rows.length
=> 7
Apartment::Tenant.create("my_new_schema")
ActiveRecord::Base.connection.select_all("SELECT * from pg_namespace").rows.length
=> 8
t = Thread.new do
  ActiveRecord::Base.connection.select_all("SELECT * from pg_namespace").rows.length
  => 7
end
t.join
```

I've been trying a million things around in here to see if anything makes a different but the command inside the new thread never sees the existence of the recently created postgres schema.

**Comment by glennfu** [comment]
I think a workaround to this situation is to say that if you need to add new schemas, and you need them to appear in new threads, you should restart your stack. Then hopefully it's sticky across everything.

**Comment by glennfu** [comment]
Adding `ActiveRecord::Base.clear_active_connections!` just before I call `Thread.new` seems to have fixed my issue.

I'm going to call this one fixed.

**Comment by mikecmpbll** [comment]
this is odd? i assume what's happening with `clear_active_connections!` is that it's putting the current connection back in to the pool and the new thread is checking out that same connection. (could confirm by looking at `ActiveRecord::Base.connection.object_id` before and inside thread).

i'm unsure why the new thread connection gets a different result though—i assume it's some kind of query/schema cache? maybe try `ActiveRecord::Base.connection.schema_cache.clear!` or `ActiveRecord::Base.connection.query_cache.clear` inside the new thead, instead of `clear_active_connections!`.

**Comment by glennfu** [comment]
I tried both of these calls just before the thread, just inside the top of the new thread, and anywhere else I could think to throw it, but none of them fixed the issue. Thanks for the ideas though!

**Comment by glennfu** [comment]
Also I checked the `object_id` of `ActiveRecord::Base.connection` and also `conn` inside the `with_connection` block and confirmed their the same so I think your hunch about `clear_active_connections!` releasing it back for use in the new Thread is correct.

Now how can I get a new Thread and a new connection to recognize the new schema?

**Comment by mikecmpbll** [comment]
no clue, maybe pg is caching it per connection. should be easy enough to test out by connecting via cli or something else, creating a new tenant in rails, then check pg_namespace on cli?

**Comment by glennfu** [comment]
So far I can't seem to reproduce this outside of my specs. Both my rails console and specs are hitting the same postgres install & user. However in my specs I can reproduce this problem 100% of the time. Very strange!
