### ISSUE TITLE
configuring apartment on ruby 1.8.7 

### ISSUE THREAD

**Issue by essaebrahem** [influitive/apartment#366]
c:\1>bundle exec rails generate apartment:install
## --- ERROR REPORT TEMPLATE ------------------------------------------------------
- What did you do?
  
  I ran the command `C:/Ruby187/bin/bundle exec rails generate apartment:install
  `
- What did you expect to happen?
  
  I expected Bundler to...
- What happened instead?
  
  Instead, what actually happened was...

Error details

```
NoMethodError: undefined method `start_with?' for nil:NilClass
  C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:7
```

9:in `ruby_shebang?'
      C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in`any?'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:7
9:in `each'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:7
9:in`any?'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:7
9:in `ruby_shebang?'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:2
4:in`run'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in
 `exec'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/vendor/thor/l
ib/thor/command.rb:27:in`**send**'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/vendor/thor/l
ib/thor/command.rb:27:in `run'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/vendor/thor/l
ib/thor/invocation.rb:126:in`invoke_command'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/vendor/thor/l
ib/thor.rb:359:in `dispatch'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/vendor/thor/l
ib/thor/base.rb:440:in`start'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in
`start'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/exe/bundle:27
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/lib/bundler/friendly_erro
rs.rb:98:in`with_friendly_errors'
      C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/exe/bundle:19
      C:/Ruby187/bin/bundle:23:in `load'
      C:/Ruby187/bin/bundle:23

Environment

  Bundler   1.12.5
  Rubygems  1.4.2
  Ruby      1.8.7 (2013-06-27 patchlevel 374) [i386-mingw32]
  Git       not installed

```
  Bundler settings
```

  disable_shared_gems
    Set for your local app (c:/1/.bundle/config): "true"
  path
    Set for your local app (c:/1/.bundle/config): "vendor/bundle"
  bin_path
    Set via BUNDLE_BIN_PATH: "C:/Ruby187/lib/ruby/gems/1.8/gems/bundler-1.12.5/e
xe/bundle"
  gemfile
    Set via BUNDLE_GEMFILE: "c:/1/Gemfile"
## --- TEMPLATE END ---------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this err
or:
https://github.com/bundler/bundler/search?q=undefined+method+%60start_with%3F%27
+for+nil%3ANilClass&type=Issues

If there aren't any reports for this error yet, please create copy and paste the
 report template above into a new issue. Don't forget to anonymize any private d
ata! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

c:\1>

**Comment by mikecmpbll** [comment]
pretty sure we're not supporting ruby 1.8.7, i'm afraid. it's a very old version of Ruby, and no recent versions of Rails support it.

**Comment by essaebrahem** [comment]
thanks for reply
i want to make my application to work with subdomain like malak.example.com and malak is the name of the database my application will coonect  
have i use apartment to do this ?
i appreciate your help

**Comment by mikecmpbll** [comment]
yes, you can do this with apartment but not using ruby 1.8.7, to my knowledge. if you have any further questions best to head to `#apartment` on [freenode](https://webchat.freenode.net/?channels=%23apartment), i'll be happy to help.

**Comment by essaebrahem** [comment]
are there article describe how  to do that manually without apartment  plugin in ruby 1.8.7

**Comment by bradrobertson** [comment]
We don't provide information about how to do multi-tenancy *without* using the Apartment gem no, that would be far beyond the scope of this project.
