### ISSUE TITLE
Managing multi-tenants migration error

### ISSUE THREAD

**Issue by emmanuelrdl** [influitive/apartment#369]
Hello,

I am not sure that is an issue but I have noticed that **if a migration fail for one tenant the tenants migrated before the  error will be migrated and the schema version will be updated for those ones. However as expected the failed migration raise an error and the current tenant and the next tenants won't be migrated and the schema version won't be updated for those.**

Let's say I have 10 tenants: T1..T10
If an error occur when migrating T5
T1..T4 will be migrated
T5..T10 won't be migrated

When trying to rollback the migration it will naturally fail since half of tenants have already been migrated and half haven't been migrated.

Did I miss something ? / Do you have any idea on how to solve this problem?

Thanks

**Comment by mikecmpbll** [comment]
you specify the tenants you want to run the db rake tasks on using the `DB` environment variable (see https://github.com/influitive/apartment/blob/development/lib/tasks/apartment.rake#L109-L111).

using this you can roll back just the migrated tenants, or migrate just the unmigrated tenants, etc.

**Comment by emmanuelrdl** [comment]
Thanks for your help!
