### ISSUE TITLE
current_tenant resets to 'public' after failed devise login

### ISSUE THREAD

**Issue by favour121** [influitive/apartment#372]
After a failed login, devise "redirects" to the login page (Users::SessionsController#new) and the value of Apartment::Tenant.current which was previously set in a TenantElevator middleware goes back to its default value of "public".

I SUSPECT this is happening because Devise isn't exactly redirecting to the login page (Failure App) but actually calling it in a new rack app and returning its response. The new rack app doesn't call the TenantElevator middleware so the tenant isn't set within the rack app.

**Comment by fmh** [comment]
same issue #368

**Comment by mikecmpbll** [comment]
https://github.com/influitive/apartment#middleware-considerations

**Comment by fmh** [comment]
@mikecmpbll : this has no effect :(
