### ISSUE TITLE
What's the right way to add Tenants in Postgres schemas?

### ISSUE THREAD

**Issue by glennfu** [influitive/apartment#374]
In my app, I had a few tenants. I went to add a new one with `Apartment::Tenant.create(schema)`. Then, upon the next deploy of my app, `rake db:migrate` failed with: `ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "users" already exists` as it was trying to run migrations within the new tenant.

I had to go back into the console, use `Apartment::Tenant.drop(schema)`, and then I tried running `rake db:migrate` but that wasn't enough. I had to run `rake apartment:create` to get the schema properly loaded and migrated.

In my opinion, the README doesn't make clear that this is the way things should be handled, but it's the only thing I've found to work. Is there something that I'm missing?

**Comment by mikecmpbll** [comment]
`rake apartment:create` simply calls `Apartment::Tenant.create` for all the tenants (`Apartment.tenant_names`) in a loop.

I'm not sure why it was trying to recreate the users table on migration, perhaps create a new tenant then check the schema_migrations table and check if that users table migration ID is in there.

**Comment by glennfu** [comment]
I just added a new tenant model entry and tried to run `rake apartment:create` directly after and got this:

```
Migrating admin tenant
Migrating assets tenant
Migrating foo tenant
Migrating new_tenant tenant
One of the following schema(s) is invalid: "new_tenant" "public"
** Execute apartment:create
Creating admin tenant
rake aborted!
NoMethodError: undefined method `quietly' for main:Object
/usr/local/bundle/gems/apartment-1.2.0/lib/tasks/apartment.rake:10:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/apartment-1.2.0/lib/tasks/apartment.rake:7:in `each'
/usr/local/bundle/gems/apartment-1.2.0/lib/tasks/apartment.rake:7:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
```

**Comment by glennfu** [comment]
I think I've got it almost figured out. The app calling `Apartment::Tenant.create` does not actually contain the migrations, so `ActiveRecord::Migrator.get_all_versions` doesn't show them. Is there a way I can later, from the app that DOES contain migrations, reset that? I'm looking at this code in postgresql_adapter.rb:

```
      def import_database_schema
        clone_pg_schema
        copy_schema_migrations
      end
```

However this is for `PostgresqlSchemaFromSqlAdapter`, but I'm not using that I'm just using `PostgresqlSchemaAdapter` so I'm not sure what my options are here.

**Comment by glennfu** [comment]
I just wrote this method for myself to help out, and it seems to do the trick:
```
  def connect_and_sync_migrations
    current_migrations = ActiveRecord::Migrator.get_all_versions
    Apartment::Tenant.create(schema)
    @account.connect
    current_migrations.each do |migration|
      ApplicationRecord.connection.execute("INSERT INTO schema_migrations (version) VALUES(#{migration})") rescue nil
    end
  end
```

From doing this the question popped into my head: "Why is the SchemaMigrations table even segmented by tenant?" Is there a way to make SchemaMigrations act like an "excluded_mode" model in the configuration? Or is there a reason why it has to behave this way?

**Comment by mikecmpbll** [comment]
the reason each tenant has schema_migrations is so that rails can know what state of migration each tenant is in .. this is how the entire migrations process works ;).

**Comment by glennfu** [comment]
I get that's how it works now, I'm just wondering if it HAS to, or if it's BEST that way. Like it's not inherently clear to me why it should even be possible that migrations be out of sync between clients. If there's no way around it, that's fine!

Do you have any comments on that block of code I dropped there? Is there a cleaner or safer way to update my `schema_migrations` table than what I'm doing here?

**Comment by mikecmpbll** [comment]
no probs. i don't know if it's the best way, but i can't think of a better way.

i didn't fully understand your situation with the migrations to be honest, sounds like you have multiple apps using the same database and one app has all the migrations, is that right? obvious first thought is why aren't you creating the tenant from the app with the migrations?

**Comment by glennfu** [comment]
The situation I'm in is that we have a larger app doing the bulk of the work, including migrations. We have another app, which has access to the same Postgres db, but does a lot less work, and is more of a front-end piece. So for the sake of avoiding as much duplication as possible, it has the same schema but not the migrations. So an admin would go into this front-end and work with the form to create a new Tenant, whereas the other larger app (with the migrations) doesn't have an actual front-end.

**Comment by mikecmpbll** [comment]
ah i see. well it's quite an unusual set up so i guess anyway which works for you, is all good :+1:

**Comment by glennfu** [comment]
I guess so! Thanks for your help :)
