### ISSUE TITLE
Seed default data when tenant its build

### ISSUE THREAD

**Issue by Frank004** [influitive/apartment#379]
So I'm looking for a way to seed and populate some per tenant model when the subdomain is build. What options do I have, any samples or ideas. thank you.

For creating the tenant I'm using a callback on the Company model

```
 after_create :create_tenant 
 after_destroy :destroy_tenant
```

**Comment by Frank004** [comment]
I found this in SO I like to know if is a valid way of seed the data to the tenant
http://stackoverflow.com/a/27343169/2837866

Another solution was building a service object to seed the data when the tenant is create.

**Comment by brunowego** [comment]
I had the same doubt and for me that was the best solution I found.
