### ISSUE TITLE
Do we need to add subdomains in /etc/hosts ?

### ISSUE THREAD

**Issue by bkotu6717** [influitive/apartment#380]
Hi, I have a very basic doubt. I have seen the Gorails apartment gem tutorial before I actually start using apartment gem in my app. The GORAILS tutorial did not say anything about adding sub domains in /etc/hosts, but without adding an entry in /etc/hosts I am not able to see my app running for particular subdomain. Please explain me if I  need to entry in hosts file or aprtment gem will take care of it?

**Comment by mikecmpbll** [comment]
apartment doesn't do anything with your hosts file. it has nothing specific to do with (sub)domains at all except it throws in a subdomain elevator for you as that's quite a common use.

if you wish to use subdomains during development/test, that's up to you how you do that. (pow, lvh.me, hosts file, or just don't include the subdomain elevator middleware in dev/test.)

**Comment by bkotu6717** [comment]
@mikecmpbll  I have 2 subdomains created subdomain1 and subdoamin2, My 127.0.0.1 is mapped to example.com . But when I tried subdomain1.example.com or subdomain2.example.com, I could not see any rails server receiving request. This means the SubDomain middleware is not identifying the subdomain from the URL. Please let me know if I am missing somewthing. you can find the repo at https://github.com/bkotu6717/gem-apartment

**Comment by mikecmpbll** [comment]
if it's not hitting the server then the problem is nothing to do with rails or the middleware, it's to do with your domain configuration. sorry but good luck!

**Comment by railsfactory-bhaskararao** [comment]
@mikecmpbll as you said apartment gem nothing to do with hosts file. I got apartment gem working with my app and able to see multiple domains working without /etc/hosts config.

**Comment by codeperl** [comment]
@railsfactory-bhaskararao 
Hi, Can you please share how did you do so for wildcard subdomain with apartment gem? I am facing issue with docker, seems same as you.

**Comment by railsfactory-bhaskararao** [comment]
@codeperl I did not use wildcard subdomains.
