### ISSUE TITLE
InvalidForeignKey Apartment Gem when creating records

### ISSUE THREAD

**Issue by muaaz-vf** [influitive/apartment#382]
I have excluded user model in apartment initializer file.

`config.excluded_models = %w{Franchise User Franchiser}`

I have a ternary model between project and user but when i add members it throughs beneath error.

`ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  insert or update on table "members" violates foreign key constraint "fk_rails_2e88fb7ce9"
DETAIL:  Key (user_id)=(6) is not present in table "users".
: INSERT INTO "members" ("user_id", "project_id", "created_at", "updated_at", "email") VALUES ($1, $2, $3, $4, $5) RETURNING "id"):`

**Comment by caironoleto** [comment]
Excluded models use the public schema, so, your FKs should be between your public schema and tenant schema. Also, Postgres supports FKs among schemas.

**Comment by Bongs** [comment]
How can I achieve this? What changes do I need to make?

I've following models:
1. State - which is in "public" schema
    This table has columns - id, name, code
2. Party - which is in tenant's schema
    This table has columns - id, name, state_id, type

The models are:
```
# app/models/state.rb
class State < ApplicationRecord
  has_many :parties
end

# app/models/state.rb
class Party < ApplicationRecord
  belongs_to :state
end
```

Migration files are:
```
# xxxx_create_states.rb
create_table :states do |t|
  t.string :name
  t.string :code, limit: 2
end

# xxxx_create_parties.rb
create_table :parties do |t|
  t.string :name
  t.references :state, foreign_key: true
  t.string :type
  t.timestamps
end
```

I've states records created in "public" schema. When I try to create "party" record in tenant schema I get error:
```
2.4.0 :016 > Party.create!({name: 'Vendor Party 1', state_id: 1, type: 'Vendor'})
   (0.2ms)  BEGIN
  State Load (0.2ms)  SELECT  "public"."states".* FROM "public"."states" WHERE "public"."states"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SQL (9.3ms)  INSERT INTO "parties" ("name", "state_id", "type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "Vendor Party 1"], ["state_id", 1], ["type", "Vendor"], ["created_at", 2017-04-02 06:51:38 UTC], ["updated_at", 2017-04-02 06:51:38 UTC]]
   (0.1ms)  ROLLBACK
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table "parties" violates foreign key constraint "fk_rails_6a79a75ee2"
DETAIL:  Key (state_id)=(1) is not present in table "states".
```

**Comment by SimonDKnight** [comment]
Remove foreign_key: true from the migration file

**Comment by hmtanbir** [comment]
> Remove foreign_key: true from the migration file.
> 
> So it would be t.integer, :state_id

Lovely solution.
