### ISSUE TITLE
Spree add admin user in apartment gem tenant

### ISSUE THREAD

**Issue by nwoow** [influitive/apartment#383]
Hey I have installed a spree and on top of that have created a tenant using apartment gem each tenant has different db in mysql. I can access a general login area but How can I create an admin user in my case. And which table I need to edit to make normal user admin. Thanks for reply

**Comment by JorgeDDW** [comment]
I would like the answer of this too.

**Comment by mikecmpbll** [comment]
> How can I create an admin user in my case.

no idea, that's entirely dependent on your user code, nothing to do with apartment

> And which table I need to edit to make normal user admin.

again, doesn't appear to have anything to do with apartment.

**Comment by JorgeDDW** [comment]
Thinking on it.
Apartment create the same schema of Spree on the tenants so if you want to access the admin of Spree of that particular tenant you just need tenant.example.com/admin
