### ISSUE TITLE
Redirect to root if not tenant found

### ISSUE THREAD

**Issue by Frank004** [influitive/apartment#384]
Is there's a way to grab the exception and  reset to the public tenant and redirecte_to root?

**Comment by mikecmpbll** [comment]
of course, just do exactly what you said. you didn't explain how you're currently switching tenant so it's difficult to advise.

if you're switching tenant per request just write your own middleware to do the switching and to handle non-existent tenants. feel free to look at the provided middleware [examples](https://github.com/influitive/apartment/tree/development/lib/apartment/elevators) for inspiration.

**Comment by Frank004** [comment]
@mikecmpbll  Im using subdomain with a Company model.

```
apartment.rb
require 'rescued_apartment_middleware'
Rails.application.config.middleware.use 'RescuedApartmentMiddleware'
```
```
/lib/rescued_apartment_middleware.rb
class RescuedApartmentMiddleware < ::Apartment::Elevators::Subdomain
  def call(env)
    super
  rescue Apartment::TenantNotFound
    Rails.logger.error "ERROR: Apartment Tenant}"
    Apartment::Tenant.reset
    redirect_to root_path
  end
end

```
I try this but can't get the middleware rescue to run and still get the error no tenant display.

**Comment by caironoleto** [comment]
@Frank004 You can do this with a `rescue_from` in your `ApplicationController`. Something like this:

```ruby
class ApplicationController < ActionController::Base
  rescue_from Apartment::TenantNotFound, with: :redirect_to_root_path

  protected

  def redirect_to_root_path
    Rails.logger.error "ERROR: Apartment Tenant"
    Apartment::Tenant.reset
    redirect_to root_path
  end
end
```

**Comment by Frank004** [comment]
@caironoleto Try it but still get the error page and didn't redirect it to the root path.

**Comment by caironoleto** [comment]
@Frank004 try the `rescue_from` with default subdomain elevator:

```ruby
module MyApplication
  class Application < Rails::Application
    config.middleware.use 'Apartment::Elevators::Subdomain'
  end
end
```

I think that rails routes are not accessible in your custom middlewares, without loading the rails stuff.

**Comment by Frank004** [comment]
`/lib/rescued_apartment_middleware.rb
`
```
require 'apartment/elevators/subdomain'
require 'apartment/tenant'
 module Apartment
  module Elevators
    class RescuedApartmentMiddleware < Apartment::Elevators::Subdomain
      def call(env)
        begin
          super
        rescue Apartment::TenantNotFound, ActiveRecord::NoDatabaseError
          Apartment::Tenant.reset
          # redirect_to root_path
          Rails.logger.error "Error: Apartment says tenant was not found"
        end
        @app.call(env)
      end
    end
  end
end
```


`apartment.rb`

```
require 'rescued_apartment_middleware'
Rails.application.config.middleware.insert_before ActiveRecord::Migration::CheckPending, Apartment::Elevators::RescuedApartmentMiddleware
```
This catching the exception but cant run redirect to root path.


What I want is to reset to the public tenant and go to the root whet no tenant its found.

**Comment by mikecmpbll** [comment]
@Frank004 Rack middleware should return an array of `[status, headers, body]`. if you want to redirect to '/' you can return:

```ruby
[302, { 'Location' => '/' }, "Tenant not found"]
```

**Comment by davidalejandroaguilar** [comment]
How could I redirect to the root path on the correct (default) subdomain? (e.g. `www`)

Trying to do so with:

```
rescue Apartment::TenantNotFound
  Apartment::Tenant.reset
  return [302, { 'Location' => '/' }, "Tenant not found"]
end
```

I get a `ERROR: Apartment Tenant not found: "public"` error.

Even by getting an existing tenant name with `Apartment.tenant_names` and `switch!`ing to it, I get a `TenantNotFound` error.

**Comment by thabrlawrenz** [comment]
For those also looking for a solution. In summary from all the comments above.

`application.rb`

    config.middleware.use RescuedApartmentMiddleware

`app/middleware/rescued_apartment_middleware.rb`

    require 'apartment/elevators/subdomain'
    require 'apartment/tenant'

    class RescuedApartmentMiddleware < ::Apartment::Elevators::Subdomain

      def call(env)
        super
      rescue Apartment::TenantNotFound, ActiveRecord::NoDatabaseError
        Apartment::Tenant.reset
        Rails.logger.error "Error: Apartment says tenant was not found (#{env['SERVER_NAME']})"
        return [301, { 'Location' => '/404.html' }, ["Tenant not found"]]
      end

    end
