### ISSUE TITLE
Use the correct version of pg_dump

### ISSUE THREAD

**Issue by mrdomino** [influitive/apartment#385]
Currently the use_sql feature just calls out to `pg_dump` on the user's PATH. This does not in general correspond to the PostgreSQL version running on the server, and version mismatches generally result in errors. It seems that as long as the correct client is installed, `/usr/lib/postgresql/$version/bin/pg_dump` is the correct version to use.

**Comment by caironoleto** [comment]
This isn't a responsible of Apartment to deal with Postgres version. See as [Rails](https://github.com/rails/rails/blob/261e94b8ee0246f0c82a782883065160b9ac9896/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L76) deal with the same issue.
