### ISSUE TITLE
How to Create Database Seed with Tenant?

### ISSUE THREAD

**Issue by JorgeDDW** [influitive/apartment#386]
Hi there guys,

Any idea for How to Create Database Seed with Tenant?

Regards,

**Comment by Xosmond** [comment]
Same problem here, i need to seed database selecting an specific tenant

**Comment by mikecmpbll** [comment]
there is a `seed_after_create` config option which you can set to true, e.g.:

```ruby
Apartment.configure do |config|
  config.seed_after_create = true
  # ...
end
```
