### ISSUE TITLE
How to create Proc Object for Migration 

### ISSUE THREAD

**Issue by JorgeDDW** [influitive/apartment#387]
Hi there,
I want to make my migrations more dynamic, I'm new to rails and I'm still learning.
So I want to apply this line, but i know that Customer is not what i most use.

and because of this text 

> In order to migrate all of your tenants (or postgresql schemas) you need to provide a list of dbs to Apartment. You can make this dynamic by providing a Proc object to be called on migrations. This object should yield an array of string representing each tenant name. Example:

I know i must be use a Proc Object, so... How can I do it?

`config.tenant_names = lambda{ Customer.pluck(:tenant_name) }
`

**Comment by mikecmpbll** [comment]
hi @JorgeDDW 

you do it exactly like the last line there. `lambda{ }` is a proc object (lambda's are types of proc). the code in between the `{}` must return an array of tenant names. `Customer.pluck(:tenant_name)` is just an example of a Customer model with a `tenant_name` attribute, but you can write any code here you want.

**Comment by JorgeDDW** [comment]
Thank you @mikecmpbll for your guide!

So this mean if my `Customer` is the model I just have to use `Customer.pluck(:tenant_name)` so the migration migrate all the tenants?

Nothing more?
No other line of code to add?

:-D

**Comment by mikecmpbll** [comment]
what is `Customer.pluck(:tenant_name)` returning?

**Comment by JorgeDDW** [comment]
oh! solve my issue! I needed to edit the `:tenant_name`. 
Now its working :)
