### ISSUE TITLE
Creating Controller not for Tenant

### ISSUE THREAD

**Issue by JorgeDDW** [influitive/apartment#389]
Hi there guys!

So this is my case: I want to create an admin panel to manage all of my tenants and tenants data.
The thing is that if I create a controller or a model, this model is going to be available for every one of the tenants. So How do I avoid this?

**Comment by mikecmpbll** [comment]
not sure what you're asking, controllers have nothing directly to do with tenants or apartment. controllers deal with requests and responses to the application.

**Comment by JorgeDDW** [comment]
my bad @mikecmpbll. I may be referred at the Model. The thing is that I want to create some scaffold's controller, model and view that I don't want that the tenant have in their database and with access on this new things.

**Comment by mikecmpbll** [comment]
all tenant's should have the same tables, including those for shared moels. apartment doesn't presently support anything else.

that doesn't mean those tables have to ever be used though.
