### ISSUE TITLE
Retrieving a list of tenants that have already been created

### ISSUE THREAD

**Issue by mxie** [influitive/apartment#390]
In a few different places, I've used `Apartment.tenant_names` under the assumption that this list is only populated once I've run `Apartment::Tenant.create("foo")`. However, I realized that it's actually just calling (or returning) whatever was specified in the config file. In my case, it was a proc (e.g. `lambda { Company.pluck(:subdomain) }`. Therefore, by calling `tenant_names`, it was really just doing this fetching the subdomains from the database, each of which may or may not have generated schemas already.

Is there any easy way to get a list of ones that have already been migrated/created? If so, it'd be nice to have a method available to return this so that it can be differentiated from `Apartment.tenant_names`.

**Comment by mikecmpbll** [comment]
for most people this is a non-issue as the two would be the same; they wouldn't add a Company record without creating the tenant database/schema.

also, for some scenarios it might be important to have them different, for instance you may wish to remove a tenant from the list without destroying the database/schema.

finally, there's no real practical way Apartment can keep track of tenants or enumerate them on demand in the way that you suggest because it's commonplace to have many db/schemas on a database server that might not be tenants, they could be from other applications, they could be the public db/schema, etc etc.

**Comment by mxie** [comment]
> they wouldn't add a Company record without creating the tenant database/schema.

The problem is that they actually can, and they wouldn't realize that there's a mismatch. There'd be no way to verify if there is a schema for the tenant unless they check in the database directly.

> for some scenarios it might be important to have them different

That's what I'm looking for - something that differentiates the two. Intuitively, I'd expect `tenant_names` to return a list of actual tenants in the system, not a superset that includes potential ones that don't have a schema yet. 

> for instance you may wish to remove a tenant from the list without destroying the database/schema

Sure! But there isn't something that reflects what might still exist in this case then.

All that said though, perhaps it isn't easy to get this list, but I think it's worth noting somewhere in README at the very least. If we can agree on that, I'd be happy to put in a PR for that. I just wanted to make sure I wasn't missing anything.

**Comment by mxie** [comment]
By the way, where I said:

> There'd be no way to verify if there is a schema for the tenant unless they check in the database directly.

This is totally fine. The problem is that that isn't likely to occur to them because most people might be relying on `tenant_names` to be the source of truth.

**Comment by mikecmpbll** [comment]
> > They wouldn't add a Company record without creating the tenant database/schema.
> 
> The problem is that they actually can, and they wouldn't realize that there's a mismatch. There'd be no way to verify if there is a schema for the tenant unless they check in the database directly.

"they" being devs, you mean? sure they can, they can do lots of stuff :D—that's a good thing.

> All that said though, perhaps it isn't easy to get this list, but I think it's worth noting somewhere in README at the very least. If we can agree on that, I'd be happy to put in a PR for that. I just wanted to make sure I wasn't missing anything.

i'm sure PRs to make the docs clearer will be welcomed :) (i'm not a maintainer though!)
