### ISSUE TITLE
Issue with ActionCable

### ISSUE THREAD

**Issue by brunowego** [influitive/apartment#391]
I do not know if apartment has support for ActionCable, I believe have, but when try to connect I need to switch to tenant every websocket request.

Should I have some kind of setup for this to be automatic?

Thanks!

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40938639)](https://www.bountysource.com/issues/40938639-issue-with-actioncable?utm_source=40938639&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by mikecmpbll** [comment]
i don't know much about actioncable yet; presumably you're using a middleware elevator to switch tenants? i guess actioncable doesn't run middleware on each "websocket request"? you probably know more about it than me.

**Comment by brunowego** [comment]
@mikecmpbll thanks for your attention.

Yes, I am using `Apartment::Elevators::FirstSubdomain`. Yes, it seems to be another way, does not run middleware.

I also don't know much about it.

**Comment by brunowego** [comment]
I tried put `Apartment::Tenant.switch! request.subdomains.first` on channels `connection.rb`, but not works. If put "switch" on event method works:

```rb
class ConferenceChannel < ApplicationCable::Channel
  ...
  def cancel
    # FIXME: Need switch tenant automatically!
    Apartment::Tenant.switch! :organization

    Dispute::Conference.find(conference_id).cancel

    ActionCable.server.broadcast "conference:#{conference_id}", nil
  end
  ...
end
```

**Comment by f** [comment]
I simply namespaced channels by adding a simple method to `channel.rb`.

```rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
    def stream_from_tenant(stream_name)
      stream_from "#{stream_name}:#{Apartment::Tenant.current}"
    end
  end
end
```

Seems working to me.

**Comment by brunowego** [comment]
Hi @f, I understand your idea, but seems not working for me, the `Apartment::Tenant.current` return `public`.

**Comment by bradrobertson** [comment]
I've never actually worked with `ActionCable` in any way. @f's solution assumes you've already switched into the appropriate tenant somehow and @brunowego's solution manually does that switching.

I don't personally know if there's a way to do this automatically within ActionCable or if it has any sort of middleware stack that you can hook into.

**Comment by shakycode** [comment]
I'm also in on this thread.  Have a multi-tenant application I'm building and trying to use actioncable with it.  Doesn't seem to work.  Plus there are issues when you go into production with having to change your nginx config.

**Comment by shakycode** [comment]
I will double the bounty on this one, FYI.

**Comment by brunowego** [comment]
This process would be similar to an approach used by gem apartment-sidekiq?

**Comment by excid3** [comment]
Not sure about it running middleware or not, but you have full access to the `request` object inside `connection.rb` so you can manually switch the tenant there as a temporary fix. 

```ruby
# app/channels/application_cable/connection.rb

module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
      tenant = request.subdomain
      Apartment::Tenant.switch!(tenant)
      logger.add_tags "ActionCable", "User #{current_user.id}", "Tenant #{tenant}"
    end

    protected

      def find_verified_user
        if current_user = env['warden'].user
          current_user
        else
          reject_unauthorized_connection
        end
      end
  end
end
```

And don't forget you'll need to use regex to match all subdomains for the ActionCable `allowed_request_origins` option. 

There's probably a way to figure out how to get this automatically done with a middleware when AC is mounted in a route since it goes through Rack in that situation. The original Faye implementation of it was setup using a Rack middleware so the current version of it might have a similar thing.

I'm not sure what happens when you're running a standalone ActionCable server directly on a port instead.

**Comment by shakycode** [comment]
@excid3 thanks for chiming in on this.  I'm going to work this into my implementation.  Thanks for doing some legwork on this issue.

**Comment by shakycode** [comment]
I used @excid3 solution and I still had problems.  So with his help we switched things around to switching the Tenant before looking up the `current_use`r with the `find_verified_user` method.

End result, ActionCable is working with Apartment with the Devise `User` model as part of the Tenant schema.

Thanks @excid3 !

````
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      tenant = request.subdomain
      Apartment::Tenant.switch!(tenant)
      self.current_user = find_verified_user
      logger.add_tags "ActionCable", "User #{current_user.id}", "Tenant #{tenant}"
    end

    protected

      def find_verified_user
        if current_user = env['warden'].user
          current_user
        else
          reject_unauthorized_connection
        end
      end
  end
end
````

**Comment by shakycode** [comment]
I also opened an issue on Rails/Rails to see how we can get the request from connection.rb into one of the channel files [https://github.com/rails/rails/issues/27875](https://github.com/rails/rails/issues/27875)

**Comment by Xosmond** [comment]
Its funny because it took me 1 hour to realize that Apartment was the problem. I should have visited this before u_u.

I did the same that @excid3 wrote and it works. BY THE WAY. If you use ActiveJob, don't forget to pass the tenant name (in my case the subdomain) to switch to it inside the job also.

**Comment by mikecmpbll** [comment]
@shakycode bear with me, i've never used action cable.

lots of the examples show (including yours!) set `current_user` instance variable on the Connection and have `identified_by :current_user`. checking the docs about `identified_by`, they say:

> Note that anything marked as an identifier will automatically create a delegate by the same name on any channel instances created off the connection.

which explains why these examples also show calling `current_user` in the Channel. based on that, it seems like you should be able to do `identified_by :current_user, :tenant` and write `self.tenant = request.subdomain` in your `connect` method. you'll then be able to access the `tenant` via the delegate in your channel instance.

**Comment by shakycode** [comment]
@mikecmpbll Thanks so much for the information.  I'm now able to delegate `tenant` to the channel file using this.  Transmitting on multiple tenants and switching is solved. 👍

**Comment by shakycode** [comment]
@brunowego Should we go ahead and close this issue?  I have a working sample now and AC + Apartment is humming along nicely.

**Comment by brunowego** [comment]
@shakycode can you expose here your solution? Thanks.

**Comment by jhubert** [comment]
@brunowego Seems shakycode has disappeared. Did you manage to solve this in a way other than what's shared above?

**Comment by nunosilva800** [comment]
Solution presented here is ok, but a middleware would be better I think.

In my case, since we're using custom warden `serialize_into_session` and `serialize_from_session`, we needed this:

```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user, :tenant

    def connect
      self.tenant = request.subdomain
      Apartment::Tenant.switch(tenant)!
      self.current_user = find_verified_user
    end

    private

    def find_verified_user
      env['warden'].session_serializer.fetch('user') ||
        reject_unauthorized_connection
    end
  end
end

```

**Comment by ramavilli** [comment]
> Solution presented here is ok, but a middleware would be better I think.
> 
> In my case, since we're using custom warden `serialize_into_session` and `serialize_from_session`, we needed this:
> 
> ```ruby
> module ApplicationCable
>   class Connection < ActionCable::Connection::Base
>     identified_by :current_user, :tenant
> 
>     def connect
>       self.tenant = request.subdomain
>       Apartment::Tenant.switch(tenant)!
>       self.current_user = find_verified_user
>     end
> 
>     private
> 
>     def find_verified_user
>       env['warden'].session_serializer.fetch('user') ||
>         reject_unauthorized_connection
>     end
>   end
> end
> ```

 There was an exception - Apartment::TenantNotFound(One of the following schema(s) is invalid: "" "public" in connect.rb

**Comment by ramavilli** [comment]
Any help friends: https://stackoverflow.com/questions/65387884/action-cable-in-rails-application-with-subdomain-apartment-gem-isnt-working
