### ISSUE TITLE
Switch tenant before create session on devise

### ISSUE THREAD

**Issue by matheusvetor** [influitive/apartment#392]
Hello, i have some tenants and i want to sign in users using devise from different tenants through same url:

```ruby
   Apartment.configure do |config|
     config.tenant_names = ['tenant_dev', 'tenant2_dev']
   end

  # application.rb
  config.tenants =  {
    'dev.tenant.com' => 'tenant_dev',
    'dev.tenant2.com' => 'tenant2_dev',
  }
  config.middleware.use 'Apartment::Elevators::HostHash', config.tenants
```

I want to iterate in to tenants and find the correct tenant with user

```ruby
  # devise session controller => create
  def create
    email = params[resource_name][:email]
    ::Rails.application.config.tenants.each do |host, tenant_name|
      Apartment::Tenant.switch!(tenant_name)
      user = resource_class.find_by(email: email)
      break if user
    end

    super
  end
```

**Comment by mikecmpbll** [comment]
why don't you hold your auth information in a shared model? seems more elegant that way.

**Comment by matheusvetor** [comment]
Is a requisite, the all data must be isolated. In fact, the problem is the
api login endpont consumed by a mobile app, the login must be transparent
to user.

2017-01-17 9:43 GMT-02:00 Mike Campbell <notifications@github.com>:

**Comment by mikecmpbll** [comment]
*shrugs*. there's various other solutions, like having them configure the endpoint in the app, or having an email -> tenant mapping in an excluded model.

as you increase the number of models, this approach will probably suck. so anyway, what's actually the problem? you didn't say what issue you were having.

**Comment by matheusvetor** [comment]
@mikecmpbll, the tenants number will be fixed. When accessing dev.tenant.com, putting a dev.tenant2.com user, the code switch the tenant proper but devise don't listen the tenant switch:

dev.tenant.com + user from tenant_dev => success
dev.tenant.com + user from tenant2_dev => unauthorized

**Comment by mikecmpbll** [comment]
sorry, i don't know enough about devise to help and it doesn't seem this is a problem to do with apartment.

**Comment by cavoixanha** [comment]
You can use
```
Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain',
                                        lambda { |request|
                                           tenant_name = nil

                                           if request.env['rack.session']['warden.user.user.key'] != nil
                                             tenant_name = User.find(request.env['rack.session']['warden.user.user.key'][0][0]).store.subdomain
                                           end
                                           return tenant_name
                                        }
```
and session_store Rails.application.config.session_store :active_record_store, key: '_name_project_session', :domain => ".#{DOMAIN}"
don't use, when I use with devise is errors ( can only me )
```
# Rails.application.config.middleware.insert_before 'Warden::Manager', 'Apartment::Elevators::Subdomain'
```
