### ISSUE TITLE
Point two different subdomain on a single schema

### ISSUE THREAD

**Issue by zohaib-sarwar-confiz** [influitive/apartment#399]
Hi,

I there some way in which we can point xyz-development.example.com and xyz.example.com to a xyz schema.

Thanks

**Comment by mikecmpbll** [comment]
write a [custom elevator](https://github.com/influitive/apartment#custom-elevator).

**Comment by zohaib-sarwar-confiz** [comment]
Hi mikecmpbll,
I have done this in config/initializers/apartment/elevators/generic.rb

    module Apartment
      module Elevators
        #   Provides a rack based tenant switching solution based on request
        #
        class Generic
          def call(env)
            request = Rack::Request.new(env)

            database = @processor.call(request)
            database = extract_env_from_subdomain(database)

            Apartment::Tenant.switch database if database

            @app.call(env)
          end

          def extract_env_from_subdomain(tenant)
            if tenant.include?(Rails.env)
              tenant.split(Rails.env)[0]
            else
              tenant
            end
          end
        end
      end
    end


Which is working for grape a gem based api and also for admin_active based admin Interface. Just wants you to validate my approach.

Thanks

**Comment by mikecmpbll** [comment]
typically you'd subclass `Apartment::Elevators::Generic`, instead of monkeypatching it, as per the readme, but whatever works for you is surely fine :).
