### ISSUE TITLE
bug in rescue from Apartment::TenantExists

### ISSUE THREAD

**Issue by bfcoder** [influitive/apartment#405]
Howdy, when I rescue Apartment::TenantExists in my model, I can't seem to drop that tenant in the rescue.

Ruby 2.3.1
Rails 4.2.7

```ruby
# seeds.rb
attrs = {...}
ApplicationInstance.create(attrs)
```

```ruby
# config/initializers/apartment.rb
Apartment.configure do |config|
  config.excluded_models = %w{ApplicationInstance}
  config.tenant_names = lambda { ApplicationInstance.pluck(:lti_key) }
end
```

```ruby
# models/application_instance.rb
class ApplicationInstance < ActiveRecord::Base
  after_create :create_schema
  def create_schema
    Apartment::Tenant.create lti_key
  rescue Apartment::TenantExists
    Apartment::Tenant.drop lti_key
    Apartment::Tenant.create lti_key
  end
end
```

To reproduce this bug, run `rake db:setup` twice. The first time, it will create the model, and create the schema for apartment. The second time those tenants will still exist in the schema and it will fail on the first `Apartment::Tenant.create lti_key` thus going into the rescue. Then on `Apartment::Tenant.drop lti_key` it will fail with `Apartment::TenantNotFound`. So it fails trying to create the tenant because it already exists, then it fails to drop because it doesn't exist. Highly suspicious. :]

If Apartment had some way to say
```ruby
def create_schema
  if !Apartment::TenantExists? lti_key
    Apartment::Tenant.create lti_key
  end
end
```

Then that would be way better. But alas it doesn't (that I have found). Can't use `Apartment.tenant_names` here because this happens during the creation of the model. Thus it is possible that nothing would be in that array.

Thanks!
-bfcoder

**Comment by bfcoder** [comment]
My fix for this issue:

```ruby
# models/application_instance.rb
class ApplicationInstance < ActiveRecord::Base
  after_commit :create_schema, on: :create
  def create_schema
    Apartment::Tenant.create lti_key
  rescue Apartment::TenantExists
  end
end
```
Now the model record is ensured to be created, and I just rescue the `Apartment::TenantExists` and ignore the error if the tenant is already there.

I do still think there is a bug with the rescue issue. I just found a better way to do what I was needing.

**Comment by mikecmpbll** [comment]
errors and backtraces for the for the exception would be nice.

apartment doesn't have a `.tenant_exists?` method because it doesn't keep track of your tenants so it has no way of knowing. if you want to test for a literal database or schema, then just write a query to do that.

glad you got it working how you want to in the end tho :+1:
