### ISSUE TITLE
2nd level subdomains block or redirect to 1st subdomain

### ISSUE THREAD

**Issue by Rovel** [influitive/apartment#407]
Hi,

I'm using apartment set tenant by it's subdomain, but I'm getting some strange behaviors when people log in a tenant with a 2nd level subdomain like this example.
https://foo.bar.com (correct link)
https://www.foo.bar.com (wrong link)

I'm already using the excluded, like below, but how can I exclude a second leve subdomain or redirect it to the first subdomain?

`Apartment::Elevators::Subdomain.excluded_subdomains = ["www"]`

**Comment by mikecmpbll** [comment]
what strange behaviour are you getting?

**Comment by Rovel** [comment]
all sort of behaviors, from views to controllers, I think its messes up with everything thats is related to specific tenant configurations.

**Comment by mikecmpbll** [comment]
hmm. i'm going to need you to be a bit more specific than that if you want me to help because nobody else has reported this issue yet so i'm not clear at the moment what's going on.

**Comment by Rovel** [comment]
well, for example the login page loads properly, as I was loading https://foo.bar.com
but devise rejects the auth, because probably it looks for the user in another schema.

**Comment by mikecmpbll** [comment]
1) you go to https://foo.bar.com
2) you log in
3) login fails? why? what's the current tenant when login fails?
