### ISSUE TITLE
Is it possible to make apartment switch tenants on connections set within specific models?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [influitive/apartment#412]
I have a postgresql setup with a readonly slave database. I'm using Apartment in the postgresql schema flavour. I would like to send some queries to that one,  to offload the primary.

They way I thought abou doing it was something like this:

```ruby
class Car < ActiveRecord::Base
  # This is my class that connects to the primary db via database.yml
end
```

I would make the slave work something like this:

```ruby
class ReadonlyCar < ActiveRecord::Base
  establish_connection(ActiveRecord::Base.connection_config.merge({host: 'some_other_host'}))
end
```

While this seems to work, the problem is, that doing `Apartment::Tenant.switch!(:germany)` only switches the schema on the primary connection.

Is there away around getting this to work?

**Comment by caironoleto** [comment]
I don't think so. We are using `Forwardable` and getting the connection through `ActiveRecord::Base.connection`. That establishes the connection using the database.yml configs.

**Comment by NielsKSchjoedt** [comment]
But if we were to implement it as a feature for apartment, any idea of an
approach we would you go with? I think it's a super common usecase, being
able to switch tenements on slaves (which are a mirror of the master, so no
differences in usage and structure). I mean, if you could tell apartment
something like: "btw here are some connection cinfigs for slaves, remember
to switch tenant on those as well, when you switch tenant...." What do you
think?

Den 10. mar. 2017 13.10 skrev "Cairo Noleto" <notifications@github.com>:

**Comment by NielsKSchjoedt** [comment]
Okay, so here is how I ended doing it for now (outside Apartment):

We have one tenant per country we operate in. Actually we do not switch tenant directly through Apartment, what we do instead is calling a `CountryManager` wrapper class who does all the needed stuff:

```ruby
class CountryManager
  def country= code
      RequestStore.store[COUNTRY_KEY] = code
      Apartment::Tenant.switch!(code)
      ReadonlyCar.connection.schema_search_path = Apartment.connection.schema_search_path
    end
end
```

As you can see, I just added `ReadonlyCar.connection.schema_search_path = Apartment.connection.schema_search_path` to that path - I guess that's all needed actually...?

Can you think of any edge case where this would give problems?

NOTE: we do NOT interact directly with switching tenant anywhere outside that method call.

**Comment by mikecmpbll** [comment]
there's a `connection_class` at the moment for modifying the main connection class (defaults to `ActiveRecord::Base`), but there's no support for multiple connection classes at present. pr welcome however!

i'm working on some features around tenant sharding (different physical hosts, already experimental support for this), but model splitting like this is quite different unfortunately.

**Comment by NielsKSchjoedt** [comment]
Interesting! Do you have a link to that experimental code? Also, can you spot any obvious flaws in the approach I described above?

**Comment by mikecmpbll** [comment]
yep that looks fine to me i think, can't see anything obviously wrong.

the experimental multi-host support at the moment is based on tenant configuration, commit here: https://github.com/influitive/apartment/commit/abdffbf8cd9fba87243f16c86390da13e318ee1f
