### ISSUE TITLE
Rails upgrade - ar_internal_metadata

### ISSUE THREAD

**Issue by Svashta** [influitive/apartment#414]
I am trying to upgrade my application from 4 to Rails 5 version and everything looks great except for the migrations which is one of the last things i need to fix.

I am using apartment gem and there are multiple databases in use.
Now, after upgrade I am getting error that ar_internal_metadata table is missing. It seems like it was created on default/primary DB, but not on tenant databases.

I was reading around about this and i understand what it is.
My question is what is the right way to solve this problem as it obviously comes from apartment, or is at least connected to this gem somehow.

Should I create this table on all tenant DBs manually?
Is there some new configuration option i am not aware?

If i create it manually, what does that mean for the future? Is this single record in the table only created once and not updated in the future, or does raiils internally update it at some point which means this table should probably be excluded in apartment?

Thanks for clarifications.

**Comment by Svashta** [comment]
OK, so I've manually created **ar_internal_metadata** table for already created and active tenant databases. Which solves the problem with normal migrations.

Now, when I create a new tenant, this table is somehow created automatically. No need for a new custom migration.

**Comment by mikecmpbll** [comment]
@Svashta thanks for reporting. it's related to an issue we currently have with Rails 5's `table_exists?` implementation https://github.com/rails/rails/pull/28399

it's should be being fixed in rails soon but i'm going to merge a fix in apartment shortly as well.

also reported in #404, #295, and #345

**Comment by sainejob** [comment]
+1 -- confirmed that moving to '5-0-stable' branch of rails fixes this issue.

**Comment by mikecmpbll** [comment]
should be okay in 5.1 afaict.
