### ISSUE TITLE
NoMethodError: undefined method `new' 

### ISSUE THREAD

**Issue by bholdman** [influitive/apartment#419]
Started a new project and only have Devise installed so far, after running bundle exec rails generate apartment:install I get an error now running any command. Rails version is 5.1.0 ruby version is 2.3.1.

The error I receive is: 
```
NoMethodError: undefined method `new' for "Apartment::Elevators::Subdomain":String
Did you mean?  next
/Users/BrianH/.rvm/gems/ruby-2.3.1/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/stack.rb:35:in `build'
/Users/BrianH/.rvm/gems/ruby-2.3.1/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/stack.rb:99:in `block in
 build'
```
I tried adding config.middleware.insert_before 'Warden::Manager', 'Apartment::Elevators::Subdomain' to application .rb and it results in the following error:

```
No such middleware to insert before: "Warden::Manager"
/Users/BrianH/.rvm/gems/ruby-2.3.1/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/stack.rb:106:in `assert_
index'
/Users/BrianH/.rvm/gems/ruby-2.3.1/gems/actionpack-5.1.0.rc1/lib/action_dispatch/middleware/stack.rb:73:in `insert'
/Users/BrianH/.rvm/gems/ruby-2.3.1/gems/railties-5.1.0.rc1/lib/rails/configuration.rb:69:in `block in merge_into'
/Users/BrianH/.rvm/gems/ruby-2.3.1/gems/railties-5.1.0.rc1/lib/rails/configuration.rb:68:in `each'
```

**Comment by bholdman** [comment]
Looks like this was an incompatibility issue with Rails 5.1.0. Changed to 5.0.2 and everything is working fine now.

**Comment by mastertechrv** [comment]
Any update for 5.1 with fixing this issue?

**Comment by israelias94** [comment]
any update for 5.1.1 with bug fixed?

**Comment by mlabarca** [comment]
Issue persists in rails 5.1.1

**Comment by BobWalsh** [comment]
I'm getting the same issue in 5.1.1

**Comment by mikecmpbll** [comment]
merged already will be released to rubygems soon, thanks for your report.

**Comment by qk-at-juice** [comment]
Still and issue for` rails 5.2.3` using 
`gem 'apartment', '~> 1.0', '>= 1.0.2'`

This was the version given by copying from rubygems. Fixed by removing quotes
