### ISSUE TITLE
after running rake apartment:migrate task,schema.rb not updating migration changes

### ISSUE THREAD

**Issue by venkat501** [influitive/apartment#425]

**Comment by meganemura** [comment]
@venkat501 
`db/schema.rb` is updated by `db:schema:dump` which is invoked by `db:migrate` task.
`apartment:migrate` task only does migrate to the tenants, not to the default (public) database.

Apartment enhances `db:migrate` task to run `apartment:migrate` after invoking `db:migrate` by default.
So, you can update `db/schema.rb` by invoking `db:migrate`.

refs:
https://github.com/influitive/apartment/blob/development/lib/apartment/tasks/enhancements.rb
https://github.com/influitive/apartment/blob/development/lib/tasks/apartment.rake
