### ISSUE TITLE
All tables in both central database and tenant schemas...

### ISSUE THREAD

**Issue by cwilliamsnh** [influitive/apartment#434]
I'm using the domain elevator

`require 'apartment/elevators/domain'`

and 

`Rails.application.config.middleware.use 'Apartment::Elevators::Domain'`

Both lines are found in my config/initializers/apartment.rb file.

However, when I create a new database, do `rake db:migrate`, create a new tenant and then do `rake db"migrate` again, all my tables are in both the central database as well as the tenant schemas. I have a second application that uses the exact same database that only has 'schema_migrations' and 'tenants' tables in the central database.

Do I need to manually delete the tables that belong in the tenant schema from the central database? When I did that, future migrations failed as tables were missing.

Thank you in advance for the help.

**Comment by mikecmpbll** [comment]
all databases in apartment have the same schema.

**Comment by AvaelKross** [comment]
ya, see in README: "Rails will always access the 'public' tenant when accessing these models, but note that tables will be created in all schemas. This may not be ideal, but its done this way because otherwise rails wouldn't be able to properly generate the schema.rb file."
