### ISSUE TITLE
Help creating a multi-tenancy API

### ISSUE THREAD

**Issue by halbano** [influitive/apartment#435]
Hi there, I'm a bit new with rails and I need some guidance to get all the stuff required working. 

I saw that I can wrote custom tenant switching using my own Elevator.

I'm building an API that receives x-user-company in every request from the frontend. I just want to select the correct schema based on that information and **prevent** switching back to public schema in every request. How I can achieve this logic? 

Any idea is very welcome

**Comment by mikecmpbll** [comment]
details for creating custom elevators in readme: https://github.com/influitive/apartment#custom-elevator

if you're stuck with anything specific ask on irc #apartment freenode
