### ISSUE TITLE
Change table name in apartment.rb

### ISSUE THREAD

**Issue by laerciocrestani** [influitive/apartment#437]
Hello.
![captura de tela 2017-06-14 as 15 33 56](https://user-images.githubusercontent.com/1430869/27149700-cb9932b4-511a-11e7-8471-5b45a0039e4e.png)
![captura de tela 2017-06-14 as 15 33 50](https://user-images.githubusercontent.com/1430869/27149701-cb9a63c8-511a-11e7-87c4-d76b408c5e41.png)

My question would be:
Today I have the following tanant:
Subdomain: itsmileacademia.pidia.com.br
Database I need connection: itsmileacademi (without the "a")
But I can not set the database in config.tenant_names

Notice that it searches the database for the subdomain and I have this for many clients, however I now have an external connection to another HOST and they can not rename the base.

Look at the attachments.

Someone could help me how I should proceed. Thank you very much.

**Comment by mikecmpbll** [comment]
thanks for the report, i'll be looking into this over the coming days

**Comment by mikecmpbll** [comment]
i think i'll be focusing on the rewrite of connection switching that i'm working on atm in #438 . you should be able to hack around this for now by calling your tenant "itsmileacademi" and then handling translating this specific case in your subdomain elevator.

i'd be happy to review an MR though.

**Comment by laerciocrestani** [comment]
@mikecmpbll 
I did not understand how I should do to be able to suppress it.
Can you kindly give me an example? 
Tanks

**Comment by mikecmpbll** [comment]
presumably you're using some kind of subdomain elevator? maybe the one that ships with apartment? that elevator would take the subdomain 'itsmileacademia', and try to connect to tenant 'itsmileacademia'. the problem is, the hash configuration overrides the database name with the tenant name, so if your database is really called 'itsmileacademi' that's what your tenant will have to be called.

sooo.. with that said, you can change your tenant names config to have 'itsmileacademi' as the tenant name, then you can write your own apartment connection middleware which is the same as what you're currently using, but which has something like:

```ruby
subdomain == 'itsmileacademi' if subdomain == 'itsmileacademia'

# apartment will then connect to tenant 'itsmileacademi'
end

**Comment by laerciocrestani** [comment]
@mikecmpbll 
Sorry for my ignorance, but I saw here about the generic elevator, but when I tribute it I lose the subdomain, see below if I should use it this way?

```
Rails.application.config.middleware.use 'SiteBake::SiteElevator'
require 'apartment/elevators/generic'
```
```
module SiteBake
  # SiteBake::SiteElevator
  class SiteElevator < Apartment::Elevators::Generic
    def parse_tenant_name(request)
      domain = Domain.find_by_host request.host

      return domain.site.token unless domain.nil?

      fail StandardError, "Domain with host #{request.host} not found"
    end
  end
end
```

**Comment by mikecmpbll** [comment]
no problem! i suggest subclassing the subdomain elevator if that's what you need: https://github.com/influitive/apartment/blob/development/lib/apartment/elevators/subdomain.rb

you can then override `parse_tenant_name` with your custom behaviour.

if you have other questions you can find me at [#apartment irc](https://webchat.freenode.net/?channels=#apartment) on freenode
