### ISSUE TITLE
Can I associate excluded model with model not excluded?

### ISSUE THREAD

**Issue by wfsneto** [influitive/apartment#446]
I have these models:

```ruby
class Modulu < ApplicationRecord
  has_many :kontrollers, dependent: :destroy
end
```

```ruby
class Kontroller < ApplicationRecord
  belongs_to :modulu

  has_many :actions, dependent: :destroy
end
```

```ruby
class Action < ApplicationRecord
  belongs_to :kontroller
end
```

```ruby
class Menu < ApplicationRecord
  has_many :items, dependent: :destroy
end
```

```ruby
class MenuItem < ApplicationRecord
  belongs_to :menu
  belongs_to :action # excluded_models
end
```

And I need associate `Action`, an excluded model, with `MenuItem`, but always when try save a menu_item a catch this error:

`ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  insert or update on table "acl_menu_items" violates foreign key constraint "fk_rails_f8a45bf567"
DETAIL:  Key (action_id)=(1af8a0e7-0c2b-4221-bd22-3800151917ef) is not present in table "acl_actions"`.

> PS: Modulu, Kontroller and Action are excluded_models. Menu and MenuItem are in a client tenant

Can I to do this association?

Thanks for your attention

**Comment by mikecmpbll** [comment]
#397 #382 #248 #227

**Comment by wfsneto** [comment]
Thanks!
