### ISSUE TITLE
When using apartment the post params change its behavior

### ISSUE THREAD

**Issue by esteoliver** [influitive/apartment#455]
I want to migrate an existing database to start using multi-tenancy. In order for this to work I want to create a configuration that allows me to configure Apartment and the application keeps working just like using only one schema

This is my config
```
# config/initializer/aparment.rb
Apartment.configure do |config|

  Rails.application.eager_load!
  config.excluded_models = ActiveRecord::Base.descendants.map(&:name) - ["HABTM_HelpResources"]
  config.tenant_names = lambda { Agency.pluck :url }
  config.persistent_schemas = ["extensions"]
end
```

```
# config/application.rb
   ...
    # ELEVATOR
    config.middleware.use "Apartment::Elevators::Subdomain"
   ...
```

everything worked fine until I tried to make a post request to my API and start to have some errors with the params. When using Apartment Rails generates the following params:
API ROUTE `/api/v1/agent/sheets`
REQUEST BODY `{"title": "ROM-009"}`
```
{"title"=>"ROM-009", "base"=>{"title"=>"ROM-009"}}
```
but without it 
```
{"title"=>"ROM-009", "sheet"=>{"title"=>"ROM-009"}}
```

I don't know why changes `sheet` to `basic`, but only occurs when using Apartment. I tried to figure out what changes or parses this value but I found nothing and the request is exactly the same. 

PD: I'm using Rails 5.0.3, Rack 2.0.3 and Apartment 1.2.0

**Comment by mikecmpbll** [comment]
there's nothing in apartment which would have anything to do with your params in a request, so even if it is related to apartment in some obscure way we couldn't possibly know why from the information provided, unfortunately.

**Comment by esteoliver** [comment]
thanks @mikecmpbll 

from your answer I could focus on finding another way of solving my problem and I found that the wrapper of the POST request is made by `ActionController::ParamsWrapper`. For some reason the default configuration stop working, but adding `wrap_parameters format: [:json]` on the controller solves the problem.
