### ISSUE TITLE
db:drop and db:reset drops only public tenant

### ISSUE THREAD

**Issue by kuzukuzu** [influitive/apartment#464]
Each tenants excluding public one aren't dropped with `db:drop` .
Also with `db:reset` .

So I have an error while recreating another tenant with same name.

Isn't there any plan to enhance tasks, `db:drop` and `db:reset` ?

**Comment by meganemura** [comment]
To enhance `db:drop` and `db:reset` (do apartment task before db task) with `apartment:drop` and `apartment:reset` is nice to have.
Maybe I will implement these.

**Comment by dalezak** [comment]
@kuzukuzu @meganemura something like this might work?

```
namespace :apartment do
  desc 'Drop Public and Tenants'
  task :drop => :environment do
    Rake::Task['db:drop:all'].invoke
  end

  desc 'Create'
  task :create => :environment do
    Rake::Task['db:create'].invoke
  end

  desc 'Migrate'
  task :migrate => :environment do
    Rake::Task['db:migrate'].invoke
  end

  desc 'Seed'
  task :seed => :environment do
    Rake::Task['db:seed'].invoke
  end

  desc 'Drop, Create, Migrate, Seed'
  task :reset => :environment do
    Rake::Task['db:drop:all'].invoke
    Rake::Task['db:create'].invoke
    Rake::Task['db:migrate'].invoke
    Rake::Task['db:seed'].invoke
  end
end
```

**Comment by kuzukuzu** [comment]
Might works.
But, enhance `db:drop` and `db:drop:all` task with `Apartment::RakeTaskEnhancer` is better way I think.

How's it?

**Comment by kuzukuzu** [comment]
fix merged.
close issue.
