### ISSUE TITLE
Using Apartment without subdomain and 1 central login form ( devise )

### ISSUE THREAD

**Issue by jordanlance** [influitive/apartment#467]
Would it be possible to use Appartment
Using Apartment without subdomain and 1 central login form ( devise )?

We don't want subdomains for every customer

**Comment by meganemura** [comment]
@jordanlance 
You can. Did you check the [Custom Elevator](https://github.com/influitive/apartment#custom-elevator) section in README?

**Comment by jordanlance** [comment]
@meganemura 
Thank you, we overlooked this coming from the related blog posts.
