### ISSUE TITLE
Switching the tenant based on request header

### ISSUE THREAD

**Issue by halbano** [influitive/apartment#469]
Hi there, 

Thank you for your time and patience. I'm a bit new with Rails and also using your gem and I need some assistance to make it work. 

I need to configure the tenant based in one custom header present on the request. I also want to prevent the default switching to the public tenant when and exception or something fails. 

I've written something but I cannot make it work. Any help is really appreciated. 

Notice the **horrible** way to get my custom header. Anyone knows how to do that in a better way?

```
# app/middleware/my_custom_elevator.rb
require 'apartment/elevators/generic'

def non_restricted_paths
  return ["/", "/admin", "/api/v1/users/sign_in", "/api/v1/users/sign_up", "/api/v1/users/authenticate", "/api/v1/companies/set_company"]
end

class CompanyElevator < Apartment::Elevators::Generic
    # @return {String} - The tenant to switch to
    def parse_tenant_name(request)
      # Get headers
      puts "This is the path: " + request.path
      puts "non_restricted_paths: " + non_restricted_paths.to_s
      if non_restricted_paths.any? { |path| request.path.eql? path }
        puts "non restricted path!!"
        return "public"
      else

        headers = Hash[*request.env.select {|k,v| k.start_with? 'HTTP_'}
                            .collect {|k,v| [k.sub(/^HTTP_/, ''), v]}
                            .collect {|k,v| [k.split('_').collect(&:capitalize).join('-'), v]}
                            .sort
                            .flatten]

        # request is an instance of Rack::Request
        if headers['X-User-Company'] == nil
          fail StandardError, "You shold configure the company"
          return Apartment::Tenant.current
        end

        # example: look up some tenant from the db based on this request
        tenant_name = Company.find_by(id: headers['X-User-Company']).subdomain
        puts "Is here!!"
        return tenant_name
      end
    end
end
```

Best regards,
Hernan

**Comment by mikecmpbll** [comment]
> I cannot make it work

what's the issue/error? looks okay to me but i'm not a 100% foolproof ruby parser :D

**Comment by halbano** [comment]
It was more a question than an issue, but I finally could get this working. Thanks @mikecmpbll for your time. 

The final elevator is a mixture between two and uses the request header as tenant name, and if not present uses the subdomain on the origin host.

**Comment by mikecmpbll** [comment]
lovely :+1:
