### ISSUE TITLE
Missing v2.0.0 tag

### ISSUE THREAD

**Issue by gfx** [influitive/apartment#471]
I want to see the diff of `v1.2.0...v2.0.0`. It's https://github.com/influitive/apartment/compare/v1.2.0...HEAD for now but it's not valid in a future.

FYI: `rake release` runs `git push origin $tag` in addition to everything else.

**Comment by mikecmpbll** [comment]
apologies; first release that i've done for apartment so wasn't 💯 on the process. will take a look at this this evening. thanks for the heads up :).

**Comment by gfx** [comment]
Thank you 👏
