### ISSUE TITLE
Apartment + Devise + activerecord-session_store + lvh.me

### ISSUE THREAD

**Issue by dalezak** [influitive/apartment#476]
I'm trying to get `Apartment` working with [Devise](https://github.com/plataformatec/devise) using [activerecord-session_store](https://github.com/rails/activerecord-session_store) (need to store large session objects too big for cookies) with `lvh.me` (to test redirecting to tenant's subdomain after logging in locally).

I can login on `http://localhost:3000` just fine, the `current_user` is set properly. However when I try logging in on `http://www.lvh.me`, the `current_user` is `nil` afterwards, believe it's related to the `session_store`.

I've tried variously configurations of `session_store` for `:cookie_store` with some luck.

```
Rails.application.config.session_store :cookie_store, key: '_myapp_session', domain: '.lvh.me', tld_length: 2
```

However when I try switching to `active_record_store`, the `current_user` is always `nil` after logging in. I've tried the following, but no luck.

```
Rails.application.config.session_store :active_record_store, key: '_appssembly_session', domain: '.lvh.me', tld_length: 2
```
What is the recommended configuration for `Apartment` with `Devise` using `active_record_store` and `lvh.me`?

**Comment by dalezak** [comment]
I've tracked down the issue, looks like it's related to using `active_record_store`, when I use `cookie_store` I am able to share the `current_user` across the `public` and `tenant` subdomains.

For Apartment's `config.excluded_models`, do I need to exclude the `Session` model? I suspect that `active_record_store` session is being stored in the `public` schema and not accessible to the tenant.

**Comment by mikecmpbll** [comment]
@dalezak I suspect so. your cookie stuff will most likely happen further up the stack than apartment's tenant switching, so it'll still be connected to the public or default tenant at this stage, so that's where you'll want your sessions to be stored.

**Comment by dalezak** [comment]
@mikecmpbll good news, looks like I may have figured it out!

The [activerecord-session_store](https://github.com/rails/activerecord-session_store) session object is defined in [ActiveRecord::SessionStore::Session](https://github.com/rails/activerecord-session_store/blob/master/lib/active_record/session_store/session.rb). 

So if I include `ActiveRecord::SessionStore::Session` in Apartment's `excluded_models`, then I am able to login on the `public` side, and still use`current_user ` on the `tenant` side :+1:

```
config.excluded_models = %w{ Tenant User ActiveRecord::SessionStore::Session }
```

**Comment by mikecmpbll** [comment]
ah yes. not sure why i didn't suggest that before. if your using the DB for the session and that session needs to be cross-tenant, then it makes sense that the table that stores the session is excluded.
