### ISSUE TITLE
Maintainer needed?

### ISSUE THREAD

**Issue by meganemura** [influitive/apartment#482]
Hi, maintainers.
I feel we currently have many remained issues and pull requests. Since my company uses this gem as significant part of the service in production for about 2 years, it motivates me to contribute to keep the gem healthy.
@mikecmpbll seems to be the only active person of maintainers who can commit/merge and cut/push the release to RubyGems. It must be tough.

We are also heavily depending on influitive/apartment-sidekiq in production too. I worry that the gem does not have any active maintainers.

If you need additional maintainers to help the community, please consider give me or anybody permissions.

**Comment by meganemura** [comment]
oops.

**Comment by mikecmpbll** [comment]
would be fine by me :). +1 on apartment-sidekiq, which we also use.

@bradrobertson : @meganemura is an active and quality contributor, i would recommend they get collaborator permissions :+1:

**Comment by bradrobertson** [comment]
Oh somehow I was NOT notified about this. Sorry all. Fine by me
