### ISSUE TITLE
Feature request: Support Oracle database

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [influitive/apartment#485]
Hello there,

Thank you a lot for awesome gem! We have to migrate our project to Oracle database. I wanted to know are you planning to add Oracle adapter? And do you think it would take long time if I try to add it myself?

Thank you!

**Comment by mikecmpbll** [comment]
it's unlikely we'll be adding support for new adapters unless they're contributed. if you'd like to write one yourself and have any questions, feel free to contact me on IRC; #apartment on freenode.
