### ISSUE TITLE
Rails5.2 + Devise

### ISSUE THREAD

**Issue by alanq** [influitive/apartment#498]
Running rails s throws:

gems/actionpack-5.2.0.beta2/lib/action_dispatch/middleware/stack.rb:108:in `assert_index': No such middleware to insert before: "Warden::Manager" (RuntimeError)

With this line in apartment.rb initializer:

Rails.application.config.middleware.insert_before 'Warden::Manager', 'Apartment::Elevators::Subdomain'

**Comment by mikecmpbll** [comment]
@alanq and are you using Warden::Manager middleware? :)

**Comment by alanq-fc** [comment]
This was fixed by using the classes instead of class name string in the initializer:

`Rails.application.config.middleware.use Apartment::Elevators::Subdomain
Rails.application.config.middleware.insert_before Warden::Manager, Apartment::Elevators::Subdomain
`

**Comment by mikecmpbll** [comment]
ah yes, indeed. that is required in rails 5.x.
