### ISSUE TITLE
Pending Migration Error if default schema is not Public

### ISSUE THREAD

**Issue by mridulap2003** [influitive/apartment#501]
## Steps to reproduce
1) Add the apartment gem to your rails app and change the default schema to `internal` in `apartment.rb`
2) Add a new migration `rails g migration SomeNewMigration`. Add some schema changes in the new migration. Like adding a new table.
3) Run `rails db:migrate`
4) Start the Rails Server and browse to any route in the app (http://somedomain.lvh.me/something).

## Expected behavior
The `schema_migrations` table in the `internal` and any other tenant schemas must have the new migration no. inserted. The `schema_migrations` table of the `public` schema must be ignored. The app should work fine.

## Actual behavior
The `schema_migrations` table in the `internal` and any other tenant schemas do have the new migration no. inserted. However, upon browsing the app, I get the `ActiveRecord::PendingMigrationError`. If I insert the new migration no. into the `public.schema_migrations` table, it works.

## System configuration
OS: Mac OS High Sierra

* Database: Postgresql 9.6

* Apartment version: 1.2.0

* Apartment config (in `config/initializers/apartment.rb` or so):

        #This is the entire file without the comments:
        require 'apartment/elevators/subdomain'
        Apartment.configure do |config|
              config.excluded_models = %w{ Client TemporaryUpload User PublicAnonymousUser PublicUser }
              config.default_schema = 'internal'
              config.tenant_names = lambda { Client.pluck :subdomain }
        end
        Rails.application.config.middleware.use Apartment::Elevators::Subdomain
        Apartment::Elevators::Subdomain.excluded_subdomains = ['internal']

* Rails (or ActiveRecord) version: 5.0.6

* Ruby version: 2.4.1p111

**Comment by mri-dula** [comment]
Fixed this by changing the `schema_search_path` in my `database.yml`

    development:
        adapter: postgresql
        encoding: unicode
        database: myapp
        pool: 5
        username: postgres
        password: ***
        host: localhost
        schema_search_path: 'internal'

**Comment by mikecmpbll** [comment]
curious. thank you for investigating and providing a solution ⭐️

**Comment by mikecmpbll** [comment]
ah yes: https://github.com/influitive/apartment#2-ensure-the-schema-is-in-rails-default-connection
