### ISSUE TITLE
How to tell apartment to ignore few tables while creating new schema for tenant

### ISSUE THREAD

**Issue by chetanrana2702** [influitive/apartment#503]
## Expected behavior
While creating a new tenant from rails console it is creating a separate schema for every tenant which is good but is not excluding Models which i have provided in apartment.rb file under config.excluded_models = %w{Tenant User}.

I am not naming schemas with subdomain rather using generic elevator and generating uid for every new Tenant and letting know to name schema with uid key.

Expected is i want to make tenants and users table remain under public schema only and these must not be copied in other tenants schema as there is no point in repeating these two tables every where

## System configuration

* Database: (Tell us what database and its version you use.)
Database: Postgresql 
version: 10.1

* Apartment version: 2.0.0

* Apartment config (in `config/initializers/apartment.rb` or so):

require 'apartment/elevators/generic'
Apartment.configure do |config|
    config.excluded_models = %w[Tenant]
    config.tenant_names = -> { Tenant.pluck :schema_uid }
end

Rails.application.config.middleware.use Apartment::Elevators::Generic, lambda { |request|
  Tenant.find_by(subdomain: request.host.split('.').first).schema_uid
}

* Rails (or ActiveRecord) version: 5.1.4

* Ruby version: 2.4.2

**Comment by mikecmpbll** [comment]
hi! this is expected behaviour.

> Rails will always access the 'public' tenant when accessing these models, but note that tables will be created in all schemas. This may not be ideal, but its done this way because otherwise rails wouldn't be able to properly generate the schema.rb file.

https://github.com/influitive/apartment#excluding-models
