### ISSUE TITLE
GraphQL compatibility?

### ISSUE THREAD

**Issue by zibs** [influitive/apartment#505]
Question: Does apartment work with something like the graphql ruby implementation https://github.com/rmosolgo/graphql-ruby ? Will it know how to detect the correct tenant during the request? Will it detect the correct subdomain?

I'm planning on experimenting with this in the coming weeks, and will report back if no one has any experience with this yet.

**Comment by mikecmpbll** [comment]
i don't know much about graphql and don't really have the time to read about it, so a more pointed question would be appreciated :).

apartment handles tenant tasks, including switching, for postgresql and mysql. unless graphql uses a different database adapter, or interferes with the database connections, i don't see that it'd have anything to do with apartment.
