### ISSUE TITLE
tenants without sub domain

### ISSUE THREAD

**Issue by QuickD** [influitive/apartment#507]
Hi, 

I am using Rails 5 and have a table called customers. There is a column named tenant in this customer table. When a user browses to my site, i want them to be able to type in the customer id and have the app switch to that tenant based on that field. 

I looked at the Custom Elevators section of Read ME but I am still a little confused. 

Any help is greatly appreciated!

**Comment by mikecmpbll** [comment]
a good place for things which span multiple requests is a cookie (possibly the session cookie). store the choice of customer id in a cookie, perhaps, and retrieve that value in a custom elevator to select the right tenant for each request.

if you have further questions head to the #apartment irc channel on freenode and i'll be happy to help if i'm around 🌟 .
