### ISSUE TITLE
Question about using devise_security_extension with apartment

### ISSUE THREAD

**Issue by peterwake** [influitive/apartment#509]
Hi,

We've been using the Apartment gem very successfully over the last couple of years, thank you.

We now have a requirement to set different password security rules depending on the tenant, and have been trying to get Apartment working with the [devise_security_extension](https://github.com/phatworx/devise_security_extension) gem.

I tried using lambdas in `config/initializers/devise_security_extension.rb` as shown below but that didn't work. I was wondering if you have any recommendation on how these settings could be pushed down into the Apartment middleware. 

```ruby
  config.password_length = lambda{ LoginSecurity.password_length }
  config.expire_password_after = lambda{ LoginSecurity.expire_password_after }
  config.password_regex = lambda{ LoginSecurity.password_regex }
  config.deny_old_passwords = lambda{ LoginSecurity.deny_old_passwords }
  config.password_archiving_count = lambda{ LoginSecurity.password_archiving_count }
```

Thanks!

**Comment by mikecmpbll** [comment]
hi @peterwake :). not really an apartment question but rather a devise one.

the settings you eluded to will need to be able to be changed post-initialisation (or like you've attempted, supplied as a callable) and able to be configured local to current thread (if you're using a threaded web server or job runner). if these conditions aren't met then it's a no-go without some hacking the internals of devise_security_extension, i'm afraid.

**Comment by peterwake** [comment]
Many thanks Mike, really appreciate your advice. I'd better get my hacking hat on!
