### ISSUE TITLE
Issues with all models being returned

### ISSUE THREAD

**Issue by samstarling** [influitive/apartment#512]
I'm playing around with Apartment to get my head around how it works. For now, I've got two excluded models, User and Organisation. An Organisation can have many users, and I'm hoping in the future to write a custom middleware that looks at `current_user` and switches accordingly.

Please let me know if you need any additional information: I appreciate the time you take to read this.

## Steps to reproduce

In an `after_create` method on Organisation, I call `Apartment::Tenant.create(name)`. In a controller, I switch manually for now:

```ruby
@posts = Apartment::Tenant.switch(current_user.organisation.name) do
   BlogPost.all
end
```

## Expected behavior

I would expect only the BlogPost models created for the tenant belonging to that user's organisation to be returned.

## Actual behavior

All models from all tenants are returned. I have done some `puts`-based debugging, and the argument I am passing to `switch` is indeed different.

## System configuration

* Database: Postgres 9.6
* Apartment version: 2.1.0
* Apartment config (in `config/initializers/apartment.rb` or so):
  * `config.excluded_models = %w{ User Organisation }`
  * `config.tenant_names = lambda { Organisation.pluck :name }`
  * `config.use_schemas = true`
  * No middleware configured
* Rails (or ActiveRecord) version: 5.1.4
* Ruby version: 2.4.1

**Comment by samstarling** [comment]
Actually, I've been a little silly here: I wasn't using `Apartment::Tenant.switch` when I created these models. It sounds like the next step is to write that middleware – while I'm here, is it unusual to write middleware that accesses something like `current_user`? If you can think of anyone who's got an example of switching based on the property of a user, that'd be much appreciated!

**Comment by ArthurWeiden** [comment]
I've actually been stuck on this for a while now as well, so if you find such an example please do tell

**Comment by samstarling** [comment]
Hey @ArthurWeiden – the problem was that I was in the "public" tenant/schema when I was writing my models (in my `Controller#create` method), and so these were being returned for all tenants, which is what is expected. Perhaps you're doing something similar?

**Comment by mikecmpbll** [comment]
> is it unusual to write middleware that accesses something like current_user?

if you're switching on application-level data it might be easier to bring the switching down to an around_action at the controller level, rather than middleware, just be careful that you switch correctly for all cases because you don't want tenant leakage.

**Comment by ArthurWeiden** [comment]
@samstarling Sorry for the delayed reply, life got a bit in the way. Thanks, that was indeed what I was doing, because I didn't switch between the tenants. I've now decided to use the subdomain elevator to switch and everything works like a charm
