### ISSUE TITLE
Recommended ActiveJob background worker?

### ISSUE THREAD

**Issue by ghost** [influitive/apartment#516]
We are in the process of scaling out a Rails 5.1 application, migrating from a single MySQL database to a PostgreSQL DB with schemas for each client using Apartment Gem.

We have a Client table for each customer and each Client can have multiple Users which are globally unique. All other tables have a client_id column, referencing the client. The Client and User table would live in the public schema. All other tables would end up in the client-specific schema using a custom elevator to switch apartments.

We are currently using Delayed::Job as background worker for our application. The demand for the background worker is not that high and we are considering alternatives if that would make the migration easier. (i.e. sidekiq)

Is there any preference in background worker adapter? I saw there is a specific sidekiq gem, but reading the issues page on Rails 5.x incompatibilities I get the feeling this project is fairly dead.

**Comment by mikecmpbll** [comment]
no specific preference imo, in my experience they're all straightforward to get working with apartment, with or without the specific gems. it's just a case of switching tenant around the job being performed. i don't know about the incompatibilities mentioned in the apartment-sidekiq issue, and there doesn't appear to be much debugging/investigation done on it yet so i can't help there.

the only consideration i would stress that is apartment related, is that the apartment connection-based adapters (use_schemas=false) aren't threadsafe and therefore sidekiq, which is multithreaded, won't work correctly. delayed_job isn't multithreaded therefore there isn't a problem there.

**Comment by ghost** [comment]
Thanks. I guess the thread-safety on the connection-based adapter is what the big rewrite you are doing is about? For now, I am planning to migrate to a single Postgres DB using schema's with the same DelayedJob backend adapter. Performance wise this should not be a problem for a long time.

I followed the instructions in this PR !436 by adding an extra column to the delayed_jobs table. I saw you had a suggestion to do it better, but couldn't find documentation on that :)

Thanks for the info. Keep up the good work :)

**Comment by mikecmpbll** [comment]
it involves that, but the rewrite's primary focus is on sharding support.

when we used DJ we made sure the delayed job table was an excluded model but i can't remember how we switched during perform, i'll double check later and get back.

**Comment by rafayet-monon** [comment]
I can't work with delayed job. Seems I don't understand the process. Can you please explain or give an example? It would be really helpful. 

here's the [gist](https://gist.github.com/rafayet-monon/515a9f99a2be8a668d2d7364196c07a1).

Thanks in advance

**Comment by derosm2** [comment]
Any update on getting this to work with DelayedJob? I took a quick stab at using https://github.com/influitive/apartment-activejob/ and excluding the appropriate class. Looks like the job was serialized correctly but job didn't change tenants when executing.

**Comment by mikecmpbll** [comment]
the [DJ docs are pretty clear on hooks](https://github.com/collectiveidea/delayed_job/#hooks), so something should be simple to implement.

a superclass for your jobs like:

```ruby
class DjJob
  def enqueue(job)
    @tenant = Apartment::Tenant.current
  end

  def perform
    Apartment::Tenant.switch(@tenant) do
      run
    end
  end
end
```

or something similar ... and then your jobs just implement the `run` method rather than `perform`. (untested)
