### ISSUE TITLE
How to get all data on all schema (include public and tenant another)

### ISSUE THREAD

**Issue by cavoixanha** [influitive/apartment#517]
I use Postgresql
I use `Apartment::Tenant.switch` for swith on subdomain
I can work with 
```
Apartment::Tenant.switch('tenant_name')
```
but It's complex when I have many subdomain I think affect performance of application. Have you actually do better?

**Comment by mikecmpbll** [comment]
i don't think i understand what you're asking. can you try and rephrase the question?

**Comment by cavoixanha** [comment]
I want get all data on all tenant exits! 
I don't create many connection for many schema!

**Comment by mikecmpbll** [comment]
so, query a model and get the results for all tenants? you can loop through the tenants i guess, but like you say it probably won't be fast. i did create [querrel](https://github.com/meritec/querrel), but not tested on pg. should probably work if you provide full configs with different schema_search_path options.

will close as not an apartment feature, and probably never will be, but feel free to continue the discussion.
