### ISSUE TITLE
[request] continuous release

### ISSUE THREAD

**Issue by gfx** [influitive/apartment#524]
It's not a bug report nor a feature request.

I'd like you to release the gem continuously because I want to use some features added after v2.0.0 release.

(As of now 41 commits from 2.0.0 https://github.com/influitive/apartment/compare/v2.0.0...HEAD)

**Comment by gfx** [comment]
ping @mikecmpbll

**Comment by meganemura** [comment]
@gfx 
[apartment 2.1.0](https://rubygems.org/gems/apartment/versions/2.1.0) has been released to rubygems in December 15, 2017. But the tag of v2.1.0 in git repo was missing. So I [tagged it](https://github.com/influitive/apartment/releases/tag/v2.1.0).
Currently, there is no feature in development branch from [v2.1.0](https://github.com/influitive/apartment/compare/v2.1.0...development).

And I now have a right to release gem to rubygems.org. I will try to release quickly as possible.
Thank you for your suggestions.
