### ISSUE TITLE
Apartment::Tenant.current does not match the actual schema the database is in

### ISSUE THREAD

**Issue by L33tH4x0r** [influitive/apartment#525]
## Steps to reproduce
Using the Devise Invitable gem, a user accepts their invitation
Get sent to a controller action that takes their request.subdomain and switches to their schema
Checking `ActiveRecord::Base.connection.schema_search_path` shows public instead of what's shown in `Apartment::Tenant.current`

## Expected behavior
User should be in the schema from their subdomain to find their account and accept their invitaiton

## Actual behavior
The user is not found because the database schema is incorrect

## System configuration
```
'activerecord', '~> 5.0', '>= 5.0.0.1'
'rails', '~> 5.0.1'
ruby '2.3.4'
gem 'apartment', '~> 1.0', '>= 1.0.2'
gem 'devise_invitable', '~> 1.7.0'
```

* Database: (Tell us what database and its version you use.)
PostgreSQL 9.5.11

* Apartment version:
1.2.0
* Apartment config (in `config/initializers/apartment.rb` or so):
```
Apartment.configure do |config|
  config.excluded_models = ['Account', "InviteError"]

  # Dynamically get tenant names to migrate
  config.tenant_names = lambda{ Account.pluck(:subdomain) }
end
```
  * `use_schemas`: (`true` or `false`)
We're using schemas, not sure what this means

* Rails (or ActiveRecord) version:
5.0.1
* Ruby version:
2.3.4

**Comment by mikecmpbll** [comment]
can you upgrade apartment please? the recent releases targetted rails 5.x but you're on an older version. might not be relevant but would be quick to rule it out.

**Comment by L33tH4x0r** [comment]
We found the issue, had nothing to do with Apartment. Was a misconfiguration on our side dealing with the devise_invitables gem having a higher priority within the Rack hierarchy. We implemented a custom elevator and gave priority to the elevator over warden in the Rack hierarchy.

**Comment by mikecmpbll** [comment]
ah yes, there's a section addressing warden and other such middlewares in the [readme](https://github.com/influitive/apartment#middleware-considerations).
