### ISSUE TITLE
postgresql/pg_dump 10.3 prepends schema public to CREATE TABLE statements

### ISSUE THREAD

**Issue by IngusSkaistkalns** [influitive/apartment#533]
## Steps to reproduce

Apartment from development, Rails 5.2.0.rc1

When creating new tenant, sql fails to create tables, because public schema gets prepended to create table statements:
```
-- Dumped from database version 10.3 (Debian 10.3-1.pgdg90+1)
-- Dumped by pg_dump version 10.3 (Debian 10.3-1.pgdg90+1)

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: ar_internal_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ar_internal_metadata (
```

Coud this be related to this issue -> `Fix pg_dump's mishandling of STATISTICS objects ` https://www.postgresql.org/docs/10/static/release-10-3.html

## Expected behavior

`Apartment::Tenant.create('my-tenant')` does not raise errors.

## Actual behavior

Fails with:
`ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "ar_internal_metadata" already exists`

## System configuration

CircleCI:
```
- image: circleci/ruby:2.5.0-node-browsers
- image: circleci/postgres:10-postgis-ram
      - run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - run: sudo sh -c 'wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -'
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-10
```

* Database: (Tell us what database and its version you use.)

```
-- Dumped from database version 10.3 (Debian 10.3-1.pgdg90+1)
-- Dumped by pg_dump version 10.3 (Debian 10.3-1.pgdg90+1)
```

* Apartment version:

from developemnt - 50d86cebbea2

* Apartment config (in `config/initializers/apartment.rb` or so):

  * use_schemas = true
  * use_sql = true
  * default_schema = "public"
  * persistent_schemas = %w(public postgis)

* Rails (or ActiveRecord) version:
  5.2.0rc1

* Ruby version:
  2.5.0

**Comment by IngusSkaistkalns** [comment]
Possibly missing something, because downgraded pg on circleci to 9.6.8 and now I got similar error, but on different objects - indexes, when creating new tenant:
```
--
-- Name: index_cars_on_depo_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_cars_on_depo_id ON public.cars USING btree (depo_id);


--
-- Name: index_plan_events_on_car_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_plan_events_on_car_id ON public.plan_events USING btree (car_id);

```

but prefix dissapears from tables.

Or is it because of new releases:
Avoid use of insecure search_path settings in pg_dump and other client programs -> https://www.postgresql.org/docs/9.6/static/release-9-6-8.html

**Comment by IngusSkaistkalns** [comment]
Could be same issue as here -> https://github.com/influitive/apartment/issues/532

**Comment by aldrinmartoq** [comment]
@IngusSkaistkalns Yes, it is the same problem.

**Comment by IngusSkaistkalns** [comment]
Closing since it the same as #532
