### ISSUE TITLE
Any plan to release a version compatible with Rails 5.2? 

### ISSUE THREAD

**Issue by abartier** [influitive/apartment#543]
Hello, 

I believe we're a few waiting for the next update of the gem. 
The major problems are related to the db:create/migrate errors but I believe that few PR have solved this. 

Any ETA on the future release ?

EDIT: Or any recommendations for using Apartment with Rails 5.2 ;)

**Comment by abartier** [comment]
Temp fix but not recommended: 
I use this in my gem file

`gem 'apartment', git: "https://github.com/influitive/apartment.git", branch: "development"`

**Comment by jstoup111** [comment]
Seeing a few of these errors and would be great to have a compatible version released soon!

**Comment by meganemura** [comment]
Released.
https://rubygems.org/gems/apartment/versions/2.2.0
