### ISSUE TITLE
Private schema excessive tables

### ISSUE THREAD

**Issue by mzaidannas** [influitive/apartment#564]
## Steps to reproduce

```bash
rake db:drop db:create db:migrate
```

## Expected behavior
Apartment should only create included model tables in private schemas

## Actual behavior
All tables/views/indices are created in public and private schemas

## System configuration

* Database: Postgresql 10.4

* Apartment version: 2.1.0

* Apartment config (in `config/initializers/apartment.rb` or so):
```ruby
Apartment.configure do |config|
  config.tenant_names  =  lambda { Model.friendly.pluck(:tenant_name) }
  config.use_schemas  =  true
  config.use_sql  =  true
end
```

  * `use_schemas`: `true`

* Rails (or ActiveRecord) version: 4.2

* Ruby version: 2.4.2

**Comment by mikecmpbll** [comment]
https://github.com/influitive/apartment#excluding-models
