### ISSUE TITLE
Streaming using ActionController::Live resets current tenant to the default one

### ISSUE THREAD

**Issue by Looooong** [influitive/apartment#600]
## Description

Whenever data are streamed by writing to response buffer from `ActionController::Live`, the `Apartment::Tenant.current` is reset back to the default tenant.

## Reproduction

[Sample project](https://github.com/Looooong/apartment_streaming_bug). The project is setup with 2 tenants:

+ `development` is the default tenant.
+ `test` is always used when accessing the site (refer to `config/initializers/apartment.rb:102`)

Reproduction steps:

+ Run server in local (example: `rails s`).
+ Go to path `/stream` (example: `http://localhost:3000/stream`).

## Expected result

+ Every lines should be `test`.
+ `Apartment::Tenant.current` keeps its current value.

## Actual behaviour

+ The first few lines show `test` tenant (first 11 lines on my machine).
+ The rest shows the default `development` tenant.

## System configuration

[Sample project](https://github.com/Looooong/apartment_streaming_bug). Refer to `app/controllers/streams_controller.rb`

* Database: Postgresql 9, SQLite3

* Apartment version: 2.2.0

* Rails (or ActiveRecord) version: 4.2.10, 5.2.3

* Ruby version: 2.3.3

**Comment by lcjury** [comment]
Each thread as his own connection and `ActionController::Live` execute actions on different threads.

What I think is happening here, is that you have 2 threads, the one who handles your connection does the switch (and the other is not), some actions of `ActionController:Live` are executed on the "other thread" who hasn't switched to your test tenant.

from [the docs](https://api.rubyonrails.org/v5.2.0/classes/ActionController/Live.html)
> The final caveat is that your actions are executed in a separate thread than the main thread. Make sure your actions are thread safe, and this shouldn't be a problem (don't share state across threads, etc).

~You're trying to share state across threads.~ (EDIT: mi assumption is wrong)

**Comment by Looooong** [comment]
I can understand that the **entire** action is executed in a child thread. Moreover, the main thread's locals is copied to the child thread. However, I don't get why current tenant is switched in the middle of the action after a call to `response.stream.write`.

If I modify the action like this, it works as expected:

```ruby
  def show
    response.headers['Content-Type'] = 'text/event-stream'
    render plain: Array.new(PRINT_TIMES) { Apartment::Tenant.current }.join("\n")
  ensure
    response.stream.close
  end
```

**Comment by mikecmpbll** [comment]
certainly sounds like a threading issue. i don't know enough about how ActionController::Live works unfortunately, without spending a lot of time on this.

**Comment by Looooong** [comment]
I probably agree with you, this might be a threading issue. I think I will avoid `ActionController::Live` then.
