### ISSUE TITLE
Static page for `www` subdomain

### ISSUE THREAD

**Issue by veeral-patel** [influitive/apartment#609]
Thank you for this project! This may have been answered already, but I searched the previous issues and didn't find anything.

Essentially, what I want is:

`www.mysite.com` -> render my site's static landing page
`*.mysite.com` -> render the appropriate subdomain

How would I set something like this up?

**Comment by lcjury** [comment]
I'm not sure if this going to work but:

you can try with subdomain exclusion https://github.com/influitive/apartment#switch-on-subdomain
and setting a group and using a constrain for your www routes

```
constraints :subdomain => "www" do
    resources :something
end
```

**Comment by veeral-patel** [comment]
@lcjury thanks! here's my solution:

```
class WorkspaceConstraint
  def self.matches?(request)
    subdomains = %w{ admin www }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end

Rails.application.routes.draw do
  constraints WorkspaceConstraint do
    resources :messages
    resources :channels
  end

  constraints :subdomain => 'admin' do
    resources :workspaces
  end

  constraints :subdomain => 'www' do
      # static page routes
  end

  constraints :subdomain => '' do
    # redirect
  end
end
```

Imagine you're creating Slack, and have:

- admin.slack.com
- www.slack.com
- slack.com (redirect to www.slack.com)
- *.slack.com (workspaces)
