### ISSUE TITLE
How to exclude whole all namespaced models?

### ISSUE THREAD

**Issue by bjensen** [influitive/apartment#633]
Im looking at #622 and I wish it was intended behavior, like we use a lot of engines which have their own namespaces and we want those to be in the public search path. 

Do you guys have suggestions on how to do this?

**Comment by lcjury** [comment]
You can look for all the `ActiveRecord::Base` classes on your namespace yourself

```ruby
Namespace.constants.map{|c| Namespace.const_get(c) }.select do |const|
    const.class == Class && const < ActiveRecord::Base
end
```

but, if you want to put that on apartment configuration, you need to lazyload it

```ruby
class LazyTenants
  def method_missing(method, *args, &block)
    tenants.send(method, *args, &block)
  end

  def tenants
    @tenants ||= User.constants.map{|c| User.const_get(c) }.select{|c| c.class == Class && c < ApplicationRecord } + ["Tenant"]
  end
end

Apartment.configure do |config|
  config.excluded_models = LazyTenants.new
end
```

**Comment by lcjury** [comment]
Maybe we can close this issue and keep the conversation in #622  :)?
