### ISSUE TITLE
rails 6.0 / ruby 2.6.1 install error

### ISSUE THREAD

**Issue by benbonnet** [influitive/apartment#639]
Unsure if i missed something; that is, just tried to get into a basic install; quite stuck at the beginning. in case it helps to spot the issue, here's the context :

## Steps to reproduce
Running `bundle exec rails generate apartment:install` 

## Expected behavior

A successful outcome

## Actual behavior

```
....rvm/gems/ruby-2.6.1/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: \
in `build': \
undefined method `new' for "Apartment::Reloader":String
...
```
## System configuration

rails 6.0 / ruby 2.6.1 / osx

* Database: postgres 11.5

* Apartment version: 0.24.3

* Apartment config (in `config/initializers/apartment.rb` or so): N/A

  * `use_schemas`:  N/A

* Rails (or ActiveRecord) version: rails 6.0

* Ruby version: ruby 2.6.1

**Comment by brayangr** [comment]
I think that this is because the support for rails 6 haven't been released yet, so you have to use the development branch. See #617

**Comment by benbonnet** [comment]
thx, haven't checked its availability on this version indeed
