### ISSUE TITLE
Multi database server configuration

### ISSUE THREAD

**Issue by zhaoyan1117** [influitive/apartment#69]
Hi Guys,

Does apartment work with **multiple physical database servers**? 
If so, is there any previous experience I can follow in configuring the setup? Also, do I need to revise elevators for this situation?

Any input is appreciated!

Thanks,
Yan

**Comment by piotrb** [comment]
Hey Guys,

This issue looks super interesting for us as well. We would like to use a second DB server to offload some of the tenants, effectively decide at one point that DB1 is "full" and add new tenants to DB2 .. and looks like this issue would allow us to do this somehow.

Has there been any work/updates towards this?

**Comment by mbolotin** [comment]
As @vanboom says, you can switch the ActiveRecord connection config through the reload method.  However, this won't account for rake tasks.  You'll need to override Apartment's extension of the rake tasks and call the migrator (and perhaps change the config) with each tenant yourself.

**Comment by ghempton** [comment]
This is something we desire as well. I am currently exploring the feasibility of using apartment in conjunction with [octopus](https://github.com/tchandy/octopus).

**Comment by mikecmpbll** [comment]
this issue was addressed in #271 which has been merged. it's currently _not thread safe_ because it uses the connection-based adapters, but i'm working on that in #266, just need to get the tests passing.

**Comment by rubinsh** [comment]
@ghempton - any luck on getting apartment to play well with octopus?

**Comment by aguinefolleau** [comment]
@ghempton @rubinsh , I'm also currently attempting to use Octopus for replication. Have you had any luck making it work?
