### ISSUE TITLE
Apartment + Rails.cache + cache digest

### ISSUE THREAD

**Issue by diegonogueira** [influitive/apartment#73]
Hi!
There is a way to set the namespace cache(Apartment::Database.current_database) on apartment initialize?

Thanks,
Diego

**Comment by diegonogueira** [comment]
Hi!
Now, I'm using this way:

production.rb
```ruby
  config.cache_store = :dalli_store, elasticache.servers, {
    :expires_in => 1.day, :namespace => proc { "#{Apartment::Tenant.current_tenant}-#{I18n.locale}" }
  }
```

it works fine! :)

**Comment by vanboom** [comment]
This worked for me... maybe Apartment can extend the ActiveRecord::Base.cache_key method to do this automatically? 

  def cache_key
    [super, Apartment::Database.current_tenant].join("/")
  end

**Comment by francois-ferrandis** [comment]
I've been using @gdott9's solution and it works well for me. Thank you!

Note: in **Rails 5** (well, `ActiveSupport::Cache::Store` version 5), the `namespaced_key` method has been renamed to `normalize_key`. Pull request here: https://github.com/rails/rails/pull/22215 

So the solution is as follows:
```ruby
module ApartmentCache
  private

  def normalize_key(key, options)
    "#{Apartment::Database.current}/#{super}"
  end
end
ActiveSupport::Cache::Store.send :prepend, ApartmentCache
```

**Warning**: if you are using Dalli in production, you will also need to patch the `ActiveSupport::Cache::DalliStore class`, but right now ([v2.7.6](https://github.com/petergoldstein/dalli/blob/fbb9119798e991efc59169603c161543434653ef/lib/active_support/cache/dalli_store.rb)) the method name is still `namespaced_key`, so I guess you'll have to duplicate that little prepended module:
```ruby
module ApartmentCacheForDalli
  private

  def namespaced_key(key, options)
    namespace = options[:namespace] || Apartment::Tenant.current
    "#{namespace}/#{super}"
  end
end
ActiveSupport::Cache::DalliStore.send :prepend, ApartmentCacheForDalli if Rails.env.production?
```

PS: I am not an advanced ruby/rails developer, so feel free to correct me and add suggestions. :)

**Comment by felixbuenemann** [comment]
I think setting the namespace for the `Rails.cache` is the cleanest solution, since you aren't accidentally patching other usage for the cache store, like assets cache.

If you want to namespace  the default `:file_store` cache with the current Apartment version set:

```ruby
# config/application.rb
config.cache_store = :file_store, "#{config.root}/tmp/cache/", {
  namespace: proc { Apartment::Tenant.current }
}
```

If you use a custom cache_store per environment, don't forget add the `:namespace` option, example:

```ruby
# config/environments/development.rb
config.cache_store = :memory_store, {
  size: 64.megabytes,
  namespace: proc { Apartment::Tenant.current }
}
# config/environments/production.rb
config.cache_store = :dalli_store, {
  expires_in: 1.day,
  namespace: proc { Apartment::Tenant.current }
}
```
