### ISSUE TITLE
PG::Error: ERROR:  prepared statement "aX" does not exist

### ISSUE THREAD

**Issue by rivsc** [influitive/apartment#74]
Hi,

Thanks for Apartment !
In production, I'm an error : 

PG::Error: ERROR:  prepared statement "a1" does not exist
: SELECT "groups".\* FROM "groups"  WHERE "groups"."group_id" = $1
F, [2013-08-26T10:08:58.509620 #8195] FATAL -- : 
ActionView::Template::Error (PG::Error: ERROR:  prepared statement "a1" does not exist

This code is in a before_filter in application_controller.rb

```
begin
Apartment::Database.switch(schema_name)
rescue
Apartment::Database.create(schema_name)
Apartment::Database.switch(schema_name)
end
```

I'm using ruby 1.9.3, postgresql 9.1, pg (0.14.0 or 0.16.0) , Rails 4.0.0 and Passenger + Nginx.

Regards,
Rivsc

**Comment by mikecmpbll** [comment]
closing as unreproducable?
