### ISSUE TITLE
Not working when using UUIDs

### ISSUE THREAD

**Issue by richardkall** [influitive/apartment#86]
I'm using UUID as the primary key instead of ID. I have enabled this using the following migrations: 

``` ruby
class EnableUuidOsspExtension < ActiveRecord::Migration
  def change
    enable_extension 'uuid-ossp'
  end
end

class CreateItems < ActiveRecord::Migration
  def change
    create_table :items, id: :uuid do |t|
      ...
    end
  end
end
```

And this gets included in my **schema.rb**:

``` ruby
ActiveRecord::Schema.define(version: 20131103132401) do
  ...
  enable_extension "uuid-ossp"
  ...

  create_table "items", id: :uuid, default: "uuid_generate_v4()", force: true do |t|
    ...
  end
end
```

Normal migrations run fine but when I create a schema (and the schema.db gets imported) it does not work.

If i run `Apartment::Database.create('testing')` in rails console I get the following errors:

``` ruby
irb(main):001:0> Apartment::Database.create('testing')
  (0.6ms)  CREATE SCHEMA "testing"
  SQL (0.4ms)  CREATE EXTENSION IF NOT EXISTS "plpgsql"
  SQL (0.3ms)  CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
  (1.7ms)  CREATE TABLE "items" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(), "name" character varying(255)) 
  PG::UndefinedFunction: ERROR:  function uuid_generate_v4() does not exist
```

See full error here: https://gist.github.com/richardkall/7384204

Any ideas?

**Comment by baghayi** [comment]
@petervandenabeele 's solution work for me. 
You saved my life man :+1:

**Comment by jhubert** [comment]
@bradrobertson I was having this issue migrating to the apartment gem on an existing application. I ended up figuring out that the extension was already installed into the public schema so it wouldn't get installed on the shared_extensions schema. I had to run ` ALTER EXTENSION "uuid-ossp" SET SCHEMA shared_extensions;` manually to fix this. Just worth noting. :)

**Comment by bradrobertson** [comment]
@jhubert good to know, thx for the info!

**Comment by edwardsharp** [comment]
Actually, what worked for me was to enable the extension for the pg_catalog schema (which always seems to be in the search path even with apartment changing it). I tried putting 'public' in the persistent_schemas config but that would wipe out the tables in the public schema which is undesirable for me.  

```'CREATE EXTENSION "uuid-ossp" SCHEMA pg_catalog;'```

**Comment by eliotsykes** [comment]
For Postgres.app 9.4.4.1 on Mac OS X, in a Rails 4.1.x app, I followed steps similar to @petervandenabeele as above at https://github.com/influitive/apartment/issues/86#issuecomment-51964542:

1. Find the oldest migration in `db/migrate/` that uses the `uuid` column type.
2. Insert as the first line of this migration's `change` method to enable the uuid-ossp extension with:

```diff
class YourMigrationNameAlreadyHere < ActiveRecord::Migration
  def change
+    enable_extension 'uuid-ossp'
```
3. Drop & recreate your test db:

```sh
RAILS_ENV=test bin/rake db:drop db:create db:migrate db:rollback db:test:prepare
```
This will regenerate `db/schema.rb` with a `enable_extension 'uuid-ossp'` line that was previously missing near the top of `schema.rb`.

**Comment by kofiasare** [comment]
update to @edwardsharp solution
```ruby
class EnableUuid < ActiveRecord::Migration[6.0]
  def change
    execute 'CREATE EXTENSION pgcrypto WITH SCHEMA pg_catalog;'
  end
end
```

**Comment by ivancortesromero** [comment]
@kofiasare thanks, it worked perfectly assuming my original (first) migration already be written as you suggested. But in my case, my first migration was enabling `pgcrypto` as follows:

```rb
class EnablePgcryptoExtension < ActiveRecord::Migration[6.0]
  def change
    enable_extension 'pgcrypto'
  end
end
```

So I don't know how to update the way the extension is enabled.
