### ISSUE TITLE
Rescue Apartment errors and redirect them

### ISSUE THREAD

**Issue by cubytz** [influitive/apartment#92]
Hello,

I am using apartment and I am loving it, but I would like to rescue errors like "Apartment::SchemaNotFound" with a redirect to the root_url, but had no success doing it. I tried the following solution :
http://stackoverflow.com/questions/11667710/how-to-rescue-custom-exceptions-coming-from-a-middleware-in-rails-3-2
But I can't seem to make it work. Is there something I am missing?
Thank you for your precious help!

**Comment by scott-stewart** [comment]
I realize this thread is older and @bradrobertson 's solution is from 2013, but just putting this here for posterity (maybe there is better way to do this now?) but I now had to rescue ::Apartment::TenantNotFound instead of ::Apartment::SchemaNotFound

**Comment by bradrobertson** [comment]
yup! naming changed. I updated my comment, thx!
